package webrogue:gfx;

interface windowing {
    // BEGIN GENERATED CODE
    enum mouse-button {
        unknown,
        left,
        right,
        middle,
    }
    
    enum named-key {
        unknown,
        alt,
        alt-graph,
        caps-lock,
        control,
        fn,
        fn-lock,
        meta,
        num-lock,
        scroll-lock,
        shift,
        symbol,
        symbol-lock,
        enter,
        tab,
        arrow-down,
        arrow-left,
        arrow-right,
        arrow-up,
        end,
        home,
        page-down,
        page-up,
        backspace,
        clear,
        copy,
        cr-sel,
        cut,
        delete,
        erase-eof,
        ex-sel,
        insert,
        paste,
        redo,
        undo,
        accept,
        again,
        attn,
        cancel,
        context-menu,
        escape,
        execute,
        find,
        help,
        pause,
        play,
        props,
        select,
        zoom-in,
        zoom-out,
        brightness-down,
        brightness-up,
        eject,
        log-off,
        power,
        power-off,
        print-screen,
        hibernate,
        standby,
        wake-up,
        all-candidates,
        alphanumeric,
        code-input,
        compose,
        convert,
        dead,
        final-mode,
        group-first,
        group-last,
        group-next,
        group-previous,
        mode-change,
        next-candidate,
        non-convert,
        previous-candidate,
        process,
        single-candidate,
        hangul-mode,
        hanja-mode,
        junja-mode,
        eisu,
        hankaku,
        hiragana,
        hiragana-katakana,
        kana-mode,
        kanji-mode,
        katakana,
        romaji,
        zenkaku,
        zenkaku-hankaku,
        soft-1,
        soft-2,
        soft-3,
        soft-4,
        channel-down,
        channel-up,
        close,
        mail-forward,
        mail-reply,
        mail-send,
        media-close,
        media-fast-forward,
        media-pause,
        media-play,
        media-play-pause,
        media-record,
        media-rewind,
        media-stop,
        media-track-next,
        media-track-previous,
        new,
        open,
        print,
        save,
        spell-check,
        key-1-1,
        key-1-2,
        audio-balance-left,
        audio-balance-right,
        audio-bass-boost-down,
        audio-bass-boost-toggle,
        audio-bass-boost-up,
        audio-fader-front,
        audio-fader-rear,
        audio-surround-mode-next,
        audio-treble-down,
        audio-treble-up,
        audio-volume-down,
        audio-volume-up,
        audio-volume-mute,
        microphone-toggle,
        microphone-volume-down,
        microphone-volume-up,
        microphone-volume-mute,
        speech-correction-list,
        speech-input-toggle,
        launch-application-1,
        launch-application-2,
        launch-calendar,
        launch-contacts,
        launch-mail,
        launch-media-player,
        launch-music-player,
        launch-phone,
        launch-screen-saver,
        launch-spreadsheet,
        launch-web-browser,
        launch-web-cam,
        launch-word-processor,
        browser-back,
        browser-favorites,
        browser-forward,
        browser-home,
        browser-refresh,
        browser-search,
        browser-stop,
        app-switch,
        call,
        camera,
        camera-focus,
        end-call,
        go-back,
        go-home,
        headset-hook,
        last-number-redial,
        notification,
        manner-mode,
        voice-dial,
        tv,
        tv-3d-mode,
        tv-antenna-cable,
        tv-audio-description,
        tv-audio-description-mix-down,
        tv-audio-description-mix-up,
        tv-contents-menu,
        tv-data-service,
        tv-input,
        tv-input-component-1,
        tv-input-component-2,
        tv-input-composite-1,
        tv-input-composite-2,
        tv-input-hdmi-1,
        tv-input-hdmi-2,
        tv-input-hdmi-3,
        tv-input-hdmi-4,
        tv-input-vga-1,
        tv-media-context,
        tv-network,
        tv-number-entry,
        tv-power,
        tv-radio-service,
        tv-satellite,
        tv-satellite-bs,
        tv-satellite-cs,
        tv-satellite-toggle,
        tv-terrestrial-analog,
        tv-terrestrial-digital,
        tv-timer,
        avr-input,
        avr-power,
        color-f-0red,
        color-f-1green,
        color-f-2yellow,
        color-f-3blue,
        color-f-4grey,
        color-f-5brown,
        closed-caption-toggle,
        dimmer,
        display-swap,
        dvr,
        exit,
        favorite-clear-0,
        favorite-clear-1,
        favorite-clear-2,
        favorite-clear-3,
        favorite-recall-0,
        favorite-recall-1,
        favorite-recall-2,
        favorite-recall-3,
        favorite-store-0,
        favorite-store-1,
        favorite-store-2,
        favorite-store-3,
        guide,
        guide-next-day,
        guide-previous-day,
        info,
        instant-replay,
        link,
        list-program,
        live-content,
        lock,
        media-apps,
        media-audio-track,
        media-last,
        media-skip-backward,
        media-skip-forward,
        media-step-backward,
        media-step-forward,
        media-top-menu,
        navigate-in,
        navigate-next,
        navigate-out,
        navigate-previous,
        next-favorite-channel,
        next-user-profile,
        on-demand,
        pairing,
        pin-p-down,
        pin-p-move,
        pin-p-toggle,
        pin-p-up,
        play-speed-down,
        play-speed-reset,
        play-speed-up,
        random-toggle,
        rc-low-battery,
        record-speed-next,
        rf-bypass,
        scan-channels-toggle,
        screen-mode-next,
        settings,
        split-screen-toggle,
        stb-input,
        stb-power,
        subtitle,
        teletext,
        video-mode-next,
        wink,
        zoom-toggle,
        f1,
        f2,
        f3,
        f4,
        f5,
        f6,
        f7,
        f8,
        f9,
        f10,
        f11,
        f12,
        f13,
        f14,
        f15,
        f16,
        f17,
        f18,
        f19,
        f20,
        f21,
        f22,
        f23,
        f24,
        f25,
        f26,
        f27,
        f28,
        f29,
        f30,
        f31,
        %f32,
        f33,
        f34,
        f35,
    }
    
    enum physical-key {
        unknown,
        backquote,
        backslash,
        bracket-left,
        bracket-right,
        comma,
        digit-0,
        digit-1,
        digit-2,
        digit-3,
        digit-4,
        digit-5,
        digit-6,
        digit-7,
        digit-8,
        digit-9,
        equal,
        intl-backslash,
        intl-ro,
        intl-yen,
        key-a,
        key-b,
        key-c,
        key-d,
        key-e,
        key-f,
        key-g,
        key-h,
        key-i,
        key-j,
        key-k,
        key-l,
        key-m,
        key-n,
        key-o,
        key-p,
        key-q,
        key-r,
        key-s,
        key-t,
        key-u,
        key-v,
        key-w,
        key-x,
        key-y,
        key-z,
        minus,
        period,
        quote,
        semicolon,
        slash,
        alt-left,
        alt-right,
        backspace,
        caps-lock,
        context-menu,
        control-left,
        control-right,
        enter,
        meta-left,
        meta-right,
        shift-left,
        shift-right,
        space,
        tab,
        convert,
        kana-mode,
        lang-1,
        lang-2,
        lang-3,
        lang-4,
        lang-5,
        non-convert,
        delete,
        end,
        help,
        home,
        insert,
        page-down,
        page-up,
        arrow-down,
        arrow-left,
        arrow-right,
        arrow-up,
        num-lock,
        numpad-0,
        numpad-1,
        numpad-2,
        numpad-3,
        numpad-4,
        numpad-5,
        numpad-6,
        numpad-7,
        numpad-8,
        numpad-9,
        numpad-add,
        numpad-backspace,
        numpad-clear,
        numpad-clear-entry,
        numpad-comma,
        numpad-decimal,
        numpad-divide,
        numpad-enter,
        numpad-equal,
        numpad-hash,
        numpad-memory-add,
        numpad-memory-clear,
        numpad-memory-recall,
        numpad-memory-store,
        numpad-memory-subtract,
        numpad-multiply,
        numpad-paren-left,
        numpad-paren-right,
        numpad-star,
        numpad-subtract,
        escape,
        fn,
        fn-lock,
        print-screen,
        scroll-lock,
        pause,
        browser-back,
        browser-favorites,
        browser-forward,
        browser-home,
        browser-refresh,
        browser-search,
        browser-stop,
        eject,
        launch-app-1,
        launch-app-2,
        launch-mail,
        media-play-pause,
        media-select,
        media-stop,
        media-track-next,
        media-track-previous,
        power,
        sleep,
        audio-volume-down,
        audio-volume-mute,
        audio-volume-up,
        wake-up,
        abort,
        resume,
        suspend,
        again,
        copy,
        cut,
        find,
        open,
        paste,
        props,
        select,
        undo,
        hiragana,
        katakana,
        unidentified,
        f1,
        f2,
        f3,
        f4,
        f5,
        f6,
        f7,
        f8,
        f9,
        f10,
        f11,
        f12,
        f13,
        f14,
        f15,
        f16,
        f17,
        f18,
        f19,
        f20,
        f21,
        f22,
        f23,
        f24,
        f25,
        f26,
        f27,
        f28,
        f29,
        f30,
        f31,
        %f32,
        f33,
        f34,
        f35,
        brightness-down,
        brightness-up,
        display-toggle-int-ext,
        keyboard-layout-select,
        launch-assistant,
        launch-control-panel,
        launch-screen-saver,
        mail-forward,
        mail-reply,
        mail-send,
        media-fast-forward,
        media-pause,
        media-play,
        media-record,
        media-rewind,
        microphone-mute-toggle,
        privacy-screen-toggle,
        keyboard-backlight-toggle,
        select-task,
        show-all-windows,
        zoom-toggle,
    }
    
    variant window-event {
        /// button, down, x, y, is-touch
        mouse-button(tuple<mouse-button, bool, u32, u32, bool>),
        /// x, y
        mouse-motion(tuple<u32, u32>),
        /// down, named-key, physical-key, text
        key(tuple<bool, named-key, physical-key, list<u8>>),
        quit,
        window-resized,
        gl-resized,
    }
    // END GENERATED CODE
    resource window {
        constructor();
        get-logical-size: func() -> tuple<u32, u32>;
        get-physical-size: func() -> tuple<u32, u32>;
        get-vulkan-id: func() -> u32;
        event-stream: func() -> stream<window-event>;
    }

    close-window: func(window: window);

}

interface vulkan {
    check-presence: func() -> bool;

    resource renderer {
        constructor(name: list<u8>);
        register-blob: func(
            res-id: u32,
            buf: list<u8>
        );
        create-shmem: func(
            buf: list<u8>
        ) -> u32;
        create-device-memory-blob: func(
            blob-id: u64,
            size: u64
        ) -> u32;

        resource-unref: func(res-id: u32);
        create-sync: func(value: u64) -> u32;
        sync-unref: func(sync-id: u32);
        sync-read: func(sync-id: u32) -> u64;
        sync-write: func(sync-id: u32, value: u64);
        submit-cmd: func(
            headers: list<u8>,
            cmds: list<u8>,
            syncs: list<u8>
        );
        sync-wait: func(
            %flags: u32,
            timeout: u32,
            syncs: list<u32>,
        ) -> s32;
        get-max-timeline-count: func() -> u32;
        get-capset: func(
            id: u32,
            version: u32
        ) -> list<u8>;
        context-init: func(capset-id: u32);
    }
}

interface cpu-rendering {
    use windowing.{window};

    // TODO return an error if, for example, size changed
    present-pixels: func(
        window: borrow<window>,
        buf: list<u32>,
    );
}

interface device-info {
    get-os-family: func() -> u8;
}

world gfx {
    import windowing;
    import vulkan;
    import cpu-rendering;
    import device-info;
}
