[package]
name = "webrogue_android"
version = "0.1.0"
edition = "2021"

[lib]
name = "webrogue_android"
crate-type = ["staticlib"]

[dependencies]
anyhow = { version = "1" }
webrogue_runtime = { path = "../../../../../../crates/runtime" }
webrogue_backend_v8 = { path = "../../../../../../crates/backend_v8", default-features = false, features = ["v8_submodule"] }
webrogue_wasi_sync = { path = "../../../../../../crates/wasi_sync" }
webrogue_std_stream_sdl = { path = "../../../../../../crates/std_stream_sdl", default-features = false }
