[package]
name = "webrogue-gl"
version.workspace = true
authors.workspace = true
edition.workspace = true

[features]
fallback = []

[dependencies]
webrogue-gfx = { workspace = true }
wasmer = { workspace = true, default-features = false }
anyhow = { workspace = true }
