#pragma once

// generated by ddl2cpp
// clang-format off

#include <sqlpp11/table.h>
#include <sqlpp11/data_types.h>
#include <sqlpp11/char_sequence.h>

namespace webrogue
{
namespace log2048
{
  namespace Log2048Scores_
  {
    struct Id
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "id";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T id;
            T& operator()() { return id; }
            const T& operator()() const { return id; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::must_not_insert, sqlpp::tag::must_not_update, sqlpp::tag::can_be_null>;
    };
    struct X
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "x";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T x;
            T& operator()() { return x; }
            const T& operator()() const { return x; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct Y
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "y";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T y;
            T& operator()() { return y; }
            const T& operator()() const { return y; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
    struct Score
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "score";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T score;
            T& operator()() { return score; }
            const T& operator()() const { return score; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::require_insert>;
    };
  } // namespace Log2048Scores_

  struct Log2048Scores: sqlpp::table_t<Log2048Scores,
               Log2048Scores_::Id,
               Log2048Scores_::X,
               Log2048Scores_::Y,
               Log2048Scores_::Score>
  {
    static constexpr const char ddl[] = "CREATE TABLE IF NOT EXISTS log2048_scores (\n    id INTEGER PRIMARY KEY AUTOINCREMENT,\n    x INTEGER NOT NULL,\n    y INTEGER NOT NULL,\n    score INTEGER NOT NULL\n)";
    struct _alias_t
    {
      static constexpr const char _literal[] =  "log2048_scores";
      using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
      template<typename T>
      struct _member_t
      {
        T log2048Scores;
        T& operator()() { return log2048Scores; }
        const T& operator()() const { return log2048Scores; }
      };
    };
  };
} // namespace log2048
} // namespace webrogue
