[package]
name = "webrogue-macos"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
name = "webrogue_macos"
crate-type = ["staticlib"]

[dependencies]
anyhow =  { workspace = true }
webrogue-runtime =  { workspace = true }
webrogue-backend-wasmtime =  { workspace = true }
webrogue-wasi =  { workspace = true }
webrogue-gl =  { workspace = true }
webrogue-gfx =  { workspace = true }
webrogue-wasi-sync =  { workspace = true }
webrogue-std-stream-os = { workspace = true }
webrogue-gfx-ffi = { workspace = true }
