[package]
name = "webrogue-macos"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
name = "webrogue_macos"
crate-type = ["staticlib"]

[dependencies]
anyhow = { workspace = true }
webrogue-runtime = { workspace = true, features = ["gl", "cranelift"] }
