[package]
name = "webrogue-aot-linker"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }

[build-dependencies]
cmake = { workspace = true }
