[package]
name = "webrogue_backend_web"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
webrogue_runtime = { workspace = true }
anyhow = { workspace = true }
webrogue_backend_web_macro = { workspace = true }
