[package]
name = "webrogue_backend_web"
version = "0.1.0"
edition = "2021"

[dependencies]
webrogue_runtime = { path = "../../../crates/runtime"}
anyhow = { version = "1" }
webrogue_backend_web_macro = { path = "macro" }
