[package]
name = "webrogue-android"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[features]
launcher = [
    "webrogue-wasmtime/jit",
    "dep:jni",
    "dep:serde",
    "dep:serde_json",
    "webrogue-virgl/lib-impl",
    "dep:webrogue-hub-debuggee",
    "dep:tokio",
]
runner = [
    "webrogue-wasmtime/aot",
    "webrogue-virgl/lib-impl",
    "dep:webrogue-common",
]

[lib]
name = "webrogue"
crate-type = ["cdylib"]

[dependencies]
anyhow = { workspace = true }
webrogue-wasmtime = { workspace = true }
winit = { workspace = true }
webrogue-virgl = { workspace = true }
webrogue-gfx-winit = { workspace = true }
jni = { version = "0.22", optional = true }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
webrogue-gfx = { workspace = true }
webrogue-vfs = { workspace = true }
webrogue-common = { workspace = true, optional = true }
tokio = { workspace = true, features = ["full"], optional = true }
webrogue-hub-debuggee = { workspace = true, optional = true }

[target.'cfg(target_os = "android")'.dependencies]
winit-android = { workspace = true }
android-activity = { workspace = true, features = ["native-activity"] }
log = { workspace = true }
android_logger = { workspace = true }
ndk-sys = { workspace = true }
ndk = { workspace = true }
