set -ex

INPUT_DIR=$1
OUTPUT_PATH=$2

LIPO_PATHS=()
LIPO_PATHS_I=0

for DEST_ARCH in $ARCHS; do
    LIPO_PATHS[$LIPO_PATHS_I]="$INPUT_DIR/aot.$DEST_ARCH.$PLATFORM_NAME.o"
    LIPO_PATHS_I=$(expr $LIPO_PATHS_I '+' 1)
done

lipo -create "${LIPO_PATHS[@]}" -output "$OUTPUT_PATH"
