[package]
name = "webrogue-default-runtime"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
webrogue-runtime = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
tokio = { version = "1", features = ["rt"] }
