[package]
name = "webrogue-default-runtime"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
webrogue-runtime = { workspace = true, features = ["gl", "wamr"] }
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
webrogue-gfx = { workspace = true, features = ["fallback"] }
