[package]
name = "webrogue-runtime"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
webrogue-wrapp = { workspace = true }
futures =  { workspace = true }
wasmparser = { workspace = true }
wasmer = { workspace = true, default-features = false, features = ["cranelift"] }
wasmer-wasix = { workspace = true }
virtual-fs = { workspace = true }
