[package]
name = "webrogue_runtime"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
webrogue_wrapp = { workspace = true }
wasi-common = { workspace = true, default-features = false, features = ["trace_log"] }
wiggle = { workspace = true, default-features = false }
futures =  { workspace = true }
wasmparser = { workspace = true }
