[package]
name = "webrogue-runtime"
version.workspace = true
authors.workspace = true
edition.workspace = true

[features]
gl = ["gfx", "dep:webrogue-gl"]
gfx = ["dep:webrogue-gfx"]

aot = ["wasmer/sys", "wasmer/static-artifact-load"]
singlepass = ["wasmer/singlepass"]
cranelift = ["wasmer/cranelift"]
llvm = ["wasmer/llvm"]
wamr = ["wasmer/wamr"]

[dependencies]
webrogue-gl = { workspace = true, optional = true }
webrogue-gfx = { workspace = true, optional = true }

anyhow = { workspace = true }
# webrogue-wrapp = { workspace = true }
wasmer = { workspace = true, default-features = false }
wasmer-wasix = { workspace = true }
virtual-fs = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread"] }
webc = { workspace = true }

[build-dependencies]
cc = { workspace = true }
