[package]
name = "webrogue-runtime"
version.workspace = true
authors.workspace = true
edition.workspace = true

[features]
cranelift = ["wasmtime/cranelift"]
aot = ["dep:webrogue-aot-data"]
cache = ["wasmtime/cache"]

[dependencies]
webrogue-gfx = { workspace = true }
anyhow = { workspace = true }
webrogue-wrapp = { workspace = true }
wasmtime = { workspace = true, default-features = false, features = ["runtime", "threads"] }
wasi-common = { workspace = true, default-features = false, features = ["sync"] }
wiggle = { workspace = true, default-features = false, features = ["wasmtime"] }
webrogue-aot-data = { workspace = true, optional = true }
