[build]
# target = "wasm32-unknown-emscripten"

[target.wasm32-unknown-emscripten]
rustflags = ["-Ctarget-feature=+atomics,+bulk-memory,+mutable-globals", "--codegen", "panic=abort"]
#rustflags = [
#    "-Ctarget-feature=+mutable-globals",
#    "--codegen", "panic=abort"
#]
