[package]
name = "webrogue-wasmtime"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[features]
jit = ["wasmtime/cranelift", "wasmtime/parallel-compilation", "wasmtime/addr2line"]
aot = ["dep:webrogue-aot-data"]
cache = ["wasmtime/cache"] # TODO "wasmtime/incremental-cache"
debug = ["jit", "wasmtime/debug"] # , "wasmtime/debug-builtins"
pulley = ["wasmtime/pulley"]

[dependencies]
webrogue-gfx = { workspace = true }
webrogue-virgl = { workspace = true }
anyhow = { workspace = true }
webrogue-wrapp = { workspace = true }
wasmtime = { workspace = true, default-features = false, features = ["runtime", "threads", "gc", "gc-drc", "anyhow", "component-model-async", "debug"] }
wasmtime-wasi = { workspace = true, default-features = false, features = ["p3"] }
webrogue-vfs = { workspace = true, features = ["wasmtime"] }
webrogue-debugger = { workspace = true }
tokio = { workspace = true, features = ["net", "time", "rt-multi-thread"] }
webrogue-aot-data = { workspace = true, optional = true }
gdbstub_arch = { workspace = true }
futures = { workspace = true }
