[package]
name = "webrogue_backend_wasmtime"
version = "0.1.0"
edition = "2021"

[dependencies]
wasmtime = { path = "../../external/wasmtime/crates/wasmtime" }
webrogue_runtime = { path = "../webrogue_runtime"}
anyhow = { version = "1" }
webrogue_macros = {path = "../webrogue_macros"}
