[package]
name = "webrogue-android"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[features]
launcher = ["webrogue-wasmtime/cranelift"]
runner = ["webrogue-wasmtime/aot"]

[lib]
name = "webrogue_android"
crate-type = ["staticlib"]

[dependencies]
anyhow = { workspace = true }
webrogue-wasmtime = { workspace = true }
