[package]
name = "webrogue-backend-v8-macro"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
webrogue-macro-common = { workspace = true }

[lib]
proc-macro = true
