[package]
name = "webrogue-gfx-fallback"
version.workspace = true
authors.workspace = true
edition.workspace = true

[build-dependencies]
cmake = { version = "^0.1.47" }
reqwest = { version = "0.12", features = ["blocking"] }
zip-extract = { version = "0.2.1" }
