include(${CMAKE_CURRENT_LIST_DIR}/../../../cmake/parse_api_header.cmake)

parse_api_header(FUNC_COUNT num_of_funcs)

set(out_content "#include \"wasm2c_runtime.hpp\"\nusing namespace webrogue::core;\n\n// clang-format off\n")
string(APPEND out_content "extern \"C\" {\n")
foreach(func_i RANGE 1 ${num_of_funcs})
    parse_api_header(
        FUNC_MACRO WASI_FUNCTION
        FUNC_ID ${func_i} 
        FUNC_NAME func_name
        RET_TYPE ret_type
        ARGS args
        ARGS_WITHOUT_TYPES args_without_types
    )
    string(REPLACE "WASMRawU32" "uint32_t" ret_type "${ret_type}")
    string(REPLACE "WASMRawI32" "int32_t" ret_type "${ret_type}")
    string(REPLACE "WASMRawF32" "float" ret_type "${ret_type}")
    string(REPLACE "WASMRawU64" "uint64_t" ret_type "${ret_type}")
    string(REPLACE "WASMRawI64" "int64_t" ret_type "${ret_type}")
    string(REPLACE "WASMRawF64" "double" ret_type "${ret_type}")

    string(REPLACE "WASMRawU32" "uint32_t" args "${args}")
    string(REPLACE "WASMRawI32" "int32_t" args "${args}")
    string(REPLACE "WASMRawF32" "float" args "${args}")
    string(REPLACE "WASMRawU64" "uint64_t" args "${args}")
    string(REPLACE "WASMRawI64" "int64_t" args "${args}")
    string(REPLACE "WASMRawF64" "double" args "${args}")

    set(nargs "${args}")
    if(nargs)
        string(REPLACE "uint32_t " "WASMRawU32::make(" nargs "${nargs}")
        string(REPLACE "int32_t " "WASMRawI32::make(" nargs "${nargs}")
        string(REPLACE "float " "WASMRawF32::make(" nargs "${nargs}")
        string(REPLACE "uint64_t " "WASMRawU64::make(" nargs "${nargs}")
        string(REPLACE "int64_t " "WASMRawI64::make(" nargs "${nargs}")
        string(REPLACE "double " "WASMRawF64::make(" nargs "${nargs}")
        string(REPLACE "," ")," nargs "${nargs}")
        string(APPEND nargs ")")
    endif()

    if("${args}" STREQUAL "")
        set(delim "")
    else()
        set(delim ", ")
    endif()
    set(w2c_args ${args})
    string(REPLACE "void *" "u32 " w2c_args "${w2c_args}")
    string(REPLACE "uint32_t" "u32" w2c_args "${w2c_args}")
    string(REPLACE "int32_t" "u32" w2c_args "${w2c_args}")
    string(REPLACE "uint64_t" "u64" w2c_args "${w2c_args}")
    string(REPLACE "int64_t" "u64" w2c_args "${w2c_args}")
    string(REPLACE "double" "double" w2c_args "${w2c_args}")

    set(nargs "${args}")
    if(nargs)
        string(REPLACE "uint32_t " "WASMRawU32::make(" nargs "${nargs}")
        string(REPLACE "int32_t " "WASMRawI32::make(" nargs "${nargs}")
        string(REPLACE "float " "WASMRawF32::make(" nargs "${nargs}")
        string(REPLACE "uint64_t " "WASMRawU64::make(" nargs "${nargs}")
        string(REPLACE "int64_t " "WASMRawI64::make(" nargs "${nargs}")
        string(REPLACE "double " "WASMRawF64::make(" nargs "${nargs}")
        string(REPLACE "," ")," nargs "${nargs}")
        string(APPEND nargs ")")
    endif()

    set(w2c_args_without_types ${nargs})
    string(REPLACE "void *" "runtime->linked.w2c_memory.data + " w2c_args_without_types "${w2c_args_without_types}")
    string(REPLACE "uint32_t " "" w2c_args_without_types "${w2c_args_without_types}")
    string(REPLACE "int32_t " "" w2c_args_without_types "${w2c_args_without_types}")
    string(REPLACE "uint64_t " "" w2c_args_without_types "${w2c_args_without_types}")
    string(REPLACE "int64_t " "" w2c_args_without_types "${w2c_args_without_types}")
    string(REPLACE "double " "" w2c_args_without_types "${w2c_args_without_types}")

    set(w2c_ret_type ${ret_type})
    string(REPLACE "void *" "void *" w2c_ret_type "${w2c_ret_type}")
    string(REPLACE "uint32_t" "u32" w2c_ret_type "${w2c_ret_type}")
    string(REPLACE "int32_t" "u32" w2c_ret_type "${w2c_ret_type}")
    string(REPLACE "uint64_t" "u64" w2c_ret_type "${w2c_ret_type}")
    string(REPLACE "int64_t" "u64" w2c_ret_type "${w2c_ret_type}")
    string(REPLACE "double" "double" w2c_ret_type "${w2c_ret_type}")

    string(APPEND out_content "${w2c_ret_type} w2c_wasi__snapshot__preview1_${func_name}(struct w2c_wasi__snapshot__preview1 *env${delim}${w2c_args}) {\n") 
    string(APPEND out_content "    auto runtime =\n")
    string(APPEND out_content "        ((webrogue::runtimes::wasm2c::Wasm2cModsRuntime *)env);\n")
    string(APPEND out_content "    return runtime->wasiObject.${func_name}(${w2c_args_without_types})")
    if("${ret_type}" STREQUAL "void")
    else()
        string(APPEND out_content ".get()")
    endif()
    string(APPEND out_content ";\n")
    string(APPEND out_content "}\n")
    string(APPEND out_content "\n")
endforeach()
string(APPEND out_content "}\n")
file(WRITE ${WR_API_EMBEDDING}.cpp "${out_content}")
