name: webrogue
configs:
  Debug: debug
  Release: release
  ReleaseLocal: release
projectReferences:
  SDL:
    path: ./external/SDL2/Xcode/SDL/SDL.xcodeproj
settings:
  base:
    DEVELOPMENT_TEAM: LC5F8UX2W7
    MACOSX_DEPLOYMENT_TARGET: 12.0
    IPHONEOS_DEPLOYMENT_TARGET: 14.0
    GENERATE_INFOPLIST_FILE: true
    MARKETING_VERSION: 0.1
    CURRENT_PROJECT_VERSION: 1
  configs:
    Debug:
      CODE_SIGN_IDENTITY: "-"
      CARGO_CONFIG: Debug
    Release:
      CODE_SIGN_IDENTITY: "Apple Development"
      CARGO_CONFIG: Release
    ReleaseLocal:
      CODE_SIGN_IDENTITY: "-"
      CARGO_CONFIG: Release
options:
  createIntermediateGroups: true
targets:
  Launcher:
    type: application
    platform: macOS
    sources:
    - macOS/Launcher
    settings:
      base:
        CODE_SIGN_ENTITLEMENTS: macOS/Launcher/launcher.entitlements
        INFOPLIST_FILE: macOS/Launcher/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: io.github.webrogue-runtime.WebrogueLauncher
        PRODUCT_NAME: webrogue Launcher
        ENABLE_HARDENED_RUNTIME: true
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.utilities
        ENABLE_PREVIEWS: true
    dependencies:
    - target: WebrogueCommon
    - target: Runtime
      embed: true
      codeSign: true
      copy:
        destination: executables
    - bundle: libEGL.dylib
      embed: true
      codeSign: true
    - bundle: libGLESv2.dylib
      embed: true
      codeSign: true
    preBuildScripts:
      - script: "cd \"${BUILT_PRODUCTS_DIR}\"; sh ${SRCROOT}/macOS/Runtime/rust/scripts/download_angle_bin.sh"
        name: Download ANGLE
        inputFiles:
          - ${SRCROOT}/macOS/runtime/rust/scripts/download_angle_bin.sh
        outputFiles:
          - ${BUILT_PRODUCTS_DIR}/macos_fat.zip
          - ${BUILT_PRODUCTS_DIR}/libEGL.dylib
          - ${BUILT_PRODUCTS_DIR}/libGLESv2.dylib
  Runtime:
    type: tool
    platform: macOS
    sources:
    - path: macOS/Runtime
      excludes:
      - "**/rust"
    - ../crates/gfx_ffi/src/webrogue_gfx_ffi_sdl2.c
    settings:
      base:
        CODE_SIGN_ENTITLEMENTS: macOS/Runtime/runtime.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: io.github.webrogue-runtime.WebrogueLauncher.Runtime
        PRODUCT_NAME: webrogue_runtime
        OTHER_LDFLAGS: "-lwebrogue_macos"
        LIBRARY_SEARCH_PATHS: "$(BUILD_DIR)/rust_artifacts/$(CONFIGURATION)/$(PLATFORM_NAME)"
        HEADER_SEARCH_PATHS: "$(SRCROOT)/external/SDL2/include"
        ENABLE_HARDENED_RUNTIME: true
    dependencies:
    - target: Cargo macOS
    - target: SDL/Static Library
    - sdk: Quartz.framework
    - sdk: Metal.framework
    - sdk: IOKit.framework
    - sdk: GameController.framework
    - sdk: ForceFeedback.framework
    - sdk: CoreVideo.framework
    - sdk: CoreHaptics.framework
    - sdk: CoreFoundation.framework
    - sdk: CoreAudio.framework
    - sdk: Cocoa.framework
    - sdk: Carbon.framework
    - sdk: AudioToolbox.framework
  Launcher_iOS:
    type: application
    platform: iOS
    sources:
    - path: iOS
      excludes:
      - "**/rust"
    - ../crates/gfx_ffi/src/webrogue_gfx_ffi_sdl2.c
    settings:
      base:
        INFOPLIST_FILE: iOS/Info.plist
        CODE_SIGN_ENTITLEMENTS: iOS/ios.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: io.github.webrogue-runtime.WebrogueLauncher
        PRODUCT_NAME: webrogue
        SWIFT_OBJC_BRIDGING_HEADER: "$(SRCROOT)/iOS/Source/webrogue-Bridging-Header.h"
        OTHER_LDFLAGS: "-lwebrogue_ios"
        LIBRARY_SEARCH_PATHS: "$(BUILD_DIR)/rust_artifacts/$(CONFIGURATION)/$(PLATFORM_NAME)"
        HEADER_SEARCH_PATHS: "$(SRCROOT)/external/SDL2/include"
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.utilities
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight UIInterfaceOrientationPortrait"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown"
        ENABLE_PREVIEWS: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UILaunchStoryboardName: LaunchScreen.storyboard
    dependencies:
    - target: Cargo iOS
    - target: SDL/Static Library-iOS
    - target: WebrogueCommon
    - sdk: UIKit.framework
    - sdk: QuartzCore.framework
    - sdk: OpenGLES.framework
    - sdk: Metal.framework
    - sdk: IOKit.framework
    - sdk: GameController.framework
    - sdk: CoreVideo.framework
    - sdk: CoreMotion.framework
    - sdk: CoreHaptics.framework
    - sdk: CoreGraphics.framework
    - sdk: CoreFoundation.framework
    - sdk: CoreBluetooth.framework
    - sdk: CoreAudio.framework
    - sdk: AVFoundation.framework
    - sdk: AudioToolbox.framework
  WebrogueCommon:
    type: framework.static
    supportedDestinations: [macOS, iOS]
    sources:
    - Common/WebrogueCommon
    settings:
      base:
        INFOPLIST_FILE: Common/WebrogueCommon/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: io.github.webrogue-runtime.WebrogueCommon
        PRODUCT_NAME: WebrogueCommon
  Cargo iOS:
    platform: iOS
    legacy:
      toolPath: /bin/sh
      arguments: iOS/rust/scripts/cargo_lipo_builder.sh
      workingDirectory: $(SRCROOT)/
      passSettings: true
  Cargo macOS:
    platform: macOS
    legacy:
      toolPath: /bin/sh
      arguments: macOS/runtime/rust/scripts/cargo_lipo_builder.sh
      workingDirectory: $(SRCROOT)/
      passSettings: true
schemes:
  MacOS_Debug:
    build:
      targets:
        Launcher: Debug
    run:
      config: Debug
  MacOS_Release:
    build:
      targets:
        Launcher: Release
    run:
      config: Release
  MacOS_ReleaseLocal:
    build:
      targets:
        Launcher: ReleaseLocal
    run:
      config: ReleaseLocal
  iOS_Debug:
    build:
      targets:
        Launcher_iOS: Debug
    run:
      config: Debug
  iOS_Release:
    build:
      targets:
        Launcher_iOS: Release
    run:
      config: Release
  iOS_ReleaseLocal:
    build:
      targets:
        Launcher_iOS: ReleaseLocal
    run:
      config: ReleaseLocal
