[package]
name = "webrogue-backend-v8"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
webrogue-runtime = { workspace = true }
anyhow = { workspace = true }
webrogue-backend-v8-macro = { workspace = true }
v8 = { workspace = true }
