// wit/calculator.wit
package vscode:example;

interface types {
	record analyze-input {
		path: string,
	}
	record analyze-output {
		data: string,
		name: string,
		id: string,
		version: string,
		macos-icon-data-url: string
	}
	variant analyze-output-result {
		success(analyze-output),
		error(string),
	}
}
world wrapp-reader {
	use types.{ analyze-input, analyze-output-result };

	import log: func(msg: string);

	export analyze: func(i: analyze-input) -> analyze-output-result;
}
