// wit/calculator.wit
package vscode:example;

interface types {
	record analyze-input {
		path: string,
	}
	record analyze-output {
		name: string,
		id: string,
		version: string,
		windows-icon-data-url: string,
		android-light-icon-data-url: string,
		android-light-background-data-url: string,
		android-dark-icon-data-url: string,
		android-dark-background-data-url: string,
		vulkan-requirement: requirement,
	}
	variant analyze-output-result {
		success(analyze-output),
		error(string),
	}
	variant requirement {
		disabled,
		optional,
		required,
	}
}
world wrapp-reader {
	use types.{ analyze-input, analyze-output-result };

	import log: func(msg: string);

	export analyze: func(i: analyze-input) -> analyze-output-result;
}
