[package]
name = "webrogue_ios"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
name = "webrogue_ios"
crate-type = ["staticlib"]

[dependencies]
anyhow = { workspace = true }
webrogue_runtime = { workspace = true }
webrogue_backend_wasmtime = { workspace = true }
webrogue_wasi = { workspace = true }
webrogue_gl = { workspace = true }
webrogue_gfx = { workspace = true }
webrogue_wasi_sync = { workspace = true }
webrogue_std_stream_os = { workspace = true }
webrogue_gfx_ffi = { workspace = true }
