[target.x86_64-unknown-linux-gnu]
# Linking static LLVM libraries with ld is pain
rustflags = [
    "-C", "link-arg=-fuse-ld=lld",
]
[target.x86_64-pc-windows-msvc]
rustflags = [
    "-C", "target-feature=+crt-static",
]
