FROM rust:bookworm

RUN apt update
RUN apt-get -y install cmake llvm-19 strace clang-19 lld-19 libc++abi-19-dev libc++-19-dev
RUN update-alternatives --install /usr/bin/llvm-ar llvm-ar /usr/bin/llvm-ar-19 1
RUN update-alternatives --install /usr/bin/ld.lld ld.lld /usr/bin/ld.lld-19 1
RUN update-alternatives --install /usr/bin/clang clang /usr/bin/clang-19 1
RUN update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-19 1

RUN apt-get -y install build-essential git make \
    pkg-config cmake ninja-build gnome-desktop-testing libasound2-dev libpulse-dev \
    libaudio-dev libjack-dev libsndio-dev libx11-dev libxext-dev \
    libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxtst-dev \
    libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev \
    libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev \
    libpipewire-0.3-dev libwayland-dev libdecor-0-dev liburing-dev

ENV GCC_VERSION=12

# https://github.com/libsdl-org/SDL/blob/main/docs/README-linux.md#build-dependencies