[package]
name = "webrogue_android"
version = "0.1.0"
edition = "2021"


[lib]
name = "webrogue_android"
crate-type = ["staticlib"]

[dependencies]
anyhow = { version = "1" }
webrogue_runtime = { path = "../../../../../../crates/webrogue_runtime" }
webrogue_backend_wasmer = { path = "../../../../../../crates/webrogue_backend_wasmer", default-features = false, features = ["singlepass"] }
webrogue_wasi_sync = { path = "../../../../../../crates/webrogue_wasi_sync" }
webrogue_std_stream_sdl = { path = "../../../../../../crates/webrogue_std_stream_sdl", default-features = false }
