name: webrogue
configs:
  Debug: debug
  Release: release
  ReleaseLocal: release
settings:
  base:
    MACOSX_DEPLOYMENT_TARGET: 12.0
    IPHONEOS_DEPLOYMENT_TARGET: 14.0
    GENERATE_INFOPLIST_FILE: true
    MARKETING_VERSION: $(WEBROGUE_APPLICATION_VERSION)
    CURRENT_PROJECT_VERSION: 1
    DEAD_CODE_STRIPPING: true
    ENABLE_USER_SCRIPT_SANDBOXING: true
    ENABLE_MODULE_VERIFIER: true
    MODULE_VERIFIER_SUPPORTED_LANGUAGE_STANDARDS: "gnu11 gnu++14"
    ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: false
    CODE_SIGN_ALLOW_ENTITLEMENTS_MODIFICATION: true
  configs:
    Debug:
      CODE_SIGN_IDENTITY: "-"
      CARGO_CONFIG: Debug
      CODE_SIGN_STYLE: Manual
    Release:
      CODE_SIGN_IDENTITY: "Apple Development"
      CARGO_CONFIG: Release
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: LC5F8UX2W7
    ReleaseLocal:
      CODE_SIGN_IDENTITY: "-"
      CARGO_CONFIG: Release
      CODE_SIGN_STYLE: Manual
options:
  createIntermediateGroups: true
targets:
  MacOSRunner:
    type: application
    platform: macOS
    sources:
    - macos/main.m
    - macos/Assets.xcassets
    - aot/aot.wrapp
    - aot.xcconfig
    configFiles:
      Debug: aot.xcconfig
      Release: aot.xcconfig
      ReleaseLocal: aot.xcconfig
    settings:
      base:
        CODE_SIGN_ENTITLEMENTS: macos/runner.entitlements
        # INFOPLIST_FILE: macos/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: $(WEBROGUE_APPLICATION_ID)
        PRODUCT_NAME: $(WEBROGUE_APPLICATION_NAME)
        ENABLE_HARDENED_RUNTIME: true
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.utilities
        INFOPLIST_KEY_CFBundleDisplayName: $(WEBROGUE_APPLICATION_NAME)
        OTHER_LDFLAGS:
          - "-lwebrogue_macos"
          - "-lSDL2"
          - "-lGFXStream"
          - "${BUILT_PRODUCTS_DIR}/aot_lipo.o"
        LIBRARY_SEARCH_PATHS: "$(BUILT_PRODUCTS_DIR)"
    dependencies:
    - bundle: libEGL.dylib
      embed: true
      codeSign: true
    - bundle: libGLESv2.dylib
      embed: true
      codeSign: true
      dependencies:
    - sdk: Quartz.framework
    - sdk: Metal.framework
    - sdk: IOKit.framework
    - sdk: GameController.framework
    - sdk: ForceFeedback.framework
    - sdk: CoreVideo.framework
    - sdk: CoreHaptics.framework
    - sdk: CoreFoundation.framework
    - sdk: CoreAudio.framework
    - sdk: Cocoa.framework
    - sdk: Carbon.framework
    - sdk: AudioToolbox.framework
    - sdk: libc++.tbd
    - sdk: libc++abi.tbd
    preBuildScripts:
      - script: "cd \"${BUILT_PRODUCTS_DIR}\"; sh ${SRCROOT}/scripts/copy_bin.sh"
        name: Copy libraries
        inputFiles:
          - ${SRCROOT}/scripts/copy_bin.sh
          - ${SRCROOT}/bin/libEGL.macosx.dylib
          - ${SRCROOT}/bin/libGLESv2.macosx.dylib
          - ${SRCROOT}/bin/libwebrogue_macos.macosx.a
          - ${SRCROOT}/bin/libSDL2.macosx.a
          - ${SRCROOT}/bin/libGFXStream.macosx.a
        outputFiles:
          - ${BUILT_PRODUCTS_DIR}/libEGL.dylib
          - ${BUILT_PRODUCTS_DIR}/libGLESv2.dylib
          - ${BUILT_PRODUCTS_DIR}/libSDL2.a
          - ${BUILT_PRODUCTS_DIR}/libGFXStream.a
          - ${BUILT_PRODUCTS_DIR}/libwebrogue_macos.a
      - script: "sh ${SRCROOT}/scripts/lipo_object_combiner.sh ${SRCROOT}/aot ${BUILT_PRODUCTS_DIR}/aot_lipo.o"
        name: Combine object to lipo
        inputFiles:
          - ${SRCROOT}/aot/aot.x86_64.macosx.o
          - ${SRCROOT}/aot/aot.arm64.macosx.o
          - ${SRCROOT}/scripts/lipo_object_combiner.sh
        outputFiles:
          - ${BUILT_PRODUCTS_DIR}/aot_lipo.o
          - ${BUILT_PRODUCTS_DIR}/aot_lipo.o.lipo
  iOSRunner:
    type: application
    platform: iOS
    sources:
    - ios/Assets.xcassets
    - ios/Bridging-Header.h
    - ios/Info.plist
    - ios/LaunchScreen.storyboard
    - ios/main.swift
    - aot/aot.wrapp
    - aot.xcconfig
    configFiles:
      Debug: aot.xcconfig
      Release: aot.xcconfig
      ReleaseLocal: aot.xcconfig
    settings:
      base:
        INFOPLIST_FILE: ios/Info.plist
        CODE_SIGN_ENTITLEMENTS: ios/ios.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: $(WEBROGUE_APPLICATION_ID)
        PRODUCT_NAME: $(WEBROGUE_APPLICATION_NAME)
        OTHER_LDFLAGS:
        - "-lwebrogue_ios"
        - "-lwrios"
        - "-lGFXStream"
        - "-lSDL2"
        - "${BUILT_PRODUCTS_DIR}/aot_lipo.o"
        LIBRARY_SEARCH_PATHS: "$(BUILT_PRODUCTS_DIR)"
        SWIFT_OBJC_BRIDGING_HEADER: "$(SRCROOT)/ios/Bridging-Header.h"
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.utilities
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight UIInterfaceOrientationPortrait"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown"
        ENABLE_PREVIEWS: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UILaunchStoryboardName: LaunchScreen.storyboard
    dependencies:
    - sdk: UIKit.framework
    - sdk: QuartzCore.framework
    - sdk: Metal.framework
    - sdk: IOKit.framework
    - sdk: GameController.framework
    - sdk: CoreVideo.framework
    - sdk: CoreMotion.framework
    - sdk: CoreHaptics.framework
    - sdk: CoreGraphics.framework
    - sdk: CoreFoundation.framework
    - sdk: CoreBluetooth.framework
    - sdk: CoreAudio.framework
    - sdk: AVFoundation.framework
    - sdk: AudioToolbox.framework
    - framework: bin/libEGL.xcframework
    - framework: bin/libGLESv2.xcframework
    preBuildScripts:
      - script: "cd \"${BUILT_PRODUCTS_DIR}\"; sh ${SRCROOT}/scripts/copy_bin_ios.sh"
        name: Copy libraries
        inputFiles:
          - ${SRCROOT}/scripts/copy_bin_ios.sh
          - ${SRCROOT}/bin/libwebrogue_ios.iphonesimulator.a
          - ${SRCROOT}/bin/libwrios.iphonesimulator.a
          - ${SRCROOT}/bin/libSDL2.iphonesimulator.a
          - ${SRCROOT}/bin/libGFXStream.iphonesimulator.a
          - ${SRCROOT}/bin/libwebrogue_ios.iphoneos.a
          - ${SRCROOT}/bin/libwrios.iphoneos.a
          - ${SRCROOT}/bin/libSDL2.iphoneos.a
          - ${SRCROOT}/bin/libGFXStream.iphoneos.a
        outputFiles:
          - ${BUILT_PRODUCTS_DIR}/libwebrogue_ios.a
          - ${BUILT_PRODUCTS_DIR}/libwrios.a
          - ${BUILT_PRODUCTS_DIR}/libSDL2.a
          - ${BUILT_PRODUCTS_DIR}/libGFXStream.a
      - script: "sh ${SRCROOT}/scripts/lipo_object_combiner.sh ${SRCROOT}/aot ${BUILT_PRODUCTS_DIR}/aot_lipo.o"
        name: Combine object to lipo
        inputFiles:
          - ${SRCROOT}/aot/aot.x86_64.iphonesimulator.o
          - ${SRCROOT}/aot/aot.arm64.iphonesimulator.o
          - ${SRCROOT}/aot/aot.arm64.iphoneos.o 
          - ${SRCROOT}/scripts/lipo_object_combiner.sh
        outputFiles:
          - ${BUILT_PRODUCTS_DIR}/aot_lipo.o
          - ${BUILT_PRODUCTS_DIR}/aot_lipo.o.lipo
schemes:
  MacOS_Debug:
    build:
      targets:
        MacOSRunner: Debug
    run:
      config: Debug
  MacOS_Release:
    build:
      targets:
        MacOSRunner: Release
    run:
      config: Release
  MacOS_ReleaseLocal:
    build:
      targets:
        MacOSRunner: ReleaseLocal
    run:
      config: ReleaseLocal
  iOS_Debug:
    build:
      targets:
        iOSRunner: Debug
    run:
      config: Debug
  iOS_Release:
    build:
      targets:
        iOSRunner: Release
    run:
      config: Release
  iOS_ReleaseLocal:
    build:
      targets:
        iOSRunner: ReleaseLocal
    run:
      config: ReleaseLocal
