[package]
name = "webrogue_backend_wasmer_macro"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
webrogue_macro_common = { workspace = true }

[lib]
proc-macro = true
