[package]
name = "webrogue_backend_v8"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
webrogue_runtime = { workspace = true }
anyhow = { workspace = true }
webrogue_backend_v8_macro = { workspace = true }
v8 = { workspace = true }
