[package]
name = "webrogue_backend_v8"
version = "0.1.0"
edition = "2021"

[dependencies]
webrogue_runtime = { path = "../runtime"}
anyhow = { version = "1" }
webrogue_backend_v8_macro = { path = "macro" }
v8 = { version = "0.99" } # git = "https://github.com/denoland/rusty_v8.git"
