[package]
name = "webrogue_wrapp_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1" }
clap = { version = "4.0", features = ["derive"] }
webrogue_wrapp = { path = "../wrapp" }
