[package]
name = "webrogue_wrapp_cli"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
webrogue_wrapp = { workspace = true }
