[package]
name = "webrogue-android"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
name = "webrogue_android"
crate-type = ["staticlib"]

[dependencies]
anyhow = { workspace = true }
webrogue-runtime = { workspace = true, features = ["gl", "cranelift"] }
wasmer-wasix = { workspace = true }
tokio = { workspace = true }
