[package]
name = "webrogue_android"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
name = "webrogue_android"
crate-type = ["staticlib"]

[features]
default = ["backend_wasmtime"]
backend_v8 = ["dep:webrogue_backend_v8"]
backend_wasmtime = ["dep:webrogue_backend_wasmtime"]

[dependencies]
anyhow = { workspace = true }
webrogue_runtime = { workspace = true }
webrogue_backend_v8 = { workspace = true, optional = true }
webrogue_backend_wasmtime = { workspace = true, optional = true }
webrogue_wasi = { workspace = true }
webrogue_wasi_sync = { workspace = true }
webrogue_gl = { workspace = true }
webrogue_gfx = { workspace = true }
webrogue_std_stream_os = { workspace = true }
webrogue_gfx_ffi = { workspace = true }

[target.'cfg(unix)'.dependencies]
rustix = { workspace = true, features = ["fs", "event"] }

[target.'cfg(windows)'.dependencies]
rustix = { workspace = true, features = ["net"] }
io-extras = { workspace = true }
