[package]
name = "webrogue-web"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[lib]
crate-type = ["staticlib"]

[dependencies]
webrogue-gfx = { workspace = true }
wasi-common = { workspace = true, default-features = false, features = ["sync"] }
anyhow = { workspace = true }
# cap-std = "3.4.1"
webrogue-wrapp = { workspace = true }
webrogue-wasip1 = { workspace = true }
wiggle = { workspace = true, default-features = false, features = [] }
webrogue-web-macro = { workspace = true }
wasmparser = { workspace = true }

# just to silence compile_error using "fallback" feature
iana-time-zone = { version = ">=0.1.61", features = ["fallback"] }
