[package]
name = "webrogue-debugger"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
wasmtime-internal-debugger = { workspace = true }
webrogue-common = { workspace = true }
wasmtime = { workspace = true, default-features = false }
gdbstub = { workspace = true }
gdbstub_arch = { workspace = true }
wasmtime-wasi = { workspace = true, default-features = false, features = ["p2"] } # wasmtime-internal-debugger needs p2, but is too shy to ask
tokio = { workspace = true, features = ["macros", "net", "rt", "sync"] }
async-trait = { workspace = true }
