[package]
name = "webrogue_std_stream_os"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
webrogue_runtime = { workspace = true }
wiggle = { workspace = true, default-features = false }

[target.'cfg(unix)'.dependencies]
rustix = { workspace = true, features = ["fs", "event"] }

[target.'cfg(windows)'.dependencies]
rustix = { workspace = true, features = ["net"] }
io-extras = { workspace = true }
