use crate::WinitWindow;
use winit::event::WindowEvent;

pub fn encode_event(
    window: &WinitWindow,
    event: WindowEvent,
    events_buffer: &mut std::sync::MutexGuard<'_, Vec<u8>>,
) {
    use webrogue_gfx::events_encoder;

    match event {
        // WindowEvent::ActivationTokenDone { serial, token } => todo!(),
        WindowEvent::SurfaceResized(_physical_size) => {
            events_encoder::gl_resized(events_buffer);
            events_encoder::window_resized(events_buffer);
        }
        // WindowEvent::Moved(physical_position) => todo!(),
        WindowEvent::CloseRequested => events_encoder::quit(events_buffer),
        WindowEvent::Destroyed => events_encoder::quit(events_buffer),
        // WindowEvent::DragEntered { paths, position } => todo!(),
        // WindowEvent::DragMoved { position } => todo!(),
        // WindowEvent::DragDropped { paths, position } => todo!(),
        // WindowEvent::DragLeft { position } => todo!(),
        // WindowEvent::Focused(_) => todo!(),
        WindowEvent::KeyboardInput {
            device_id,
            event,
            is_synthetic,
        } => {
            if is_synthetic {
                return;
            }
            let mut named_key = match event.logical_key {
                winit::keyboard::Key::Named(named_key) => translate_named_key(named_key),
                _ => events_encoder::NamedKey::Unknown,
            };
            let mut physical_key = translate_physical_key(event.physical_key);
            let mut encode_buffer = [0u8; 4];
            let mut text_buffer = [0u8; 32];
            let mut text_buffer_size = 0;
            macro_rules! flush {
                () => {
                    events_encoder::key(
                        events_buffer,
                        event.state.is_pressed(),
                        named_key,
                        physical_key,
                        text_buffer_size as u8,
                        &text_buffer,
                    );
                };
            }
            if let Some(text) = event.text {
                let max_buffer_size = 31; // must be null-terminated
                for char in text.chars() {
                    let new_len = text_buffer_size + char.len_utf8();
                    if new_len > max_buffer_size {
                        flush!();
                        named_key = events_encoder::NamedKey::Unknown;
                        physical_key = events_encoder::PhysicalKey::Unknown;
                        text_buffer.fill(0);
                        text_buffer_size = 0;
                    }
                    let new_bytes = char.encode_utf8(&mut encode_buffer).as_bytes();
                    text_buffer[text_buffer_size..(text_buffer_size + new_bytes.len())]
                        .copy_from_slice(new_bytes);
                    text_buffer_size += new_bytes.len();
                }
            }
            if text_buffer_size != 0
                || named_key != events_encoder::NamedKey::Unknown
                || physical_key != events_encoder::PhysicalKey::Unknown
            {
                flush!();
            }
        }
        // WindowEvent::ModifiersChanged(modifiers) => todo!(),
        // WindowEvent::Ime(ime) => todo!(),
        WindowEvent::PointerMoved {
            device_id: _,
            position,
            primary: _,
            source: _,
        } => {
            let logical_position = position.to_logical(window.internal.window.scale_factor());
            events_encoder::mouse_motion(events_buffer, logical_position.x, logical_position.y);
        }
        // WindowEvent::PointerEntered { device_id, position, primary, kind } => todo!(),
        // WindowEvent::PointerLeft { device_id, position, primary, kind } => todo!(),
        // WindowEvent::MouseWheel { device_id, delta, phase } => todo!(),
        WindowEvent::PointerButton {
            device_id: _,
            state,
            position,
            primary: _,
            button,
        } => {
            let button = match button {
                winit::event::ButtonSource::Mouse(mouse_button) => match mouse_button {
                    winit::event::MouseButton::Left => events_encoder::MouseButton::Left,
                    winit::event::MouseButton::Right => events_encoder::MouseButton::Right,
                    winit::event::MouseButton::Middle => events_encoder::MouseButton::Left,
                    winit::event::MouseButton::Back => events_encoder::MouseButton::Left,
                    _ => events_encoder::MouseButton::Left,
                },
                winit::event::ButtonSource::Touch {
                    finger_id: _,
                    force: _,
                } => events_encoder::MouseButton::Left,
                winit::event::ButtonSource::TabletTool {
                    kind: _,
                    button: _,
                    data: _,
                } => events_encoder::MouseButton::Left,
                winit::event::ButtonSource::Unknown(_) => events_encoder::MouseButton::Unknown,
            };
            let logical_position = position.to_logical(window.internal.window.scale_factor());
            events_encoder::mouse_button(
                events_buffer,
                button,
                state.is_pressed(),
                logical_position.x,
                logical_position.y,
                false,
            );
        }
        // WindowEvent::PinchGesture { device_id, delta, phase } => todo!(),
        // WindowEvent::PanGesture { device_id, delta, phase } => todo!(),
        // WindowEvent::DoubleTapGesture { device_id } => todo!(),
        // WindowEvent::RotationGesture { device_id, delta, phase } => todo!(),
        // WindowEvent::TouchpadPressure { device_id, pressure, stage } => todo!(),
        WindowEvent::ScaleFactorChanged {
            scale_factor: _,
            surface_size_writer: _,
        } => {
            events_encoder::gl_resized(events_buffer);
            events_encoder::window_resized(events_buffer);
        }
        // WindowEvent::ThemeChanged(theme) => todo!(),
        // WindowEvent::Occluded(_) => todo!(),
        // WindowEvent::RedrawRequested => todo!(),
        _ => {}
    };
}

fn translate_named_key(
    named_key: winit::keyboard::NamedKey,
) -> webrogue_gfx::events_encoder::NamedKey {
    use webrogue_gfx::events_encoder::NamedKey::*;
    use winit::keyboard::NamedKey as WinitKey;

    match named_key {
        WinitKey::Unidentified => Unknown,
        WinitKey::Alt => Alt,
        WinitKey::AltGraph => AltGraph,
        WinitKey::CapsLock => CapsLock,
        WinitKey::Control => Control,
        WinitKey::Fn => Fn,
        WinitKey::FnLock => FnLock,
        WinitKey::Meta => Meta,
        WinitKey::NumLock => NumLock,
        WinitKey::ScrollLock => ScrollLock,
        WinitKey::Shift => Shift,
        WinitKey::Symbol => Symbol,
        WinitKey::SymbolLock => SymbolLock,
        WinitKey::Hyper => Hyper,
        WinitKey::Super => Super,
        WinitKey::Enter => Enter,
        WinitKey::Tab => Tab,
        WinitKey::ArrowDown => ArrowDown,
        WinitKey::ArrowLeft => ArrowLeft,
        WinitKey::ArrowRight => ArrowRight,
        WinitKey::ArrowUp => ArrowUp,
        WinitKey::End => End,
        WinitKey::Home => Home,
        WinitKey::PageDown => PageDown,
        WinitKey::PageUp => PageUp,
        WinitKey::Backspace => Backspace,
        WinitKey::Clear => Clear,
        WinitKey::Copy => Copy,
        WinitKey::CrSel => CrSel,
        WinitKey::Cut => Cut,
        WinitKey::Delete => Delete,
        WinitKey::EraseEof => EraseEof,
        WinitKey::ExSel => ExSel,
        WinitKey::Insert => Insert,
        WinitKey::Paste => Paste,
        WinitKey::Redo => Redo,
        WinitKey::Undo => Undo,
        WinitKey::Accept => Accept,
        WinitKey::Again => Again,
        WinitKey::Attn => Attn,
        WinitKey::Cancel => Cancel,
        WinitKey::ContextMenu => ContextMenu,
        WinitKey::Escape => Escape,
        WinitKey::Execute => Execute,
        WinitKey::Find => Find,
        WinitKey::Help => Help,
        WinitKey::Pause => Pause,
        WinitKey::Play => Play,
        WinitKey::Props => Props,
        WinitKey::Select => Select,
        WinitKey::ZoomIn => ZoomIn,
        WinitKey::ZoomOut => ZoomOut,
        WinitKey::BrightnessDown => BrightnessDown,
        WinitKey::BrightnessUp => BrightnessUp,
        WinitKey::Eject => Eject,
        WinitKey::LogOff => LogOff,
        WinitKey::Power => Power,
        WinitKey::PowerOff => PowerOff,
        WinitKey::PrintScreen => PrintScreen,
        WinitKey::Hibernate => Hibernate,
        WinitKey::Standby => Standby,
        WinitKey::WakeUp => WakeUp,
        WinitKey::AllCandidates => AllCandidates,
        WinitKey::Alphanumeric => Alphanumeric,
        WinitKey::CodeInput => CodeInput,
        WinitKey::Compose => Compose,
        WinitKey::Convert => Convert,
        WinitKey::Dead => Dead,
        WinitKey::FinalMode => FinalMode,
        WinitKey::GroupFirst => GroupFirst,
        WinitKey::GroupLast => GroupLast,
        WinitKey::GroupNext => GroupNext,
        WinitKey::GroupPrevious => GroupPrevious,
        WinitKey::ModeChange => ModeChange,
        WinitKey::NextCandidate => NextCandidate,
        WinitKey::NonConvert => NonConvert,
        WinitKey::PreviousCandidate => PreviousCandidate,
        WinitKey::Process => Process,
        WinitKey::SingleCandidate => SingleCandidate,
        WinitKey::HangulMode => HangulMode,
        WinitKey::HanjaMode => HanjaMode,
        WinitKey::JunjaMode => JunjaMode,
        WinitKey::Eisu => Eisu,
        WinitKey::Hankaku => Hankaku,
        WinitKey::Hiragana => Hiragana,
        WinitKey::HiraganaKatakana => HiraganaKatakana,
        WinitKey::KanaMode => KanaMode,
        WinitKey::KanjiMode => KanjiMode,
        WinitKey::Katakana => Katakana,
        WinitKey::Romaji => Romaji,
        WinitKey::Zenkaku => Zenkaku,
        WinitKey::ZenkakuHankaku => ZenkakuHankaku,
        WinitKey::Soft1 => Soft1,
        WinitKey::Soft2 => Soft2,
        WinitKey::Soft3 => Soft3,
        WinitKey::Soft4 => Soft4,
        WinitKey::ChannelDown => ChannelDown,
        WinitKey::ChannelUp => ChannelUp,
        WinitKey::Close => Close,
        WinitKey::MailForward => MailForward,
        WinitKey::MailReply => MailReply,
        WinitKey::MailSend => MailSend,
        WinitKey::MediaClose => MediaClose,
        WinitKey::MediaFastForward => MediaFastForward,
        WinitKey::MediaPause => MediaPause,
        WinitKey::MediaPlay => MediaPlay,
        WinitKey::MediaPlayPause => MediaPlayPause,
        WinitKey::MediaRecord => MediaRecord,
        WinitKey::MediaRewind => MediaRewind,
        WinitKey::MediaStop => MediaStop,
        WinitKey::MediaTrackNext => MediaTrackNext,
        WinitKey::MediaTrackPrevious => MediaTrackPrevious,
        WinitKey::New => New,
        WinitKey::Open => Open,
        WinitKey::Print => Print,
        WinitKey::Save => Save,
        WinitKey::SpellCheck => SpellCheck,
        WinitKey::Key11 => Key11,
        WinitKey::Key12 => Key12,
        WinitKey::AudioBalanceLeft => AudioBalanceLeft,
        WinitKey::AudioBalanceRight => AudioBalanceRight,
        WinitKey::AudioBassBoostDown => AudioBassBoostDown,
        WinitKey::AudioBassBoostToggle => AudioBassBoostToggle,
        WinitKey::AudioBassBoostUp => AudioBassBoostUp,
        WinitKey::AudioFaderFront => AudioFaderFront,
        WinitKey::AudioFaderRear => AudioFaderRear,
        WinitKey::AudioSurroundModeNext => AudioSurroundModeNext,
        WinitKey::AudioTrebleDown => AudioTrebleDown,
        WinitKey::AudioTrebleUp => AudioTrebleUp,
        WinitKey::AudioVolumeDown => AudioVolumeDown,
        WinitKey::AudioVolumeUp => AudioVolumeUp,
        WinitKey::AudioVolumeMute => AudioVolumeMute,
        WinitKey::MicrophoneToggle => MicrophoneToggle,
        WinitKey::MicrophoneVolumeDown => MicrophoneVolumeDown,
        WinitKey::MicrophoneVolumeUp => MicrophoneVolumeUp,
        WinitKey::MicrophoneVolumeMute => MicrophoneVolumeMute,
        WinitKey::SpeechCorrectionList => SpeechCorrectionList,
        WinitKey::SpeechInputToggle => SpeechInputToggle,
        WinitKey::LaunchApplication1 => LaunchApplication1,
        WinitKey::LaunchApplication2 => LaunchApplication2,
        WinitKey::LaunchCalendar => LaunchCalendar,
        WinitKey::LaunchContacts => LaunchContacts,
        WinitKey::LaunchMail => LaunchMail,
        WinitKey::LaunchMediaPlayer => LaunchMediaPlayer,
        WinitKey::LaunchMusicPlayer => LaunchMusicPlayer,
        WinitKey::LaunchPhone => LaunchPhone,
        WinitKey::LaunchScreenSaver => LaunchScreenSaver,
        WinitKey::LaunchSpreadsheet => LaunchSpreadsheet,
        WinitKey::LaunchWebBrowser => LaunchWebBrowser,
        WinitKey::LaunchWebCam => LaunchWebCam,
        WinitKey::LaunchWordProcessor => LaunchWordProcessor,
        WinitKey::BrowserBack => BrowserBack,
        WinitKey::BrowserFavorites => BrowserFavorites,
        WinitKey::BrowserForward => BrowserForward,
        WinitKey::BrowserHome => BrowserHome,
        WinitKey::BrowserRefresh => BrowserRefresh,
        WinitKey::BrowserSearch => BrowserSearch,
        WinitKey::BrowserStop => BrowserStop,
        WinitKey::AppSwitch => AppSwitch,
        WinitKey::Call => Call,
        WinitKey::Camera => Camera,
        WinitKey::CameraFocus => CameraFocus,
        WinitKey::EndCall => EndCall,
        WinitKey::GoBack => GoBack,
        WinitKey::GoHome => GoHome,
        WinitKey::HeadsetHook => HeadsetHook,
        WinitKey::LastNumberRedial => LastNumberRedial,
        WinitKey::Notification => Notification,
        WinitKey::MannerMode => MannerMode,
        WinitKey::VoiceDial => VoiceDial,
        WinitKey::TV => Tv,
        WinitKey::TV3DMode => Tv3dMode,
        WinitKey::TVAntennaCable => TvAntennaCable,
        WinitKey::TVAudioDescription => TvAudioDescription,
        WinitKey::TVAudioDescriptionMixDown => TvAudioDescriptionMixDown,
        WinitKey::TVAudioDescriptionMixUp => TvAudioDescriptionMixUp,
        WinitKey::TVContentsMenu => TvContentsMenu,
        WinitKey::TVDataService => TvDataService,
        WinitKey::TVInput => TvInput,
        WinitKey::TVInputComponent1 => TvInputComponent1,
        WinitKey::TVInputComponent2 => TvInputComponent2,
        WinitKey::TVInputComposite1 => TvInputComposite1,
        WinitKey::TVInputComposite2 => TvInputComposite2,
        WinitKey::TVInputHDMI1 => TvInputHdmi1,
        WinitKey::TVInputHDMI2 => TvInputHdmi2,
        WinitKey::TVInputHDMI3 => TvInputHdmi3,
        WinitKey::TVInputHDMI4 => TvInputHdmi4,
        WinitKey::TVInputVGA1 => TvInputVga1,
        WinitKey::TVMediaContext => TvMediaContext,
        WinitKey::TVNetwork => TvNetwork,
        WinitKey::TVNumberEntry => TvNumberEntry,
        WinitKey::TVPower => TvPower,
        WinitKey::TVRadioService => TvRadioService,
        WinitKey::TVSatellite => TvSatellite,
        WinitKey::TVSatelliteBS => TvSatelliteBs,
        WinitKey::TVSatelliteCS => TvSatelliteCs,
        WinitKey::TVSatelliteToggle => TvSatelliteToggle,
        WinitKey::TVTerrestrialAnalog => TvTerrestrialAnalog,
        WinitKey::TVTerrestrialDigital => TvTerrestrialDigital,
        WinitKey::TVTimer => TvTimer,
        WinitKey::AVRInput => AvrInput,
        WinitKey::AVRPower => AvrPower,
        WinitKey::ColorF0Red => ColorF0red,
        WinitKey::ColorF1Green => ColorF1green,
        WinitKey::ColorF2Yellow => ColorF2yellow,
        WinitKey::ColorF3Blue => ColorF3blue,
        WinitKey::ColorF4Grey => ColorF4grey,
        WinitKey::ColorF5Brown => ColorF5brown,
        WinitKey::ClosedCaptionToggle => ClosedCaptionToggle,
        WinitKey::Dimmer => Dimmer,
        WinitKey::DisplaySwap => DisplaySwap,
        WinitKey::DVR => Dvr,
        WinitKey::Exit => Exit,
        WinitKey::FavoriteClear0 => FavoriteClear0,
        WinitKey::FavoriteClear1 => FavoriteClear1,
        WinitKey::FavoriteClear2 => FavoriteClear2,
        WinitKey::FavoriteClear3 => FavoriteClear3,
        WinitKey::FavoriteRecall0 => FavoriteRecall0,
        WinitKey::FavoriteRecall1 => FavoriteRecall1,
        WinitKey::FavoriteRecall2 => FavoriteRecall2,
        WinitKey::FavoriteRecall3 => FavoriteRecall3,
        WinitKey::FavoriteStore0 => FavoriteStore0,
        WinitKey::FavoriteStore1 => FavoriteStore1,
        WinitKey::FavoriteStore2 => FavoriteStore2,
        WinitKey::FavoriteStore3 => FavoriteStore3,
        WinitKey::Guide => Guide,
        WinitKey::GuideNextDay => GuideNextDay,
        WinitKey::GuidePreviousDay => GuidePreviousDay,
        WinitKey::Info => Info,
        WinitKey::InstantReplay => InstantReplay,
        WinitKey::Link => Link,
        WinitKey::ListProgram => ListProgram,
        WinitKey::LiveContent => LiveContent,
        WinitKey::Lock => Lock,
        WinitKey::MediaApps => MediaApps,
        WinitKey::MediaAudioTrack => MediaAudioTrack,
        WinitKey::MediaLast => MediaLast,
        WinitKey::MediaSkipBackward => MediaSkipBackward,
        WinitKey::MediaSkipForward => MediaSkipForward,
        WinitKey::MediaStepBackward => MediaStepBackward,
        WinitKey::MediaStepForward => MediaStepForward,
        WinitKey::MediaTopMenu => MediaTopMenu,
        WinitKey::NavigateIn => NavigateIn,
        WinitKey::NavigateNext => NavigateNext,
        WinitKey::NavigateOut => NavigateOut,
        WinitKey::NavigatePrevious => NavigatePrevious,
        WinitKey::NextFavoriteChannel => NextFavoriteChannel,
        WinitKey::NextUserProfile => NextUserProfile,
        WinitKey::OnDemand => OnDemand,
        WinitKey::Pairing => Pairing,
        WinitKey::PinPDown => PinPDown,
        WinitKey::PinPMove => PinPMove,
        WinitKey::PinPToggle => PinPToggle,
        WinitKey::PinPUp => PinPUp,
        WinitKey::PlaySpeedDown => PlaySpeedDown,
        WinitKey::PlaySpeedReset => PlaySpeedReset,
        WinitKey::PlaySpeedUp => PlaySpeedUp,
        WinitKey::RandomToggle => RandomToggle,
        WinitKey::RcLowBattery => RcLowBattery,
        WinitKey::RecordSpeedNext => RecordSpeedNext,
        WinitKey::RfBypass => RfBypass,
        WinitKey::ScanChannelsToggle => ScanChannelsToggle,
        WinitKey::ScreenModeNext => ScreenModeNext,
        WinitKey::Settings => Settings,
        WinitKey::SplitScreenToggle => SplitScreenToggle,
        WinitKey::STBInput => StbInput,
        WinitKey::STBPower => StbPower,
        WinitKey::Subtitle => Subtitle,
        WinitKey::Teletext => Teletext,
        WinitKey::VideoModeNext => VideoModeNext,
        WinitKey::Wink => Wink,
        WinitKey::ZoomToggle => ZoomToggle,
        WinitKey::F1 => F1,
        WinitKey::F2 => F2,
        WinitKey::F3 => F3,
        WinitKey::F4 => F4,
        WinitKey::F5 => F5,
        WinitKey::F6 => F6,
        WinitKey::F7 => F7,
        WinitKey::F8 => F8,
        WinitKey::F9 => F9,
        WinitKey::F10 => F10,
        WinitKey::F11 => F11,
        WinitKey::F12 => F12,
        WinitKey::F13 => F13,
        WinitKey::F14 => F14,
        WinitKey::F15 => F15,
        WinitKey::F16 => F16,
        WinitKey::F17 => F17,
        WinitKey::F18 => F18,
        WinitKey::F19 => F19,
        WinitKey::F20 => F20,
        WinitKey::F21 => F21,
        WinitKey::F22 => F22,
        WinitKey::F23 => F23,
        WinitKey::F24 => F24,
        WinitKey::F25 => F25,
        WinitKey::F26 => F26,
        WinitKey::F27 => F27,
        WinitKey::F28 => F28,
        WinitKey::F29 => F29,
        WinitKey::F30 => F30,
        WinitKey::F31 => F31,
        WinitKey::F32 => F32,
        WinitKey::F33 => F33,
        WinitKey::F34 => F34,
        WinitKey::F35 => F35,
        _ => Unknown,
    }
}

fn translate_physical_key(
    physical_key: winit::keyboard::PhysicalKey,
) -> webrogue_gfx::events_encoder::PhysicalKey {
    use webrogue_gfx::events_encoder::PhysicalKey::*;
    use winit::keyboard::KeyCode;

    match physical_key {
        winit::keyboard::PhysicalKey::Code(code) => match code {
            KeyCode::Backquote => Backquote,
            KeyCode::Backslash => Backslash,
            KeyCode::BracketLeft => BracketLeft,
            KeyCode::BracketRight => BracketRight,
            KeyCode::Comma => Comma,
            KeyCode::Digit0 => Digit0,
            KeyCode::Digit1 => Digit1,
            KeyCode::Digit2 => Digit2,
            KeyCode::Digit3 => Digit3,
            KeyCode::Digit4 => Digit4,
            KeyCode::Digit5 => Digit5,
            KeyCode::Digit6 => Digit6,
            KeyCode::Digit7 => Digit7,
            KeyCode::Digit8 => Digit8,
            KeyCode::Digit9 => Digit9,
            KeyCode::Equal => Equal,
            KeyCode::IntlBackslash => IntlBackslash,
            KeyCode::IntlRo => IntlRo,
            KeyCode::IntlYen => IntlYen,
            KeyCode::KeyA => KeyA,
            KeyCode::KeyB => KeyB,
            KeyCode::KeyC => KeyC,
            KeyCode::KeyD => KeyD,
            KeyCode::KeyE => KeyE,
            KeyCode::KeyF => KeyF,
            KeyCode::KeyG => KeyG,
            KeyCode::KeyH => KeyH,
            KeyCode::KeyI => KeyI,
            KeyCode::KeyJ => KeyJ,
            KeyCode::KeyK => KeyK,
            KeyCode::KeyL => KeyL,
            KeyCode::KeyM => KeyM,
            KeyCode::KeyN => KeyN,
            KeyCode::KeyO => KeyO,
            KeyCode::KeyP => KeyP,
            KeyCode::KeyQ => KeyQ,
            KeyCode::KeyR => KeyR,
            KeyCode::KeyS => KeyS,
            KeyCode::KeyT => KeyT,
            KeyCode::KeyU => KeyU,
            KeyCode::KeyV => KeyV,
            KeyCode::KeyW => KeyW,
            KeyCode::KeyX => KeyX,
            KeyCode::KeyY => KeyY,
            KeyCode::KeyZ => KeyZ,
            KeyCode::Minus => Minus,
            KeyCode::Period => Period,
            KeyCode::Quote => Quote,
            KeyCode::Semicolon => Semicolon,
            KeyCode::Slash => Slash,
            KeyCode::AltLeft => AltLeft,
            KeyCode::AltRight => AltRight,
            KeyCode::Backspace => Backspace,
            KeyCode::CapsLock => CapsLock,
            KeyCode::ContextMenu => ContextMenu,
            KeyCode::ControlLeft => ControlLeft,
            KeyCode::ControlRight => ControlRight,
            KeyCode::Enter => Enter,
            KeyCode::MetaLeft => MetaLeft,
            KeyCode::MetaRight => MetaRight,
            KeyCode::ShiftLeft => ShiftLeft,
            KeyCode::ShiftRight => ShiftRight,
            KeyCode::Space => Space,
            KeyCode::Tab => Tab,
            KeyCode::Convert => Convert,
            KeyCode::KanaMode => KanaMode,
            KeyCode::Lang1 => Lang1,
            KeyCode::Lang2 => Lang2,
            KeyCode::Lang3 => Lang3,
            KeyCode::Lang4 => Lang4,
            KeyCode::Lang5 => Lang5,
            KeyCode::NonConvert => NonConvert,
            KeyCode::Delete => Delete,
            KeyCode::End => End,
            KeyCode::Help => Help,
            KeyCode::Home => Home,
            KeyCode::Insert => Insert,
            KeyCode::PageDown => PageDown,
            KeyCode::PageUp => PageUp,
            KeyCode::ArrowDown => ArrowDown,
            KeyCode::ArrowLeft => ArrowLeft,
            KeyCode::ArrowRight => ArrowRight,
            KeyCode::ArrowUp => ArrowUp,
            KeyCode::NumLock => NumLock,
            KeyCode::Numpad0 => Numpad0,
            KeyCode::Numpad1 => Numpad1,
            KeyCode::Numpad2 => Numpad2,
            KeyCode::Numpad3 => Numpad3,
            KeyCode::Numpad4 => Numpad4,
            KeyCode::Numpad5 => Numpad5,
            KeyCode::Numpad6 => Numpad6,
            KeyCode::Numpad7 => Numpad7,
            KeyCode::Numpad8 => Numpad8,
            KeyCode::Numpad9 => Numpad9,
            KeyCode::NumpadAdd => NumpadAdd,
            KeyCode::NumpadBackspace => NumpadBackspace,
            KeyCode::NumpadClear => NumpadClear,
            KeyCode::NumpadClearEntry => NumpadClearEntry,
            KeyCode::NumpadComma => NumpadComma,
            KeyCode::NumpadDecimal => NumpadDecimal,
            KeyCode::NumpadDivide => NumpadDivide,
            KeyCode::NumpadEnter => NumpadEnter,
            KeyCode::NumpadEqual => NumpadEqual,
            KeyCode::NumpadHash => NumpadHash,
            KeyCode::NumpadMemoryAdd => NumpadMemoryAdd,
            KeyCode::NumpadMemoryClear => NumpadMemoryClear,
            KeyCode::NumpadMemoryRecall => NumpadMemoryRecall,
            KeyCode::NumpadMemoryStore => NumpadMemoryStore,
            KeyCode::NumpadMemorySubtract => NumpadMemorySubtract,
            KeyCode::NumpadMultiply => NumpadMultiply,
            KeyCode::NumpadParenLeft => NumpadParenLeft,
            KeyCode::NumpadParenRight => NumpadParenRight,
            KeyCode::NumpadStar => NumpadStar,
            KeyCode::NumpadSubtract => NumpadSubtract,
            KeyCode::Escape => Escape,
            KeyCode::Fn => Fn,
            KeyCode::FnLock => FnLock,
            KeyCode::PrintScreen => PrintScreen,
            KeyCode::ScrollLock => ScrollLock,
            KeyCode::Pause => Pause,
            KeyCode::BrowserBack => BrowserBack,
            KeyCode::BrowserFavorites => BrowserFavorites,
            KeyCode::BrowserForward => BrowserForward,
            KeyCode::BrowserHome => BrowserHome,
            KeyCode::BrowserRefresh => BrowserRefresh,
            KeyCode::BrowserSearch => BrowserSearch,
            KeyCode::BrowserStop => BrowserStop,
            KeyCode::Eject => Eject,
            KeyCode::LaunchApp1 => LaunchApp1,
            KeyCode::LaunchApp2 => LaunchApp2,
            KeyCode::LaunchMail => LaunchMail,
            KeyCode::MediaPlayPause => MediaPlayPause,
            KeyCode::MediaSelect => MediaSelect,
            KeyCode::MediaStop => MediaStop,
            KeyCode::MediaTrackNext => MediaTrackNext,
            KeyCode::MediaTrackPrevious => MediaTrackPrevious,
            KeyCode::Power => Power,
            KeyCode::Sleep => Sleep,
            KeyCode::AudioVolumeDown => AudioVolumeDown,
            KeyCode::AudioVolumeMute => AudioVolumeMute,
            KeyCode::AudioVolumeUp => AudioVolumeUp,
            KeyCode::WakeUp => WakeUp,
            KeyCode::Hyper => Hyper,
            KeyCode::Super => Super,
            KeyCode::Turbo => Turbo,
            KeyCode::Abort => Abort,
            KeyCode::Resume => Resume,
            KeyCode::Suspend => Suspend,
            KeyCode::Again => Again,
            KeyCode::Copy => Copy,
            KeyCode::Cut => Cut,
            KeyCode::Find => Find,
            KeyCode::Open => Open,
            KeyCode::Paste => Paste,
            KeyCode::Props => Props,
            KeyCode::Select => Select,
            KeyCode::Undo => Undo,
            KeyCode::Hiragana => Hiragana,
            KeyCode::Katakana => Katakana,
            KeyCode::Unidentified => Unidentified,
            KeyCode::F1 => F1,
            KeyCode::F2 => F2,
            KeyCode::F3 => F3,
            KeyCode::F4 => F4,
            KeyCode::F5 => F5,
            KeyCode::F6 => F6,
            KeyCode::F7 => F7,
            KeyCode::F8 => F8,
            KeyCode::F9 => F9,
            KeyCode::F10 => F10,
            KeyCode::F11 => F11,
            KeyCode::F12 => F12,
            KeyCode::F13 => F13,
            KeyCode::F14 => F14,
            KeyCode::F15 => F15,
            KeyCode::F16 => F16,
            KeyCode::F17 => F17,
            KeyCode::F18 => F18,
            KeyCode::F19 => F19,
            KeyCode::F20 => F20,
            KeyCode::F21 => F21,
            KeyCode::F22 => F22,
            KeyCode::F23 => F23,
            KeyCode::F24 => F24,
            KeyCode::F25 => F25,
            KeyCode::F26 => F26,
            KeyCode::F27 => F27,
            KeyCode::F28 => F28,
            KeyCode::F29 => F29,
            KeyCode::F30 => F30,
            KeyCode::F31 => F31,
            KeyCode::F32 => F32,
            KeyCode::F33 => F33,
            KeyCode::F34 => F34,
            KeyCode::F35 => F35,
            KeyCode::BrightnessDown => BrightnessDown,
            KeyCode::BrightnessUp => BrightnessUp,
            KeyCode::DisplayToggleIntExt => DisplayToggleIntExt,
            KeyCode::KeyboardLayoutSelect => KeyboardLayoutSelect,
            KeyCode::LaunchAssistant => LaunchAssistant,
            KeyCode::LaunchControlPanel => LaunchControlPanel,
            KeyCode::LaunchScreenSaver => LaunchScreenSaver,
            KeyCode::MailForward => MailForward,
            KeyCode::MailReply => MailReply,
            KeyCode::MailSend => MailSend,
            KeyCode::MediaFastForward => MediaFastForward,
            KeyCode::MediaPause => MediaPause,
            KeyCode::MediaPlay => MediaPlay,
            KeyCode::MediaRecord => MediaRecord,
            KeyCode::MediaRewind => MediaRewind,
            KeyCode::MicrophoneMuteToggle => MicrophoneMuteToggle,
            KeyCode::PrivacyScreenToggle => PrivacyScreenToggle,
            KeyCode::KeyboardBacklightToggle => KeyboardBacklightToggle,
            KeyCode::SelectTask => SelectTask,
            KeyCode::ShowAllWindows => ShowAllWindows,
            KeyCode::ZoomToggle => ZoomToggle,
            _ => Unknown,
        },
        winit::keyboard::PhysicalKey::Unidentified(_) => Unknown,
    }
}
