/*
 * Hub API
 *
 * API for Hub authentication and user management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthLoginRequest {
    #[serde(rename = "username_or_email")]
    pub username_or_email: String,
    #[serde(rename = "password")]
    pub password: String,
}

impl AuthLoginRequest {
    pub fn new(username_or_email: String, password: String) -> AuthLoginRequest {
        AuthLoginRequest {
            username_or_email,
            password,
        }
    }
}

