/*
 * Hub API
 *
 * API for Hub authentication and user management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthLoginResponse {
    #[serde(rename = "token")]
    pub token: String,
    #[serde(rename = "needs_email_verification")]
    pub needs_email_verification: bool,
}

impl AuthLoginResponse {
    pub fn new(token: String, needs_email_verification: bool) -> AuthLoginResponse {
        AuthLoginResponse {
            token,
            needs_email_verification,
        }
    }
}

