/*
 * Hub API
 *
 * API for Hub authentication and user management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CheckEmail500Response {
    #[serde(rename = "error")]
    pub error: serde_json::Value,
}

impl CheckEmail500Response {
    pub fn new(error: serde_json::Value) -> CheckEmail500Response {
        CheckEmail500Response {
            error,
        }
    }
}

