/*
 * Hub API
 *
 * API for Hub authentication and user management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CheckEmailRequest {
    #[serde(rename = "email")]
    pub email: String,
}

impl CheckEmailRequest {
    pub fn new(email: String) -> CheckEmailRequest {
        CheckEmailRequest {
            email,
        }
    }
}

