/*
 * Hub API
 *
 * API for Hub authentication and user management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CheckEmailResponse {
    #[serde(rename = "is_taken")]
    pub is_taken: bool,
}

impl CheckEmailResponse {
    pub fn new(is_taken: bool) -> CheckEmailResponse {
        CheckEmailResponse {
            is_taken,
        }
    }
}

