/*
 * Hub API
 *
 * API for Hub authentication and user management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConnectDeviceWsEvent {
    #[serde(rename = "sdp_offer", skip_serializing_if = "Option::is_none")]
    pub sdp_offer: Option<String>,
}

impl ConnectDeviceWsEvent {
    pub fn new() -> ConnectDeviceWsEvent {
        ConnectDeviceWsEvent {
            sdp_offer: None,
        }
    }
}

