/*
 * Hub API
 *
 * API for Hub authentication and user management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConnectDeviceWsCommand {
    #[serde(rename = "uuid")]
    pub uuid: uuid::Uuid,
    #[serde(rename = "sdp_answer", skip_serializing_if = "Option::is_none")]
    pub sdp_answer: Option<String>,
}

impl ConnectDeviceWsCommand {
    pub fn new(uuid: uuid::Uuid) -> ConnectDeviceWsCommand {
        ConnectDeviceWsCommand {
            uuid,
            sdp_answer: None,
        }
    }
}

