/*
 * Hub API
 *
 * API for Hub authentication and user management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConnectDeviceWsCommand {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "sdp_answer", skip_serializing_if = "Option::is_none")]
    pub sdp_answer: Option<String>,
}

impl ConnectDeviceWsCommand {
    pub fn new() -> ConnectDeviceWsCommand {
        ConnectDeviceWsCommand {
            name: None,
            sdp_answer: None,
        }
    }
}

