/*
 * Hub API
 *
 * API for Hub authentication and user management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DebugOutgoingWsMessage {
    #[serde(rename = "uuid")]
    pub uuid: uuid::Uuid,
    #[serde(rename = "sdp_offer")]
    pub sdp_offer: String,
}

impl DebugOutgoingWsMessage {
    pub fn new(uuid: uuid::Uuid, sdp_offer: String) -> DebugOutgoingWsMessage {
        DebugOutgoingWsMessage {
            uuid,
            sdp_offer,
        }
    }
}

