/*
 * Hub API
 *
 * API for Hub authentication and user management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DebugDeviceWsEvent {
    #[serde(rename = "sdp_answer")]
    pub sdp_answer: String,
}

impl DebugDeviceWsEvent {
    pub fn new(sdp_answer: String) -> DebugDeviceWsEvent {
        DebugDeviceWsEvent {
            sdp_answer,
        }
    }
}

