/*
 * Hub API
 *
 * API for Hub authentication and user management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DebugDeviceWsCommand {
    #[serde(rename = "sdp_offer")]
    pub sdp_offer: String,
    #[serde(rename = "device_name")]
    pub device_name: String,
}

impl DebugDeviceWsCommand {
    pub fn new(sdp_offer: String, device_name: String) -> DebugDeviceWsCommand {
        DebugDeviceWsCommand {
            sdp_offer,
            device_name,
        }
    }
}

