/*
 * Hub API
 *
 * API for Hub authentication and user management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeviceConnectionIncomingWsMessage {
    #[serde(rename = "sdp_offer")]
    pub sdp_offer: String,
}

impl DeviceConnectionIncomingWsMessage {
    pub fn new(sdp_offer: String) -> DeviceConnectionIncomingWsMessage {
        DeviceConnectionIncomingWsMessage {
            sdp_offer,
        }
    }
}

