/*
 * Hub API
 *
 * API for Hub authentication and user management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeviceInfo {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "online_at")]
    pub online_at: String,
    #[serde(rename = "status")]
    pub status: Status,
}

impl DeviceInfo {
    pub fn new(name: String, online_at: String, status: Status) -> DeviceInfo {
        DeviceInfo {
            name,
            online_at,
            status,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "offline")]
    Offline,
    #[serde(rename = "online")]
    Online,
    #[serde(rename = "busy")]
    Busy,
}

impl Default for Status {
    fn default() -> Status {
        Self::Offline
    }
}

