/*
 * Hub API
 *
 * API for Hub authentication and user management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeviceConnectionOutgoingWsMessage {
    #[serde(rename = "sdp_answer", deserialize_with = "Option::deserialize")]
    pub sdp_answer: Option<String>,
    #[serde(rename = "uuid", deserialize_with = "Option::deserialize")]
    pub uuid: Option<uuid::Uuid>,
}

impl DeviceConnectionOutgoingWsMessage {
    pub fn new(sdp_answer: Option<String>, uuid: Option<uuid::Uuid>) -> DeviceConnectionOutgoingWsMessage {
        DeviceConnectionOutgoingWsMessage {
            sdp_answer,
            uuid,
        }
    }
}

