/*
 * Hub API
 *
 * API for Hub authentication and user management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeviceInfo {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "online_at")]
    pub online_at: String,
    #[serde(rename = "is_online")]
    pub is_online: bool,
}

impl DeviceInfo {
    pub fn new(name: String, online_at: String, is_online: bool) -> DeviceInfo {
        DeviceInfo {
            name,
            online_at,
            is_online,
        }
    }
}

