/*
 * Hub API
 *
 * API for Hub authentication and user management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ErrorResponse {
    #[serde(rename = "error")]
    pub error: String,
    #[serde(rename = "error_code", deserialize_with = "Option::deserialize")]
    pub error_code: Option<ErrorCode>,
}

impl ErrorResponse {
    pub fn new(error: String, error_code: Option<ErrorCode>) -> ErrorResponse {
        ErrorResponse {
            error,
            error_code,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ErrorCode {
    #[serde(rename = "WEAK_PASSWORD")]
    WeakPassword,
    #[serde(rename = "WRONG_EMAIL_OR_PASSWORD")]
    WrongEmailOrPassword,
    #[serde(rename = "WRONG_OTP")]
    WrongOtp,
    #[serde(rename = "API_TOKEN_NAME_TAKEN")]
    ApiTokenNameTaken,
}

impl Default for ErrorCode {
    fn default() -> ErrorCode {
        Self::WeakPassword
    }
}

