/*
 * Hub API
 *
 * API for Hub authentication and user management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthVerifyEmailRequest {
    #[serde(rename = "code")]
    pub code: String,
}

impl AuthVerifyEmailRequest {
    pub fn new(code: String) -> AuthVerifyEmailRequest {
        AuthVerifyEmailRequest {
            code,
        }
    }
}

