/*
 * Hub API
 *
 * API for Hub authentication and user management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthSignupResponse {
    #[serde(rename = "token")]
    pub token: String,
    #[serde(rename = "needs_verification")]
    pub needs_verification: bool,
}

impl AuthSignupResponse {
    pub fn new(token: String, needs_verification: bool) -> AuthSignupResponse {
        AuthSignupResponse {
            token,
            needs_verification,
        }
    }
}

