/*
 * Hub API
 *
 * API for Hub authentication and user management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConnectDeviceWsRequest {
    #[serde(rename = "uuid")]
    pub uuid: uuid::Uuid,
}

impl ConnectDeviceWsRequest {
    pub fn new(uuid: uuid::Uuid) -> ConnectDeviceWsRequest {
        ConnectDeviceWsRequest {
            uuid,
        }
    }
}

