name: webrogue
configs:
  Debug: debug
  Release: release
  ReleaseLocal: release
settings:
  base:
    MACOSX_DEPLOYMENT_TARGET: 12.0
    IPHONEOS_DEPLOYMENT_TARGET: 15.0
    GENERATE_INFOPLIST_FILE: true
    MARKETING_VERSION: 0.1
    CURRENT_PROJECT_VERSION: 1
    DEAD_CODE_STRIPPING: true
    ENABLE_USER_SCRIPT_SANDBOXING: true
    ENABLE_MODULE_VERIFIER: true
    MODULE_VERIFIER_SUPPORTED_LANGUAGE_STANDARDS: "gnu11 gnu++14"
  configs:
    Debug:
      CODE_SIGN_IDENTITY: "-"
      CARGO_PROFILE: debug
      CODE_SIGN_STYLE: Manual
    Release:
      CODE_SIGN_IDENTITY: "Apple Development"
      CARGO_PROFILE: aot
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: LC5F8UX2W7
    ReleaseLocal:
      CODE_SIGN_IDENTITY: "-"
      CARGO_PROFILE: aot
      CODE_SIGN_STYLE: Manual
options:
  createIntermediateGroups: true
targets:
  GFXStream:
    type: library.static
    platform: [macOS, iOS]
    sources:
    - ../../crates/gfxstream/webrogue_gfxstream.cpp
    - ../../external/gfxstream/host/vulkan/vk_decoder.cpp
    - ../../external/gfxstream/host/vulkan/vulkan_stream.cpp
    - ../../external/gfxstream/host/vulkan/vulkan_handle_mapping.cpp
    - ../../external/gfxstream/host/vulkan/vulkan_boxed_handles.cpp
    - ../../external/gfxstream/host/vulkan/vk_decoder_global_state.cpp
    - ../../external/gfxstream/host/vulkan/render_thread_info_vk.cpp
    - ../../external/gfxstream/host/vulkan/debug_utils_helper.cpp
    - ../../external/gfxstream/host/vulkan/device_op_tracker.cpp
    - ../../external/gfxstream/host/vulkan/vk_common_operations.cpp
    - ../../external/gfxstream/host/vulkan/device_lost_helper.cpp
    - ../../external/gfxstream/host/vulkan/vk_emulated_physical_device_queue.cpp
    - ../../external/gfxstream/host/vulkan/vk_emulated_physical_device_memory.cpp
    - ../../external/gfxstream/host/vulkan/vk_decoder_snapshot.cpp
    - ../../external/gfxstream/host/vulkan/vk_reconstruction.cpp
    - ../../external/gfxstream/host/vulkan/swap_chain_state_vk.cpp
    - ../../external/gfxstream/host/vulkan/dependency_graph.cpp
    - ../../external/gfxstream/host/vulkan/vk_utils.cpp
    - ../../external/gfxstream/host/vulkan/vk_format_utils.cpp
    - ../../external/gfxstream/host/vulkan/external_memory.cpp
    - ../../external/gfxstream/host/vulkan/cereal/common/goldfish_vk_dispatch.cpp
    - ../../external/gfxstream/host/vulkan/cereal/common/goldfish_vk_transform.cpp
    - ../../external/gfxstream/host/vulkan/cereal/common/goldfish_vk_extension_structs.cpp
    - ../../external/gfxstream/host/vulkan/cereal/common/goldfish_vk_reserved_marshaling.cpp
    - ../../external/gfxstream/host/vulkan/cereal/common/goldfish_vk_deepcopy.cpp
    - ../../external/gfxstream/host/vulkan/cereal/common/goldfish_vk_marshaling.cpp
    - ../../external/gfxstream/host/vulkan/emulated_textures/gpu_decompression_pipeline.cpp
    - ../../external/gfxstream/host/vulkan/emulated_textures/astc_texture.cpp
    - ../../external/gfxstream/host/vulkan/emulated_textures/compressed_image_info.cpp
    - ../../external/gfxstream/host/compressed_textures/astc_cpu_decompressor_noop.cpp
    - ../../external/gfxstream/host/features/features.cpp
    - ../../external/gfxstream/host/common/external_object_manager.cpp
    - ../../external/gfxstream/host/common/vm_operations.cpp
    - ../../external/gfxstream/host/common/graphics_driver_lock.cpp
    - ../../external/gfxstream/common/base/UdmabufCreator_stub.cpp
    - ../../external/gfxstream/common/base/System.cpp
    - ../../external/gfxstream/common/logging/logging.cpp
    - ../../external/gfxstream/common/base/Thread_pthread.cpp
    - ../../external/gfxstream/host/common/stream_utils.cpp
    - ../../external/gfxstream/common/base/system-native-mac.mm
    settings:
      base:
        HEADER_SEARCH_PATHS:
        - "$(SRCROOT)/../../external/gfxstream"
        - "$(SRCROOT)/../../external/gfxstream/host"
        - "$(SRCROOT)/../../external/gfxstream/host/common"
        - "$(SRCROOT)/../../external/gfxstream/host/common/include"
        - "$(SRCROOT)/../../external/gfxstream/host/vulkan"
        - "$(SRCROOT)/../../external/gfxstream/host/vulkan/cereal"
        - "$(SRCROOT)/../../external/gfxstream/host/vulkan/cereal/common"
        - "$(SRCROOT)/../../external/gfxstream/host/features/include"
        - "$(SRCROOT)/../../external/gfxstream/host/tracing/include"
        - "$(SRCROOT)/../../external/gfxstream/common/utils/include"
        - "$(SRCROOT)/../../external/gfxstream/host/compressed_textures/include"
        - "$(SRCROOT)/../../external/gfxstream/common/base/include"
        - "$(SRCROOT)/../../external/gfxstream/common/logging/include"
        - "$(SRCROOT)/../../external/gfxstream/host/decoder_common/include"
        - "$(SRCROOT)/../../external/gfxstream/third_party/vulkan/include"
        - "$(SRCROOT)/../../external/gfxstream/host/include"
        - "$(SRCROOT)/../../external/gfxstream/host/iostream/include"
        - "$(SRCROOT)/../../external/gfxstream/third_party/glm/include"
        - "$(SRCROOT)/../../external/gfxstream/host/renderdoc/include"
        - "$(SRCROOT)/../../external/gfxstream/third_party/renderdoc/include"
        - "$(SRCROOT)/../../external/gfxstream/host/library/include"
        - "$(SRCROOT)/../../external/gfxstream/host/snapshot/include"
        - "$(SRCROOT)/../../external/gfxstream/third_party/astc-encoder/Source"
        - "$(SRCROOT)/../../external/gfxstream/third_party/opengl/include"
        - "$(SRCROOT)/../../external/gfxstream/third_party/android/include"
        CLANG_CXX_LANGUAGE_STANDARD:
        - "gnu++20"
        GCC_PREPROCESSOR_DEFINITIONS:
        - "VK_GFXSTREAM_STRUCTURE_TYPE_EXT=1"
        - "VK_USE_PLATFORM_METAL_EXT=1"
        - "VK_USE_PLATFORM_MACOS_MVK=1"
        OTHER_CPLUSPLUSFLAGS:
        - "$(OTHER_CFLAGS)"
        - "-Wno-return-type-c-linkage"
  Launcher:
    type: application
    platform: macOS
    sources:
    - macos/launcher
    settings:
      base:
        CODE_SIGN_ENTITLEMENTS: macos/launcher/launcher.entitlements
        INFOPLIST_FILE: macos/launcher/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: io.github.webrogue-runtime.WebrogueLauncher
        PRODUCT_NAME: Webrogue launcher
        ENABLE_HARDENED_RUNTIME: true
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.utilities
        ENABLE_PREVIEWS: true
    dependencies:
    - target: Runtime
      embed: true
      codeSign: true
      copy:
        destination: executables
    - bundle: libMoltenVK.dylib
      embed: true
      codeSign: true
    preBuildScripts:
      - script: "cp \"${SRCROOT}/external/MoltenVK/MoltenVK/dynamic/dylib/macOS/libMoltenVK.dylib\" \"${BUILT_PRODUCTS_DIR}/libMoltenVK.dylib\""
        name: Download MoltenVK for macOS
        inputFiles:
          - ${SRCROOT}/external/MoltenVK/MoltenVK/dynamic/dylib/macOS/libMoltenVK.dylib
        outputFiles:
          - ${BUILT_PRODUCTS_DIR}/libMoltenVK.dylib
  Runtime:
    type: tool
    platform: macOS
    sources:
    - macos/runtime
    settings:
      base:
        CODE_SIGN_ENTITLEMENTS: macos/runtime/runtime.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: io.github.webrogue-runtime.WebrogueLauncher.Runtime
        PRODUCT_NAME: webrogue_runtime
        OTHER_LDFLAGS: "-lwebrogue_macos"
        LIBRARY_SEARCH_PATHS: "$(BUILD_DIR)/rust_artifacts/runtime/$(CONFIGURATION)/$(PLATFORM_NAME)"
        ENABLE_HARDENED_RUNTIME: true
    dependencies:
    - target: Cargo_macos_runtime
    - target: GFXStream_macOS
    - sdk: Quartz.framework
    - sdk: Metal.framework
    - sdk: IOKit.framework
    - sdk: GameController.framework
    - sdk: ForceFeedback.framework
    - sdk: CoreVideo.framework
    - sdk: CoreHaptics.framework
    - sdk: CoreFoundation.framework
    - sdk: CoreAudio.framework
    - sdk: Cocoa.framework
    - sdk: Carbon.framework
    - sdk: AudioToolbox.framework
    - sdk: libc++.tbd
    - sdk: libc++abi.tbd
  runnerlib:
    type: library.static
    platform: iOS
    sources:
    - ios/runnerlib 
    settings:
      base:
        PRODUCT_NAME: runnerlib
  Launcher_iOS:
    type: application
    platform: iOS
    sources:
    - ios/launcher
    settings:
      base:
        INFOPLIST_FILE: ios/launcher/Info.plist
        CODE_SIGN_ENTITLEMENTS: ios/launcher/ios.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: io.github.webrogue-runtime.WebrogueLauncher
        PRODUCT_NAME: Webrogue Runtime
        OTHER_LDFLAGS: "-lwebrogue_ios"
        LIBRARY_SEARCH_PATHS: "$(BUILD_DIR)/rust_artifacts/ios_launcher/$(CONFIGURATION)/$(PLATFORM_NAME)"
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.utilities
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight UIInterfaceOrientationPortrait"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown"
        ENABLE_PREVIEWS: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UILaunchStoryboardName: LaunchScreen.storyboard
    dependencies:
    - target: Cargo_iOS_launcher
    - target: GFXStream_iOS
    # SDL deps
    - sdk: UIKit.framework
    - sdk: QuartzCore.framework
    - sdk: Metal.framework
    - sdk: IOKit.framework
    - sdk: GameController.framework
    - sdk: CoreVideo.framework
    - sdk: CoreMotion.framework
    - sdk: CoreHaptics.framework
    - sdk: CoreGraphics.framework
    - sdk: CoreFoundation.framework
    - sdk: CoreBluetooth.framework
    - sdk: CoreAudio.framework
    - sdk: AVFoundation.framework
    - sdk: AudioToolbox.framework

    # Wry deps
    - sdk: WebKit.framework
    # MoltenVK
    - framework: external/MoltenVK/MoltenVK/static/MoltenVK.xcframework
  Runner_iOS:
    type: application
    platform: iOS
    sources:
    - path: ios/runner
      excludes:
      - "aot.*.*.o"
    settings:
      base:
        INFOPLIST_FILE: ios/runner/Info.plist
        CODE_SIGN_ENTITLEMENTS: ios/runner/ios.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: io.github.webrogue-runtime.WebrogueRunner
        PRODUCT_NAME: Webrogue Runner
        OTHER_LDFLAGS:
        - "-lwebrogue_ios"
        - "$(BUILD_DIR)/rust_artifacts/ios_runner/$(CONFIGURATION)/$(PLATFORM_NAME)/aot_lipo.o"
        LIBRARY_SEARCH_PATHS: "$(BUILD_DIR)/rust_artifacts/ios_runner/$(CONFIGURATION)/$(PLATFORM_NAME)"
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.utilities
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight UIInterfaceOrientationPortrait"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown"
        ENABLE_PREVIEWS: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UILaunchStoryboardName: LaunchScreen.storyboard
    dependencies:
    - target: Cargo_iOS_runner
    - target: runnerlib
    - target: GFXStream_iOS
    - sdk: UIKit.framework
    - sdk: QuartzCore.framework
    - sdk: Metal.framework
    - sdk: IOKit.framework
    - sdk: GameController.framework
    - sdk: CoreVideo.framework
    - sdk: CoreMotion.framework
    - sdk: CoreHaptics.framework
    - sdk: CoreGraphics.framework
    - sdk: CoreFoundation.framework
    - sdk: CoreBluetooth.framework
    - sdk: CoreAudio.framework
    - sdk: AVFoundation.framework
    - sdk: AudioToolbox.framework
    - sdk: IOSurface.framework
    - framework: external/MoltenVK/RepackedVK.xcframework
    - sdk: libc++.tbd
    - sdk: libc++abi.tbd
    preBuildScripts:
      - script: "sh ${SRCROOT}/scripts/lipo_object_combiner.sh ${SRCROOT}/ios/runner ${BUILD_DIR}/rust_artifacts/ios_runner/${CONFIGURATION}/${PLATFORM_NAME}/aot_lipo.o"
        name: Combine object to lipo
        inputFiles:
          - ${SRCROOT}/ios/runner/aot.x86_64.iphonesimulator.o
          - ${SRCROOT}/ios/runner/aot.arm64.iphonesimulator.o
          - ${SRCROOT}/ios/runner/aot.arm64.iphoneos.o 
          - ${SRCROOT}/scripts/lipo_object_combiner.sh
        outputFiles:
          - ${BUILD_DIR}/rust_artifacts/ios_runner/${CONFIGURATION}/${PLATFORM_NAME}/aot_lipo.o
          - ${BUILD_DIR}/rust_artifacts/ios_runner/${CONFIGURATION}/${PLATFORM_NAME}/aot_lipo.o.lipo
  Cargo_iOS_launcher:
    platform: iOS
    legacy:
      toolPath: /bin/sh
      arguments: ios/rust/cargo_lipo_builder.sh launcher
      workingDirectory: "$(SRCROOT)/"
      passSettings: true
  Cargo_iOS_runner:
    platform: iOS
    legacy:
      toolPath: /bin/sh
      arguments: ios/rust/cargo_lipo_builder.sh runner
      workingDirectory: "$(SRCROOT)/"
      passSettings: true
  Cargo_macos_runtime:
    platform: macOS
    legacy:
      toolPath: /bin/sh
      arguments: macos/rust/cargo_lipo_builder.sh runtime
      workingDirectory: "$(SRCROOT)/"
      passSettings: true
  Cargo_macos_runner:
    platform: macOS
    legacy:
      toolPath: /bin/sh
      arguments: macos/rust/cargo_lipo_builder.sh runner
      workingDirectory: "$(SRCROOT)/"
      passSettings: true
  Runner:
    type: application
    platform: macOS
    sources:
    - path: macos/runner
      excludes:
      - "aot.*.*.o"
    settings:
      base:
        CODE_SIGN_ENTITLEMENTS: macos/runner/runner.entitlements
        INFOPLIST_FILE: macos/runner/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: io.github.webrogue-runtime.WebrogueLauncher.Runner
        PRODUCT_NAME: webrogue_runner
        OTHER_LDFLAGS:
        - "-lwebrogue_macos"
        - "$(BUILD_DIR)/rust_artifacts/runner/$(CONFIGURATION)/$(PLATFORM_NAME)/aot_lipo.o"
        LIBRARY_SEARCH_PATHS: "$(BUILD_DIR)/rust_artifacts/runner/$(CONFIGURATION)/$(PLATFORM_NAME)"
        ENABLE_HARDENED_RUNTIME: true
    dependencies:
    - target: Cargo_macos_runner
    - target: GFXStream_macOS
    - sdk: Quartz.framework
    - sdk: Metal.framework
    - sdk: IOKit.framework
    - sdk: GameController.framework
    - sdk: ForceFeedback.framework
    - sdk: CoreVideo.framework
    - sdk: CoreHaptics.framework
    - sdk: CoreFoundation.framework
    - sdk: CoreAudio.framework
    - sdk: Cocoa.framework
    - sdk: Carbon.framework
    - sdk: AudioToolbox.framework
    - sdk: libc++.tbd
    - sdk: libc++abi.tbd
    - bundle: libMoltenVK.dylib
      embed: true
      codeSign: true
    preBuildScripts:
      - script: "sh ${SRCROOT}/scripts/lipo_object_combiner.sh ${SRCROOT}/macos/runner ${BUILD_DIR}/rust_artifacts/runner/${CONFIGURATION}/${PLATFORM_NAME}/aot_lipo.o"
        name: Combine object to lipo
        inputFiles:
          - ${SRCROOT}/macos/runner/aot.x86_64.macosx.o
          - ${SRCROOT}/macos/runner/aot.arm64.macosx.o
          - ${SRCROOT}/scripts/lipo_object_combiner.sh
        outputFiles:
          - ${BUILD_DIR}/rust_artifacts/runner/${CONFIGURATION}/${PLATFORM_NAME}/aot_lipo.o
          - ${BUILD_DIR}/rust_artifacts/runner/${CONFIGURATION}/${PLATFORM_NAME}/aot_lipo.o.lipo
      - script: "cp \"${SRCROOT}/external/MoltenVK/MoltenVK/dynamic/dylib/macOS/libMoltenVK.dylib\" \"${BUILT_PRODUCTS_DIR}/libMoltenVK.dylib\""
        name: Download MoltenVK for macOS
        inputFiles:
          - ${SRCROOT}/external/MoltenVK/MoltenVK/dynamic/dylib/macOS/libMoltenVK.dylib
        outputFiles:
          - ${BUILT_PRODUCTS_DIR}/libMoltenVK.dylib
schemes:
  MacOS_Launcher_Debug:
    build:
      targets:
        Launcher: Debug
    run:
      config: Debug
  MacOS_Launcher_Release:
    build:
      targets:
        Launcher: Release
    run:
      config: Release
  MacOS_Launcher_ReleaseLocal:
    build:
      targets:
        Launcher: ReleaseLocal
    run:
      config: ReleaseLocal
  MacOS_Runner_Debug:
    build:
      targets:
        Runner: Debug
    run:
      config: Debug
  MacOS_Runner_Release:
    build:
      targets:
        Runner: Release
    run:
      config: Release
  MacOS_Runner_ReleaseLocal:
    build:
      targets:
        Runner: ReleaseLocal
    run:
      config: ReleaseLocal
  iOS_Launcher_Debug:
    build:
      targets:
        Launcher_iOS: Debug
    run:
      config: Debug
  iOS_Launcher_Release:
    build:
      targets:
        Launcher_iOS: Release
    run:
      config: Release
  iOS_Launcher_ReleaseLocal:
    build:
      targets:
        Launcher_iOS: ReleaseLocal
    run:
      config: ReleaseLocal
  iOS_Runner_Debug:
    build:
      targets:
        Runner_iOS: Debug
    run:
      config: Debug
  iOS_Runner_Release:
    build:
      targets:
        Runner_iOS: Release
    run:
      config: Release
  iOS_Runner_ReleaseLocal:
    build:
      targets:
        Runner_iOS: ReleaseLocal
    run:
      config: ReleaseLocal
