name: webrogue
configs:
  Debug: debug
  Release: release
  ReleaseLocal: release
settings:
  base:
    MACOSX_DEPLOYMENT_TARGET: 12.0
    IPHONEOS_DEPLOYMENT_TARGET: 15.0
    GENERATE_INFOPLIST_FILE: true
    MARKETING_VERSION: 0.1
    CURRENT_PROJECT_VERSION: 1
    DEAD_CODE_STRIPPING: true
    ENABLE_USER_SCRIPT_SANDBOXING: true
    ENABLE_MODULE_VERIFIER: true
    MODULE_VERIFIER_SUPPORTED_LANGUAGE_STANDARDS: "gnu11 gnu++14"
  configs:
    Debug:
      CODE_SIGN_IDENTITY: "-"
      CARGO_PROFILE: debug
      CODE_SIGN_STYLE: Manual
    Release:
      CODE_SIGN_IDENTITY: "Apple Development"
      CARGO_PROFILE: aot
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: LC5F8UX2W7
    ReleaseLocal:
      CODE_SIGN_IDENTITY: "-"
      CARGO_PROFILE: aot
      CODE_SIGN_STYLE: Manual
options:
  createIntermediateGroups: true
targets:
  VirGLImpl:
    type: library.static
    platform: [macOS, iOS]
    sources:
    - ../../crates/virgl-lib/webrogue_virgl_impl.c
    - ../../external/virglrenderer/src/virglrenderer.c
    - ../../external/virglrenderer/src/virgl_fence.c
    - ../../external/virglrenderer/src/virgl_util.c
    - ../../external/virglrenderer/src/virgl_context.c
    - ../../external/virglrenderer/src/virgl_resource.c
    - ../../external/virglrenderer/src/venus/vkr_allocator.c
    - ../../external/virglrenderer/src/mesa/util/hash_table.c
    - ../../external/virglrenderer/src/mesa/util/ralloc.c
    - ../../external/virglrenderer/src/mesa/util/os_file.c
    - ../../external/virglrenderer/src/mesa/util/u_debug.c
    - ../../external/virglrenderer/src/mesa/util/os_misc.c
    - ../../external/virglrenderer/src/mesa/util/anon_file.c
    - ../../external/virglrenderer/src/gallium/auxiliary/util/u_hash_table.c
    - ../../external/virglrenderer/src/gallium/auxiliary/util/u_debug_describe.c
    - ../../external/virglrenderer/src/gallium/auxiliary/util/u_texture.c
    - ../../external/virglrenderer/src/gallium/auxiliary/util/u_format.c
    - ../../external/virglrenderer/src/gallium/auxiliary/tgsi/tgsi_info.c
    - ../../external/virglrenderer/src/gallium/auxiliary/tgsi/tgsi_scan.c
    - ../../external/virglrenderer/src/gallium/auxiliary/tgsi/tgsi_dump.c
    - ../../external/virglrenderer/src/gallium/auxiliary/tgsi/tgsi_strings.c
    - ../../external/virglrenderer/src/gallium/auxiliary/tgsi/tgsi_text.c
    - ../../external/virglrenderer/src/gallium/auxiliary/tgsi/tgsi_util.c
    - ../../external/virglrenderer/src/gallium/auxiliary/tgsi/tgsi_parse.c
    - ../../external/virglrenderer/src/gallium/auxiliary/tgsi/tgsi_sanity.c
    - ../../external/virglrenderer/src/gallium/auxiliary/tgsi/tgsi_build.c
    - ../../external/virglrenderer/src/gallium/auxiliary/tgsi/tgsi_iterate.c
    - ../../external/virglrenderer/src/gallium/auxiliary/cso_cache/cso_hash.c
    - ../../external/virglrenderer/src/gallium/auxiliary/cso_cache/cso_cache.c
    - ../../external/virglrenderer/gen/u_format_table.c
    - ../../external/virglrenderer/src/vrend/vrend_blitter.c
    - ../../external/virglrenderer/src/vrend/vrend_formats.c
    - ../../external/virglrenderer/src/vrend/vrend_tweaks.c
    - ../../external/virglrenderer/src/vrend/vrend_debug.c
    - ../../external/virglrenderer/src/vrend/vrend_object.c
    - ../../external/virglrenderer/src/vrend/vrend_decode.c
    - ../../external/virglrenderer/src/vrend/vrend_shader.c
    - ../../external/virglrenderer/src/vrend/iov.c
    - ../../external/virglrenderer/src/vrend/vrend_renderer.c
    - ../../external/virglrenderer/src/vrend/vrend_winsys.c
    - ../../external/virglrenderer/src/venus/vkr_renderer.c
    - ../../external/virglrenderer/src/venus/vkr_buffer.c
    - ../../external/virglrenderer/src/venus/vkr_common.c
    - ../../external/virglrenderer/src/venus/vkr_context.c
    - ../../external/virglrenderer/src/venus/vkr_command_buffer.c
    - ../../external/virglrenderer/src/venus/vkr_cs.c
    - ../../external/virglrenderer/src/venus/vkr_instance.c
    - ../../external/virglrenderer/src/venus/vkr_device.c
    - ../../external/virglrenderer/src/venus/vkr_transport.c
    - ../../external/virglrenderer/src/venus/vkr_ring.c
    - ../../external/virglrenderer/src/venus/vkr_physical_device.c
    - ../../external/virglrenderer/src/venus/vkr_image.c
    - ../../external/virglrenderer/src/venus/vkr_library.c
    - ../../external/virglrenderer/src/venus/vkr_descriptor_heap.c
    - ../../external/virglrenderer/src/venus/vkr_queue.c
    - ../../external/virglrenderer/src/venus/vkr_query_pool.c
    - ../../external/virglrenderer/src/venus/vkr_descriptor_set.c
    - ../../external/virglrenderer/src/venus/vkr_pipeline.c
    - ../../external/virglrenderer/src/venus/vkr_acceleration_structure.c
    - ../../external/virglrenderer/src/venus/vkr_render_pass.c
    - ../../external/virglrenderer/src/venus/vkr_device_memory.c
    - ../../external/virglrenderer/src/venus/vkr_host_copy.c
    - ../../external/virglrenderer/src/venus/vkr_webrogue.c
    - ../../external/virglrenderer/src/proxy/proxy_renderer.c
    - ../../external/virglrenderer/src/proxy/proxy_server.c
    - ../../external/virglrenderer/src/proxy/proxy_client.c
    - ../../external/virglrenderer/src/proxy/proxy_context.c
    - ../../external/virglrenderer/src/proxy/proxy_socket.c
    - ../../external/virglrenderer/src/proxy/proxy_common.c
    - ../../external/virglrenderer/server/render_server.c
    - ../../external/virglrenderer/server/render_client.c
    - ../../external/virglrenderer/server/render_context.c
    - ../../external/virglrenderer/server/render_socket.c
    - ../../external/virglrenderer/server/render_worker.c
    - ../../external/virglrenderer/server/render_state.c
    - ../../external/virglrenderer/server/render_common.c
    settings:
      base:
        HEADER_SEARCH_PATHS:
        - "$(SRCROOT)/virgl"
        - "$(SRCROOT)/../../crates/virgl-lib"
        - "$(SRCROOT)/../../external/virglrenderer"
        - "$(SRCROOT)/../../external/virglrenderer/gen"
        - "$(SRCROOT)/../../external/virglrenderer/src"
        - "$(SRCROOT)/../../external/virglrenderer/src/venus"
        - "$(SRCROOT)/../../external/virglrenderer/src/drm"
        - "$(SRCROOT)/../../external/virglrenderer/src/drm/drm-uapi"
        - "$(SRCROOT)/../../external/virglrenderer/src/gallium/include"
        - "$(SRCROOT)/../../external/virglrenderer/src/gallium/auxiliary"
        - "$(SRCROOT)/../../external/virglrenderer/src/gallium/auxiliary/util"
        - "$(SRCROOT)/../../external/virglrenderer/src/mesa"
        - "$(SRCROOT)/../../external/virglrenderer/src/mesa/pipe"
        - "$(SRCROOT)/../../external/virglrenderer/src/mesa/compat"
        - "$(SRCROOT)/../../external/virglrenderer/src/mesa/util"
        CLANG_C_LANGUAGE_STANDARD: "gnu11"
        GCC_PREPROCESSOR_DEFINITIONS:
        - "HAVE_CONFIG_H=1"
        - "VK_USE_PLATFORM_WEBROGUE=1"
        - "VK_USE_PLATFORM_METAL_EXT=1"
        - "VK_ENABLE_BETA_EXTENSIONS=1"
        OTHER_CFLAGS:
        - "$(inherited)"
        - "-imacros$(SRCROOT)/virgl/config.h"
        - "-Wno-unused-parameter"
        - "-Wno-attributes"
  VirGLStub:
    type: library.static
    platform: [macOS, iOS]
    sources:
    - ../../crates/virgl-lib/webrogue_virgl_stub.c
    settings:
      base:
        HEADER_SEARCH_PATHS:
        - "$(SRCROOT)/virgl"
        - "$(SRCROOT)/../../external/virglrenderer"
        - "$(SRCROOT)/../../external/virglrenderer/src"
        - "$(SRCROOT)/../../external/virglrenderer/src/venus"
        - "$(SRCROOT)/../../external/virglrenderer/src/drm"
        - "$(SRCROOT)/../../external/virglrenderer/src/drm/drm-uapi"
        - "$(SRCROOT)/../../external/virglrenderer/src/gallium/include"
        - "$(SRCROOT)/../../external/virglrenderer/src/gallium/auxiliary"
        - "$(SRCROOT)/../../external/virglrenderer/src/gallium/auxiliary/util"
        - "$(SRCROOT)/../../external/virglrenderer/src/mesa"
        - "$(SRCROOT)/../../external/virglrenderer/src/mesa/pipe"
        - "$(SRCROOT)/../../external/virglrenderer/src/mesa/compat"
        - "$(SRCROOT)/../../external/virglrenderer/src/mesa/util"
        CLANG_C_LANGUAGE_STANDARD: "gnu11"
        GCC_PREPROCESSOR_DEFINITIONS:
        - "HAVE_CONFIG_H=1"
        OTHER_CFLAGS:
        - "$(inherited)"
        - "-imacros$(SRCROOT)/virgl/config.h"
  Launcher:
    type: application
    platform: macOS
    sources:
    - macos/launcher
    settings:
      base:
        CODE_SIGN_ENTITLEMENTS: macos/launcher/launcher.entitlements
        INFOPLIST_FILE: macos/launcher/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: io.github.webrogue-runtime.WebrogueLauncher
        PRODUCT_NAME: Webrogue launcher
        ENABLE_HARDENED_RUNTIME: true
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.utilities
        ENABLE_PREVIEWS: true
    dependencies:
    - target: Runtime
      embed: true
      codeSign: true
      copy:
        destination: executables
    - bundle: libMoltenVK.dylib
      embed: true
      codeSign: true
    preBuildScripts:
      - script: "cp \"${SRCROOT}/external/MoltenVK/MoltenVK/dynamic/dylib/macOS/libMoltenVK.dylib\" \"${BUILT_PRODUCTS_DIR}/libMoltenVK.dylib\""
        name: Download MoltenVK for macOS
        inputFiles:
          - ${SRCROOT}/external/MoltenVK/MoltenVK/dynamic/dylib/macOS/libMoltenVK.dylib
        outputFiles:
          - ${BUILT_PRODUCTS_DIR}/libMoltenVK.dylib
  Runtime:
    type: tool
    platform: macOS
    sources:
    - macos/runtime
    settings:
      base:
        CODE_SIGN_ENTITLEMENTS: macos/runtime/runtime.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: io.github.webrogue-runtime.WebrogueLauncher.Runtime
        PRODUCT_NAME: webrogue_runtime
        OTHER_LDFLAGS: "-lwebrogue_macos"
        LIBRARY_SEARCH_PATHS: "$(BUILD_DIR)/rust_artifacts/runtime/$(CONFIGURATION)/$(PLATFORM_NAME)"
        ENABLE_HARDENED_RUNTIME: true
    dependencies:
    - target: Cargo_macos_runtime
    - target: VirGLImpl_macOS
    - sdk: Quartz.framework
    - sdk: Metal.framework
    - sdk: IOKit.framework
    - sdk: GameController.framework
    - sdk: ForceFeedback.framework
    - sdk: CoreVideo.framework
    - sdk: CoreHaptics.framework
    - sdk: CoreFoundation.framework
    - sdk: CoreAudio.framework
    - sdk: Cocoa.framework
    - sdk: Carbon.framework
    - sdk: AudioToolbox.framework
    - sdk: libc++.tbd
    - sdk: libc++abi.tbd
  runnerlib:
    type: library.static
    platform: iOS
    sources:
    - ios/runnerlib 
    settings:
      base:
        PRODUCT_NAME: runnerlib
  Launcher_iOS:
    type: application
    platform: iOS
    sources:
    - ios/launcher
    settings:
      base:
        INFOPLIST_FILE: ios/launcher/Info.plist
        CODE_SIGN_ENTITLEMENTS: ios/launcher/ios.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: io.github.webrogue-runtime.WebrogueLauncher
        PRODUCT_NAME: Webrogue Runtime
        OTHER_LDFLAGS: "-lwebrogue_ios"
        LIBRARY_SEARCH_PATHS: "$(BUILD_DIR)/rust_artifacts/ios_launcher/$(CONFIGURATION)/$(PLATFORM_NAME)"
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.utilities
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight UIInterfaceOrientationPortrait"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown"
        ENABLE_PREVIEWS: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UILaunchStoryboardName: LaunchScreen.storyboard
    dependencies:
    - target: Cargo_iOS_launcher
    - target: VirGLImpl_iOS
    # SDL deps
    - sdk: UIKit.framework
    - sdk: QuartzCore.framework
    - sdk: Metal.framework
    - sdk: IOKit.framework
    - sdk: GameController.framework
    - sdk: CoreVideo.framework
    - sdk: CoreMotion.framework
    - sdk: CoreHaptics.framework
    - sdk: CoreGraphics.framework
    - sdk: CoreFoundation.framework
    - sdk: CoreBluetooth.framework
    - sdk: CoreAudio.framework
    - sdk: AVFoundation.framework
    - sdk: AudioToolbox.framework

    # Wry deps
    - sdk: WebKit.framework
    # MoltenVK
    - framework: external/MoltenVK/MoltenVK/static/MoltenVK.xcframework
  Runner_iOS:
    type: application
    platform: iOS
    sources:
    - path: ios/runner
      excludes:
      - "aot.*.*.o"
    settings:
      base:
        INFOPLIST_FILE: ios/runner/Info.plist
        CODE_SIGN_ENTITLEMENTS: ios/runner/ios.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: io.github.webrogue-runtime.WebrogueRunner
        PRODUCT_NAME: Webrogue Runner
        OTHER_LDFLAGS:
        - "-lwebrogue_ios"
        - "$(BUILD_DIR)/rust_artifacts/ios_runner/$(CONFIGURATION)/$(PLATFORM_NAME)/aot_lipo.o"
        LIBRARY_SEARCH_PATHS: "$(BUILD_DIR)/rust_artifacts/ios_runner/$(CONFIGURATION)/$(PLATFORM_NAME)"
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.utilities
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight UIInterfaceOrientationPortrait"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown"
        ENABLE_PREVIEWS: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UILaunchStoryboardName: LaunchScreen.storyboard
    dependencies:
    - target: Cargo_iOS_runner
    - target: runnerlib
    - target: VirGLImpl_iOS
    - sdk: UIKit.framework
    - sdk: QuartzCore.framework
    - sdk: Metal.framework
    - sdk: IOKit.framework
    - sdk: GameController.framework
    - sdk: CoreVideo.framework
    - sdk: CoreMotion.framework
    - sdk: CoreHaptics.framework
    - sdk: CoreGraphics.framework
    - sdk: CoreFoundation.framework
    - sdk: CoreBluetooth.framework
    - sdk: CoreAudio.framework
    - sdk: AVFoundation.framework
    - sdk: AudioToolbox.framework
    - sdk: IOSurface.framework
    - framework: external/MoltenVK/RepackedVK.xcframework
    - sdk: libc++.tbd
    - sdk: libc++abi.tbd
    preBuildScripts:
      - script: "sh ${SRCROOT}/scripts/lipo_object_combiner.sh ${SRCROOT}/ios/runner ${BUILD_DIR}/rust_artifacts/ios_runner/${CONFIGURATION}/${PLATFORM_NAME}/aot_lipo.o"
        name: Combine object to lipo
        inputFiles:
          - ${SRCROOT}/ios/runner/aot.x86_64.iphonesimulator.o
          - ${SRCROOT}/ios/runner/aot.arm64.iphonesimulator.o
          - ${SRCROOT}/ios/runner/aot.arm64.iphoneos.o 
          - ${SRCROOT}/scripts/lipo_object_combiner.sh
        outputFiles:
          - ${BUILD_DIR}/rust_artifacts/ios_runner/${CONFIGURATION}/${PLATFORM_NAME}/aot_lipo.o
          - ${BUILD_DIR}/rust_artifacts/ios_runner/${CONFIGURATION}/${PLATFORM_NAME}/aot_lipo.o.lipo
  Cargo_iOS_launcher:
    platform: iOS
    legacy:
      toolPath: /bin/sh
      arguments: ios/rust/cargo_lipo_builder.sh launcher
      workingDirectory: "$(SRCROOT)/"
      passSettings: true
  Cargo_iOS_runner:
    platform: iOS
    legacy:
      toolPath: /bin/sh
      arguments: ios/rust/cargo_lipo_builder.sh runner
      workingDirectory: "$(SRCROOT)/"
      passSettings: true
  Cargo_macos_runtime:
    platform: macOS
    legacy:
      toolPath: /bin/sh
      arguments: macos/rust/cargo_lipo_builder.sh runtime
      workingDirectory: "$(SRCROOT)/"
      passSettings: true
  Cargo_macos_runner:
    platform: macOS
    legacy:
      toolPath: /bin/sh
      arguments: macos/rust/cargo_lipo_builder.sh runner
      workingDirectory: "$(SRCROOT)/"
      passSettings: true
  Runner:
    type: application
    platform: macOS
    sources:
    - path: macos/runner
      excludes:
      - "aot.*.*.o"
    settings:
      base:
        CODE_SIGN_ENTITLEMENTS: macos/runner/runner.entitlements
        INFOPLIST_FILE: macos/runner/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: io.github.webrogue-runtime.WebrogueLauncher.Runner
        PRODUCT_NAME: webrogue_runner
        OTHER_LDFLAGS:
        - "-lwebrogue_macos"
        - "$(BUILD_DIR)/rust_artifacts/runner/$(CONFIGURATION)/$(PLATFORM_NAME)/aot_lipo.o"
        LIBRARY_SEARCH_PATHS: "$(BUILD_DIR)/rust_artifacts/runner/$(CONFIGURATION)/$(PLATFORM_NAME)"
        ENABLE_HARDENED_RUNTIME: true
    dependencies:
    - target: Cargo_macos_runner
    - target: VirGLImpl_macOS
    - sdk: Quartz.framework
    - sdk: Metal.framework
    - sdk: IOKit.framework
    - sdk: GameController.framework
    - sdk: ForceFeedback.framework
    - sdk: CoreVideo.framework
    - sdk: CoreHaptics.framework
    - sdk: CoreFoundation.framework
    - sdk: CoreAudio.framework
    - sdk: Cocoa.framework
    - sdk: Carbon.framework
    - sdk: AudioToolbox.framework
    - sdk: libc++.tbd
    - sdk: libc++abi.tbd
    - bundle: libMoltenVK.dylib
      embed: true
      codeSign: true
    preBuildScripts:
      - script: "sh ${SRCROOT}/scripts/lipo_object_combiner.sh ${SRCROOT}/macos/runner ${BUILD_DIR}/rust_artifacts/runner/${CONFIGURATION}/${PLATFORM_NAME}/aot_lipo.o"
        name: Combine object to lipo
        inputFiles:
          - ${SRCROOT}/macos/runner/aot.x86_64.macosx.o
          - ${SRCROOT}/macos/runner/aot.arm64.macosx.o
          - ${SRCROOT}/scripts/lipo_object_combiner.sh
        outputFiles:
          - ${BUILD_DIR}/rust_artifacts/runner/${CONFIGURATION}/${PLATFORM_NAME}/aot_lipo.o
          - ${BUILD_DIR}/rust_artifacts/runner/${CONFIGURATION}/${PLATFORM_NAME}/aot_lipo.o.lipo
      - script: "cp \"${SRCROOT}/external/MoltenVK/MoltenVK/dynamic/dylib/macOS/libMoltenVK.dylib\" \"${BUILT_PRODUCTS_DIR}/libMoltenVK.dylib\""
        name: Download MoltenVK for macOS
        inputFiles:
          - ${SRCROOT}/external/MoltenVK/MoltenVK/dynamic/dylib/macOS/libMoltenVK.dylib
        outputFiles:
          - ${BUILT_PRODUCTS_DIR}/libMoltenVK.dylib
schemes:
  MacOS_Launcher_Debug:
    build:
      targets:
        Launcher: Debug
    run:
      config: Debug
  MacOS_Launcher_Release:
    build:
      targets:
        Launcher: Release
    run:
      config: Release
  MacOS_Launcher_ReleaseLocal:
    build:
      targets:
        Launcher: ReleaseLocal
    run:
      config: ReleaseLocal
  MacOS_Runner_Debug:
    build:
      targets:
        Runner: Debug
    run:
      config: Debug
  MacOS_Runner_Release:
    build:
      targets:
        Runner: Release
    run:
      config: Release
  MacOS_Runner_ReleaseLocal:
    build:
      targets:
        Runner: ReleaseLocal
    run:
      config: ReleaseLocal
  iOS_Launcher_Debug:
    build:
      targets:
        Launcher_iOS: Debug
    run:
      config: Debug
  iOS_Launcher_Release:
    build:
      targets:
        Launcher_iOS: Release
    run:
      config: Release
  iOS_Launcher_ReleaseLocal:
    build:
      targets:
        Launcher_iOS: ReleaseLocal
    run:
      config: ReleaseLocal
  iOS_Runner_Debug:
    build:
      targets:
        Runner_iOS: Debug
    run:
      config: Debug
  iOS_Runner_Release:
    build:
      targets:
        Runner_iOS: Release
    run:
      config: Release
  iOS_Runner_ReleaseLocal:
    build:
      targets:
        Runner_iOS: ReleaseLocal
    run:
      config: ReleaseLocal
