name: webrogue
configs:
  Debug: debug
  Release: release
  ReleaseLocal: release
projectReferences:
  SDL:
    path: ./external/SDL2/Xcode/SDL/SDL.xcodeproj
settings:
  base:
    MACOSX_DEPLOYMENT_TARGET: 12.0
    IPHONEOS_DEPLOYMENT_TARGET: 14.0
    GENERATE_INFOPLIST_FILE: true
    MARKETING_VERSION: 0.1
    CURRENT_PROJECT_VERSION: 1
    DEAD_CODE_STRIPPING: true
    ENABLE_USER_SCRIPT_SANDBOXING: true
    ENABLE_MODULE_VERIFIER: true
    MODULE_VERIFIER_SUPPORTED_LANGUAGE_STANDARDS: "gnu11 gnu++14"
    ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: true
  configs:
    Debug:
      CODE_SIGN_IDENTITY: "-"
      CARGO_PROFILE: debug
      CODE_SIGN_STYLE: Manual
    Release:
      CODE_SIGN_IDENTITY: "Apple Development"
      CARGO_PROFILE: release-lto
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: LC5F8UX2W7
    ReleaseLocal:
      CODE_SIGN_IDENTITY: "-"
      CARGO_PROFILE: release-lto
      CODE_SIGN_STYLE: Manual
options:
  createIntermediateGroups: true
targets:
  Launcher:
    type: application
    platform: macOS
    sources:
    - macOS/Launcher
    settings:
      base:
        CODE_SIGN_ENTITLEMENTS: macOS/Launcher/launcher.entitlements
        INFOPLIST_FILE: macOS/Launcher/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: io.github.webrogue-runtime.WebrogueLauncher
        PRODUCT_NAME: webrogue Launcher
        ENABLE_HARDENED_RUNTIME: true
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.utilities
        ENABLE_PREVIEWS: true
    dependencies:
    - target: WebrogueCommon
    - target: Runtime
      embed: true
      codeSign: true
      copy:
        destination: executables
    - bundle: libEGL.dylib
      embed: true
      codeSign: true
    - bundle: libGLESv2.dylib
      embed: true
      codeSign: true
    preBuildScripts:
      - script: "cd \"${BUILT_PRODUCTS_DIR}\"; sh ${SRCROOT}/scripts/download_angle_bin.sh"
        name: Download ANGLE
        inputFiles:
          - ${SRCROOT}/scripts/download_angle_bin.sh
        outputFiles:
          - ${BUILT_PRODUCTS_DIR}/macos_fat.zip
          - ${BUILT_PRODUCTS_DIR}/libEGL.dylib
          - ${BUILT_PRODUCTS_DIR}/libGLESv2.dylib
  Runtime:
    type: tool
    platform: macOS
    sources:
    - path: macOS/runtime
      excludes:
      - "**/rust"
    settings:
      base:
        CODE_SIGN_ENTITLEMENTS: macOS/runtime/runtime.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: io.github.webrogue-runtime.WebrogueLauncher.Runtime
        PRODUCT_NAME: webrogue_runtime
        OTHER_LDFLAGS: "-lwebrogue_macos"
        LIBRARY_SEARCH_PATHS: "$(BUILD_DIR)/rust_artifacts/runtime/$(CONFIGURATION)/$(PLATFORM_NAME)"
        HEADER_SEARCH_PATHS: "$(SRCROOT)/external/SDL2/include"
        ENABLE_HARDENED_RUNTIME: true
    dependencies:
    - target: Cargo_macos_runtime
    - target: SDL/Static Library
    - sdk: Quartz.framework
    - sdk: Metal.framework
    - sdk: IOKit.framework
    - sdk: GameController.framework
    - sdk: ForceFeedback.framework
    - sdk: CoreVideo.framework
    - sdk: CoreHaptics.framework
    - sdk: CoreFoundation.framework
    - sdk: CoreAudio.framework
    - sdk: Cocoa.framework
    - sdk: Carbon.framework
    - sdk: AudioToolbox.framework
  Launcher_iOS:
    type: application
    platform: iOS
    sources:
    - path: iOS
      excludes:
      - "**/rust"
    settings:
      base:
        INFOPLIST_FILE: iOS/Info.plist
        CODE_SIGN_ENTITLEMENTS: iOS/ios.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: io.github.webrogue-runtime.WebrogueLauncher
        PRODUCT_NAME: webrogue
        SWIFT_OBJC_BRIDGING_HEADER: "$(SRCROOT)/iOS/Source/webrogue-Bridging-Header.h"
        OTHER_LDFLAGS: "-lwebrogue_ios"
        LIBRARY_SEARCH_PATHS: "$(BUILD_DIR)/rust_artifacts/runtime_ios/$(CONFIGURATION)/$(PLATFORM_NAME)"
        HEADER_SEARCH_PATHS:
        - "$(SRCROOT)/external/SDL2/include"
        SYSTEM_HEADER_SEARCH_PATHS:
        - "$(SRCROOT)/external/angle_ios_headers"
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.utilities
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight UIInterfaceOrientationPortrait"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown"
        ENABLE_PREVIEWS: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UILaunchStoryboardName: LaunchScreen.storyboard
    dependencies:
    - target: Cargo_iOS
    - target: SDL/Static Library-iOS
    - target: WebrogueCommon
    - sdk: UIKit.framework
    - sdk: QuartzCore.framework
    - sdk: Metal.framework
    - sdk: IOKit.framework
    - sdk: GameController.framework
    - sdk: CoreVideo.framework
    - sdk: CoreMotion.framework
    - sdk: CoreHaptics.framework
    - sdk: CoreGraphics.framework
    - sdk: CoreFoundation.framework
    - sdk: CoreBluetooth.framework
    - sdk: CoreAudio.framework
    - sdk: AVFoundation.framework
    - sdk: AudioToolbox.framework
    - framework: external/libEGL.xcframework
    - framework: external/libGLESv2.xcframework
  WebrogueCommon:
    type: framework.static
    supportedDestinations: [macOS, iOS]
    sources:
    - Common/WebrogueCommon
    settings:
      base:
        INFOPLIST_FILE: Common/WebrogueCommon/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: io.github.webrogue-runtime.WebrogueCommon
        PRODUCT_NAME: WebrogueCommon
  Cargo_iOS:
    platform: iOS
    legacy:
      toolPath: /bin/sh
      arguments: iOS/rust/cargo_lipo_builder.sh
      workingDirectory: $(SRCROOT)/
      passSettings: true
  Cargo_macos_runtime:
    platform: macOS
    legacy:
      toolPath: /bin/sh
      arguments: macOS/runtime/rust/cargo_lipo_builder.sh runtime
      workingDirectory: $(SRCROOT)/
      passSettings: true
  Cargo_macos_runner:
    platform: macOS
    legacy:
      toolPath: /bin/sh
      arguments: macOS/runtime/rust/cargo_lipo_builder.sh runner
      workingDirectory: $(SRCROOT)/
      passSettings: true
  Runner:
    type: application
    platform: macOS
    sources:
    - path: macOS/runner
      excludes:
      - "aot_*.o"
    settings:
      base:
        CODE_SIGN_ENTITLEMENTS: macOS/runner/runner.entitlements
        INFOPLIST_FILE: macOS/runner/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: io.github.webrogue-runtime.WebrogueLauncher.Runner
        PRODUCT_NAME: webrogue_runner
        OTHER_LDFLAGS:
        - "-lwebrogue_macos"
        - "$(BUILD_DIR)/rust_artifacts/runner/$(CONFIGURATION)/$(PLATFORM_NAME)/aot_lipo.o"
        LIBRARY_SEARCH_PATHS: "$(BUILD_DIR)/rust_artifacts/runner/$(CONFIGURATION)/$(PLATFORM_NAME)"
        HEADER_SEARCH_PATHS: "$(SRCROOT)/external/SDL2/include"
        ENABLE_HARDENED_RUNTIME: true
    dependencies:
    - target: Cargo_macos_runner
    - target: SDL/Static Library
    - sdk: Quartz.framework
    - sdk: Metal.framework
    - sdk: IOKit.framework
    - sdk: GameController.framework
    - sdk: ForceFeedback.framework
    - sdk: CoreVideo.framework
    - sdk: CoreHaptics.framework
    - sdk: CoreFoundation.framework
    - sdk: CoreAudio.framework
    - sdk: Cocoa.framework
    - sdk: Carbon.framework
    - sdk: AudioToolbox.framework
    - bundle: libEGL.dylib
      embed: true
      codeSign: true
    - bundle: libGLESv2.dylib
      embed: true
      codeSign: true
    preBuildScripts:
      - script: "sh ${SRCROOT}/scripts/lipo_object_combiner.sh ${SRCROOT}/macOS/runner ${BUILD_DIR}/rust_artifacts/runner/${CONFIGURATION}/${PLATFORM_NAME}/aot_lipo.o"
        name: Combine object to lipo
        inputFiles:
          - ${SRCROOT}/macOS/runner/aot_x86_64.o
          - ${SRCROOT}/macOS/runner/aot_arm64.o
          - ${SRCROOT}/scripts/lipo_object_combiner.sh
        outputFiles:
          - ${BUILD_DIR}/rust_artifacts/runner/${CONFIGURATION}/${PLATFORM_NAME}/aot_lipo.o
          - ${BUILD_DIR}/rust_artifacts/runner/${CONFIGURATION}/${PLATFORM_NAME}/aot_lipo.o.lipo
      - script: "cd \"${BUILT_PRODUCTS_DIR}\"; sh ${SRCROOT}/scripts/download_angle_bin.sh"
        name: Download ANGLE
        inputFiles:
          - ${SRCROOT}/scripts/download_angle_bin.sh
        outputFiles:
          - ${BUILT_PRODUCTS_DIR}/macos_fat.zip
          - ${BUILT_PRODUCTS_DIR}/libEGL.dylib
          - ${BUILT_PRODUCTS_DIR}/libGLESv2.dylib
schemes:
  MacOS_Launcher_Debug:
    build:
      targets:
        Launcher: Debug
    run:
      config: Debug
  MacOS_Launcher_Release:
    build:
      targets:
        Launcher: Release
    run:
      config: Release
  MacOS_Launcher_ReleaseLocal:
    build:
      targets:
        Launcher: ReleaseLocal
        SDL/Static Library: Release
    run:
      config: ReleaseLocal
  MacOS_Runner_Debug:
    build:
      targets:
        Runner: Debug
    run:
      config: Debug
  MacOS_Runner_Release:
    build:
      targets:
        Runner: Release
    run:
      config: Release
  MacOS_Runner_ReleaseLocal:
    build:
      targets:
        Runner: ReleaseLocal
    run:
      config: ReleaseLocal
  iOS_Debug:
    build:
      targets:
        Launcher_iOS: Debug
    run:
      config: Debug
  iOS_Release:
    build:
      targets:
        Launcher_iOS: Release
    run:
      config: Release
  iOS_ReleaseLocal:
    build:
      targets:
        Launcher_iOS: ReleaseLocal
    run:
      config: ReleaseLocal
