[package]
name = "webrogue-wrapp"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[features]
write = []

[dependencies]
anyhow = { workspace = true }
zstd-safe = { workspace = true, features = ["seekable", "std"] }
zstd = { workspace = true }
webrogue-common = { workspace = true }
#image = { workspace = true, optional = true, default-features = false, features = ["png", "rayon"] }
