[package]
name = "webrogue-wrapp"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
anyhow = { workspace = true }
zstd-seekable = { workspace = true }
