[package]
name = "webrogue-wrapp"
version.workspace = true
authors.workspace = true
edition.workspace = true

[features]
write = ["dep:image"]

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
anyhow = { workspace = true }
zstd-safe = { workspace = true, features = ["seekable", "std"] }
image = { workspace = true, optional = true, default-features = false, features = ["png", "rayon"] }
semver = { workspace = true, default-features = false, features = ["serde"]  }
