all: jenkins_rsa android_key_password android_store_password

jenkins_rsa:
	ssh-keygen -f jenkins_rsa -N ""

android_key_password:
	echo "keys/android_key_password not provided!" && exit 1
	
android_store_password:
	echo "keys/android_store_password not provided!" && exit 1
