#![allow(dead_code)]
#![allow(non_camel_case_types)]
#![allow(non_upper_case_globals)]
/* automatically generated by rust-bindgen 0.72.1 */

pub const ENABLE_VENUS: u32 = 1;
pub const CHECK_GL_ERRORS: u32 = 1;
pub const HAVE_FUNC_ATTRIBUTE_WEAK: u32 = 1;
pub const HAVE___BUILTIN_EXPECT: u32 = 1;
pub const HAVE_FUNC_ATTRIBUTE_RETURNS_NONNULL: u32 = 1;
pub const ENABLE_RENDER_SERVER: u32 = 1;
pub const UTIL_ARCH_BIG_ENDIAN: u32 = 0;
pub const VIRGL_RENDERER_UNSTABLE_APIS: u32 = 1;
pub const RENDER_SERVER_EXEC_PATH: &[u8; 16] = b"No path to that\0";
pub const HAVE_PTHREAD: u32 = 1;
pub const ENABLE_SAME_PROCESS_RENDER_SERVER: u32 = 1;
pub const UTIL_ARCH_LITTLE_ENDIAN: u32 = 1;
pub const HAVE___BUILTIN_CLZ: u32 = 1;
pub const HAVE_FUNC_ATTRIBUTE_PURE: u32 = 1;
pub const HAVE_SYS_UIO_H: u32 = 1;
pub const HAVE_TIMESPEC_GET: u32 = 1;
pub const HAVE___BUILTIN_CLZLL: u32 = 1;
pub const HAVE___BUILTIN_TYPES_COMPATIBLE_P: u32 = 1;
pub const PIPE_ARCH_X86_64: u32 = 1;
pub const HAVE___BUILTIN_BSWAP32: u32 = 1;
pub const HAVE___BUILTIN_BSWAP64: u32 = 1;
pub const HAVE_FUNC_ATTRIBUTE_PACKED: u32 = 1;
pub const HAVE___BUILTIN_POPCOUNT: u32 = 1;
pub const HAVE_FUNC_ATTRIBUTE_NORETURN: u32 = 1;
pub const HAVE_MEMFD_CREATE: u32 = 1;
pub const ENABLE_RENDER_SERVER_WORKER_THREAD: u32 = 1;
pub const HAVE_FUNC_ATTRIBUTE_UNUSED: u32 = 1;
pub const HAVE_PTHREAD_SETAFFINITY: u32 = 1;
pub const HAVE_FUNC_ATTRIBUTE_WARN_UNUSED_RESULT: u32 = 1;
pub const HAVE___BUILTIN_FFS: u32 = 1;
pub const HAVE_STRTOK_R: u32 = 1;
pub const _GNU_SOURCE: u32 = 1;
pub const HAVE_FUNC_ATTRIBUTE_FORMAT: u32 = 1;
pub const HAVE___BUILTIN_UNREACHABLE: u32 = 1;
pub const HAVE_FUNC_ATTRIBUTE_MALLOC: u32 = 1;
pub const HAVE___BUILTIN_FFSLL: u32 = 1;
pub const HAVE_FUNC_ATTRIBUTE_CONST: u32 = 1;
pub const HAVE___BUILTIN_POPCOUNTLL: u32 = 1;
pub const HAVE_EVENTFD_H: u32 = 1;
pub const HAVE_FUNC_ATTRIBUTE_FLATTEN: u32 = 1;
pub const _STDINT_H: u32 = 1;
pub const _FEATURES_H: u32 = 1;
pub const _ISOC95_SOURCE: u32 = 1;
pub const _ISOC99_SOURCE: u32 = 1;
pub const _ISOC11_SOURCE: u32 = 1;
pub const _ISOC23_SOURCE: u32 = 1;
pub const _ISOC2Y_SOURCE: u32 = 1;
pub const _POSIX_SOURCE: u32 = 1;
pub const _POSIX_C_SOURCE: u32 = 202405;
pub const _XOPEN_SOURCE: u32 = 800;
pub const _XOPEN_SOURCE_EXTENDED: u32 = 1;
pub const _LARGEFILE64_SOURCE: u32 = 1;
pub const _DEFAULT_SOURCE: u32 = 1;
pub const _ATFILE_SOURCE: u32 = 1;
pub const _DYNAMIC_STACK_SIZE_SOURCE: u32 = 1;
pub const __GLIBC_USE_ISOC2Y: u32 = 1;
pub const __GLIBC_USE_ISOC23: u32 = 1;
pub const __USE_ISOC11: u32 = 1;
pub const __USE_ISOC99: u32 = 1;
pub const __USE_ISOC95: u32 = 1;
pub const __USE_POSIX: u32 = 1;
pub const __USE_POSIX2: u32 = 1;
pub const __USE_POSIX199309: u32 = 1;
pub const __USE_POSIX199506: u32 = 1;
pub const __USE_XOPEN2K: u32 = 1;
pub const __USE_XOPEN2K8: u32 = 1;
pub const __USE_XOPEN2K24: u32 = 1;
pub const __USE_XOPEN: u32 = 1;
pub const __USE_XOPEN_EXTENDED: u32 = 1;
pub const __USE_UNIX98: u32 = 1;
pub const _LARGEFILE_SOURCE: u32 = 1;
pub const __USE_XOPEN2K8XSI: u32 = 1;
pub const __USE_XOPEN2K24XSI: u32 = 1;
pub const __USE_XOPEN2KXSI: u32 = 1;
pub const __USE_LARGEFILE: u32 = 1;
pub const __USE_LARGEFILE64: u32 = 1;
pub const __WORDSIZE: u32 = 64;
pub const __WORDSIZE_TIME64_COMPAT32: u32 = 1;
pub const __SYSCALL_WORDSIZE: u32 = 64;
pub const __TIMESIZE: u32 = 64;
pub const __USE_TIME_BITS64: u32 = 1;
pub const __USE_MISC: u32 = 1;
pub const __USE_ATFILE: u32 = 1;
pub const __USE_DYNAMIC_STACK_SIZE: u32 = 1;
pub const __USE_GNU: u32 = 1;
pub const __USE_FORTIFY_LEVEL: u32 = 0;
pub const __GLIBC_USE_DEPRECATED_GETS: u32 = 0;
pub const __GLIBC_USE_DEPRECATED_SCANF: u32 = 0;
pub const __GLIBC_USE_C23_STRTOL: u32 = 1;
pub const _STDC_PREDEF_H: u32 = 1;
pub const __STDC_IEC_559__: u32 = 1;
pub const __STDC_IEC_60559_BFP__: u32 = 201404;
pub const __STDC_IEC_559_COMPLEX__: u32 = 1;
pub const __STDC_IEC_60559_COMPLEX__: u32 = 201404;
pub const __STDC_ISO_10646__: u32 = 201706;
pub const __GNU_LIBRARY__: u32 = 6;
pub const __GLIBC__: u32 = 2;
pub const __GLIBC_MINOR__: u32 = 43;
pub const _SYS_CDEFS_H: u32 = 1;
pub const __glibc_c99_flexarr_available: u32 = 1;
pub const __LDOUBLE_REDIRECTS_TO_FLOAT128_ABI: u32 = 0;
pub const __HAVE_GENERIC_SELECTION: u32 = 1;
pub const __GLIBC_USE_LIB_EXT2: u32 = 1;
pub const __GLIBC_USE_IEC_60559_BFP_EXT: u32 = 1;
pub const __GLIBC_USE_IEC_60559_BFP_EXT_C23: u32 = 1;
pub const __GLIBC_USE_IEC_60559_EXT: u32 = 1;
pub const __GLIBC_USE_IEC_60559_FUNCS_EXT: u32 = 1;
pub const __GLIBC_USE_IEC_60559_FUNCS_EXT_C23: u32 = 1;
pub const __GLIBC_USE_IEC_60559_TYPES_EXT: u32 = 1;
pub const _BITS_TYPES_H: u32 = 1;
pub const _BITS_TYPESIZES_H: u32 = 1;
pub const __OFF_T_MATCHES_OFF64_T: u32 = 1;
pub const __INO_T_MATCHES_INO64_T: u32 = 1;
pub const __RLIM_T_MATCHES_RLIM64_T: u32 = 1;
pub const __STATFS_MATCHES_STATFS64: u32 = 1;
pub const __KERNEL_OLD_TIMEVAL_MATCHES_TIMEVAL64: u32 = 1;
pub const __FD_SETSIZE: u32 = 1024;
pub const _BITS_TIME64_H: u32 = 1;
pub const _BITS_WCHAR_H: u32 = 1;
pub const __STDC_VERSION_STDINT_H__: u32 = 202311;
pub const _BITS_STDINT_INTN_H: u32 = 1;
pub const _BITS_STDINT_UINTN_H: u32 = 1;
pub const _BITS_STDINT_LEAST_H: u32 = 1;
pub const INT8_MIN: i32 = -128;
pub const INT16_MIN: i32 = -32768;
pub const INT32_MIN: i32 = -2147483648;
pub const INT8_MAX: u32 = 127;
pub const INT16_MAX: u32 = 32767;
pub const INT32_MAX: u32 = 2147483647;
pub const UINT8_MAX: u32 = 255;
pub const UINT16_MAX: u32 = 65535;
pub const UINT32_MAX: u32 = 4294967295;
pub const INT_LEAST8_MIN: i32 = -128;
pub const INT_LEAST16_MIN: i32 = -32768;
pub const INT_LEAST32_MIN: i32 = -2147483648;
pub const INT_LEAST8_MAX: u32 = 127;
pub const INT_LEAST16_MAX: u32 = 32767;
pub const INT_LEAST32_MAX: u32 = 2147483647;
pub const UINT_LEAST8_MAX: u32 = 255;
pub const UINT_LEAST16_MAX: u32 = 65535;
pub const UINT_LEAST32_MAX: u32 = 4294967295;
pub const INT_FAST8_MIN: i32 = -128;
pub const INT_FAST16_MIN: i64 = -9223372036854775808;
pub const INT_FAST32_MIN: i64 = -9223372036854775808;
pub const INT_FAST8_MAX: u32 = 127;
pub const INT_FAST16_MAX: u64 = 9223372036854775807;
pub const INT_FAST32_MAX: u64 = 9223372036854775807;
pub const UINT_FAST8_MAX: u32 = 255;
pub const UINT_FAST16_MAX: i32 = -1;
pub const UINT_FAST32_MAX: i32 = -1;
pub const INTPTR_MIN: i64 = -9223372036854775808;
pub const INTPTR_MAX: u64 = 9223372036854775807;
pub const UINTPTR_MAX: i32 = -1;
pub const PTRDIFF_MIN: i64 = -9223372036854775808;
pub const PTRDIFF_MAX: u64 = 9223372036854775807;
pub const SIG_ATOMIC_MIN: i32 = -2147483648;
pub const SIG_ATOMIC_MAX: u32 = 2147483647;
pub const SIZE_MAX: i32 = -1;
pub const WINT_MIN: u32 = 0;
pub const WINT_MAX: u32 = 4294967295;
pub const INT8_WIDTH: u32 = 8;
pub const UINT8_WIDTH: u32 = 8;
pub const INT16_WIDTH: u32 = 16;
pub const UINT16_WIDTH: u32 = 16;
pub const INT32_WIDTH: u32 = 32;
pub const UINT32_WIDTH: u32 = 32;
pub const INT64_WIDTH: u32 = 64;
pub const UINT64_WIDTH: u32 = 64;
pub const INT_LEAST8_WIDTH: u32 = 8;
pub const UINT_LEAST8_WIDTH: u32 = 8;
pub const INT_LEAST16_WIDTH: u32 = 16;
pub const UINT_LEAST16_WIDTH: u32 = 16;
pub const INT_LEAST32_WIDTH: u32 = 32;
pub const UINT_LEAST32_WIDTH: u32 = 32;
pub const INT_LEAST64_WIDTH: u32 = 64;
pub const UINT_LEAST64_WIDTH: u32 = 64;
pub const INT_FAST8_WIDTH: u32 = 8;
pub const UINT_FAST8_WIDTH: u32 = 8;
pub const INT_FAST16_WIDTH: u32 = 64;
pub const UINT_FAST16_WIDTH: u32 = 64;
pub const INT_FAST32_WIDTH: u32 = 64;
pub const UINT_FAST32_WIDTH: u32 = 64;
pub const INT_FAST64_WIDTH: u32 = 64;
pub const UINT_FAST64_WIDTH: u32 = 64;
pub const INTPTR_WIDTH: u32 = 64;
pub const UINTPTR_WIDTH: u32 = 64;
pub const INTMAX_WIDTH: u32 = 64;
pub const UINTMAX_WIDTH: u32 = 64;
pub const PTRDIFF_WIDTH: u32 = 64;
pub const SIG_ATOMIC_WIDTH: u32 = 32;
pub const SIZE_WIDTH: u32 = 64;
pub const WCHAR_WIDTH: u32 = 32;
pub const WINT_WIDTH: u32 = 32;
pub const __bool_true_false_are_defined: u32 = 1;
pub const true_: u32 = 1;
pub const false_: u32 = 0;
pub const VIRGL_MAJOR_VERSION: u32 = 1;
pub const VIRGL_MINOR_VERSION: u32 = 3;
pub const VIRGL_MICRO_VERSION: u32 = 0;
pub const VIRGL_RENDERER_CALLBACKS_VERSION: u32 = 4;
pub const VIRGL_RENDERER_USE_EGL: u32 = 1;
pub const VIRGL_RENDERER_THREAD_SYNC: u32 = 2;
pub const VIRGL_RENDERER_USE_GLX: u32 = 4;
pub const VIRGL_RENDERER_USE_SURFACELESS: u32 = 8;
pub const VIRGL_RENDERER_USE_GLES: u32 = 16;
pub const VIRGL_RENDERER_USE_EXTERNAL_BLOB: u32 = 32;
pub const VIRGL_RENDERER_VENUS: u32 = 64;
pub const VIRGL_RENDERER_NO_VIRGL: u32 = 128;
pub const VIRGL_RENDERER_ASYNC_FENCE_CB: u32 = 256;
pub const VIRGL_RENDERER_RENDER_SERVER: u32 = 512;
pub const VIRGL_RENDERER_DRM: u32 = 1024;
pub const VIRGL_RENDERER_USE_VIDEO: u32 = 2048;
pub const VIRGL_RENDERER_D3D11_SHARE_TEXTURE: u32 = 4096;
pub const VIRGL_RENDERER_COMPAT_PROFILE: u32 = 8192;
pub const VIRGL_RENDERER_USE_GUEST_VRAM: u32 = 16384;
pub const VIRGL_RES_BIND_DEPTH_STENCIL: u32 = 1;
pub const VIRGL_RES_BIND_RENDER_TARGET: u32 = 2;
pub const VIRGL_RES_BIND_SAMPLER_VIEW: u32 = 8;
pub const VIRGL_RES_BIND_VERTEX_BUFFER: u32 = 16;
pub const VIRGL_RES_BIND_INDEX_BUFFER: u32 = 32;
pub const VIRGL_RES_BIND_CONSTANT_BUFFER: u32 = 64;
pub const VIRGL_RES_BIND_STREAM_OUTPUT: u32 = 2048;
pub const VIRGL_RES_BIND_CURSOR: u32 = 65536;
pub const VIRGL_RES_BIND_CUSTOM: u32 = 131072;
pub const VIRGL_RES_BIND_SCANOUT: u32 = 262144;
pub const VIRGL_RES_BIND_SHARED: u32 = 1048576;
pub const VIRGL_RENDERER_RESOURCE_INFO_EXT_VERSION: u32 = 0;
pub const VIRGL_RENDERER_CONTEXT_FLAG_CAPSET_ID_MASK: u32 = 255;
pub const VIRGL_RENDERER_BLOB_MEM_GUEST: u32 = 1;
pub const VIRGL_RENDERER_BLOB_MEM_HOST3D: u32 = 2;
pub const VIRGL_RENDERER_BLOB_MEM_HOST3D_GUEST: u32 = 3;
pub const VIRGL_RENDERER_BLOB_MEM_GUEST_VRAM: u32 = 4;
pub const VIRGL_RENDERER_BLOB_FLAG_USE_MAPPABLE: u32 = 1;
pub const VIRGL_RENDERER_BLOB_FLAG_USE_SHAREABLE: u32 = 2;
pub const VIRGL_RENDERER_BLOB_FLAG_USE_CROSS_DEVICE: u32 = 4;
pub const VIRGL_RENDERER_MAP_CACHE_MASK: u32 = 15;
pub const VIRGL_RENDERER_MAP_CACHE_NONE: u32 = 0;
pub const VIRGL_RENDERER_MAP_CACHE_CACHED: u32 = 1;
pub const VIRGL_RENDERER_MAP_CACHE_UNCACHED: u32 = 2;
pub const VIRGL_RENDERER_MAP_CACHE_WC: u32 = 3;
pub const VIRGL_RENDERER_BLOB_FD_TYPE_DMABUF: u32 = 1;
pub const VIRGL_RENDERER_BLOB_FD_TYPE_OPAQUE: u32 = 2;
pub const VIRGL_RENDERER_BLOB_FD_TYPE_SHM: u32 = 3;
pub const VIRGL_RENDERER_FENCE_FLAG_MERGEABLE: u32 = 1;
pub const _ERRNO_H: u32 = 1;
pub const _BITS_ERRNO_H: u32 = 1;
pub const EPERM: u32 = 1;
pub const ENOENT: u32 = 2;
pub const ESRCH: u32 = 3;
pub const EINTR: u32 = 4;
pub const EIO: u32 = 5;
pub const ENXIO: u32 = 6;
pub const E2BIG: u32 = 7;
pub const ENOEXEC: u32 = 8;
pub const EBADF: u32 = 9;
pub const ECHILD: u32 = 10;
pub const EAGAIN: u32 = 11;
pub const ENOMEM: u32 = 12;
pub const EACCES: u32 = 13;
pub const EFAULT: u32 = 14;
pub const ENOTBLK: u32 = 15;
pub const EBUSY: u32 = 16;
pub const EEXIST: u32 = 17;
pub const EXDEV: u32 = 18;
pub const ENODEV: u32 = 19;
pub const ENOTDIR: u32 = 20;
pub const EISDIR: u32 = 21;
pub const EINVAL: u32 = 22;
pub const ENFILE: u32 = 23;
pub const EMFILE: u32 = 24;
pub const ENOTTY: u32 = 25;
pub const ETXTBSY: u32 = 26;
pub const EFBIG: u32 = 27;
pub const ENOSPC: u32 = 28;
pub const ESPIPE: u32 = 29;
pub const EROFS: u32 = 30;
pub const EMLINK: u32 = 31;
pub const EPIPE: u32 = 32;
pub const EDOM: u32 = 33;
pub const ERANGE: u32 = 34;
pub const EDEADLK: u32 = 35;
pub const ENAMETOOLONG: u32 = 36;
pub const ENOLCK: u32 = 37;
pub const ENOSYS: u32 = 38;
pub const ENOTEMPTY: u32 = 39;
pub const ELOOP: u32 = 40;
pub const EWOULDBLOCK: u32 = 11;
pub const ENOMSG: u32 = 42;
pub const EIDRM: u32 = 43;
pub const ECHRNG: u32 = 44;
pub const EL2NSYNC: u32 = 45;
pub const EL3HLT: u32 = 46;
pub const EL3RST: u32 = 47;
pub const ELNRNG: u32 = 48;
pub const EUNATCH: u32 = 49;
pub const ENOCSI: u32 = 50;
pub const EL2HLT: u32 = 51;
pub const EBADE: u32 = 52;
pub const EBADR: u32 = 53;
pub const EXFULL: u32 = 54;
pub const ENOANO: u32 = 55;
pub const EBADRQC: u32 = 56;
pub const EBADSLT: u32 = 57;
pub const EDEADLOCK: u32 = 35;
pub const EBFONT: u32 = 59;
pub const ENOSTR: u32 = 60;
pub const ENODATA: u32 = 61;
pub const ETIME: u32 = 62;
pub const ENOSR: u32 = 63;
pub const ENONET: u32 = 64;
pub const ENOPKG: u32 = 65;
pub const EREMOTE: u32 = 66;
pub const ENOLINK: u32 = 67;
pub const EADV: u32 = 68;
pub const ESRMNT: u32 = 69;
pub const ECOMM: u32 = 70;
pub const EPROTO: u32 = 71;
pub const EMULTIHOP: u32 = 72;
pub const EDOTDOT: u32 = 73;
pub const EBADMSG: u32 = 74;
pub const EFSBADCRC: u32 = 74;
pub const EOVERFLOW: u32 = 75;
pub const ENOTUNIQ: u32 = 76;
pub const EBADFD: u32 = 77;
pub const EREMCHG: u32 = 78;
pub const ELIBACC: u32 = 79;
pub const ELIBBAD: u32 = 80;
pub const ELIBSCN: u32 = 81;
pub const ELIBMAX: u32 = 82;
pub const ELIBEXEC: u32 = 83;
pub const EILSEQ: u32 = 84;
pub const ERESTART: u32 = 85;
pub const ESTRPIPE: u32 = 86;
pub const EUSERS: u32 = 87;
pub const ENOTSOCK: u32 = 88;
pub const EDESTADDRREQ: u32 = 89;
pub const EMSGSIZE: u32 = 90;
pub const EPROTOTYPE: u32 = 91;
pub const ENOPROTOOPT: u32 = 92;
pub const EPROTONOSUPPORT: u32 = 93;
pub const ESOCKTNOSUPPORT: u32 = 94;
pub const EOPNOTSUPP: u32 = 95;
pub const EPFNOSUPPORT: u32 = 96;
pub const EAFNOSUPPORT: u32 = 97;
pub const EADDRINUSE: u32 = 98;
pub const EADDRNOTAVAIL: u32 = 99;
pub const ENETDOWN: u32 = 100;
pub const ENETUNREACH: u32 = 101;
pub const ENETRESET: u32 = 102;
pub const ECONNABORTED: u32 = 103;
pub const ECONNRESET: u32 = 104;
pub const ENOBUFS: u32 = 105;
pub const EISCONN: u32 = 106;
pub const ENOTCONN: u32 = 107;
pub const ESHUTDOWN: u32 = 108;
pub const ETOOMANYREFS: u32 = 109;
pub const ETIMEDOUT: u32 = 110;
pub const ECONNREFUSED: u32 = 111;
pub const EHOSTDOWN: u32 = 112;
pub const EHOSTUNREACH: u32 = 113;
pub const EALREADY: u32 = 114;
pub const EINPROGRESS: u32 = 115;
pub const ESTALE: u32 = 116;
pub const EUCLEAN: u32 = 117;
pub const EFSCORRUPTED: u32 = 117;
pub const ENOTNAM: u32 = 118;
pub const ENAVAIL: u32 = 119;
pub const EISNAM: u32 = 120;
pub const EREMOTEIO: u32 = 121;
pub const EDQUOT: u32 = 122;
pub const ENOMEDIUM: u32 = 123;
pub const EMEDIUMTYPE: u32 = 124;
pub const ECANCELED: u32 = 125;
pub const ENOKEY: u32 = 126;
pub const EKEYEXPIRED: u32 = 127;
pub const EKEYREVOKED: u32 = 128;
pub const EKEYREJECTED: u32 = 129;
pub const EOWNERDEAD: u32 = 130;
pub const ENOTRECOVERABLE: u32 = 131;
pub const ERFKILL: u32 = 132;
pub const EHWPOISON: u32 = 133;
pub const ENOTSUP: u32 = 95;
pub const __error_t_defined: u32 = 1;
pub type __u_char = ::std::os::raw::c_uchar;
pub type __u_short = ::std::os::raw::c_ushort;
pub type __u_int = ::std::os::raw::c_uint;
pub type __u_long = ::std::os::raw::c_ulong;
pub type __int8_t = ::std::os::raw::c_schar;
pub type __uint8_t = ::std::os::raw::c_uchar;
pub type __int16_t = ::std::os::raw::c_short;
pub type __uint16_t = ::std::os::raw::c_ushort;
pub type __int32_t = ::std::os::raw::c_int;
pub type __uint32_t = ::std::os::raw::c_uint;
pub type __int64_t = ::std::os::raw::c_long;
pub type __uint64_t = ::std::os::raw::c_ulong;
pub type __int_least8_t = __int8_t;
pub type __uint_least8_t = __uint8_t;
pub type __int_least16_t = __int16_t;
pub type __uint_least16_t = __uint16_t;
pub type __int_least32_t = __int32_t;
pub type __uint_least32_t = __uint32_t;
pub type __int_least64_t = __int64_t;
pub type __uint_least64_t = __uint64_t;
pub type __quad_t = ::std::os::raw::c_long;
pub type __u_quad_t = ::std::os::raw::c_ulong;
pub type __intmax_t = ::std::os::raw::c_long;
pub type __uintmax_t = ::std::os::raw::c_ulong;
pub type __dev_t = ::std::os::raw::c_ulong;
pub type __uid_t = ::std::os::raw::c_uint;
pub type __gid_t = ::std::os::raw::c_uint;
pub type __ino_t = ::std::os::raw::c_ulong;
pub type __ino64_t = ::std::os::raw::c_ulong;
pub type __mode_t = ::std::os::raw::c_uint;
pub type __nlink_t = ::std::os::raw::c_ulong;
pub type __off_t = ::std::os::raw::c_long;
pub type __off64_t = ::std::os::raw::c_long;
pub type __pid_t = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __fsid_t {
    pub __val: [::std::os::raw::c_int; 2usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __fsid_t"][::std::mem::size_of::<__fsid_t>() - 8usize];
    ["Alignment of __fsid_t"][::std::mem::align_of::<__fsid_t>() - 4usize];
    ["Offset of field: __fsid_t::__val"][::std::mem::offset_of!(__fsid_t, __val) - 0usize];
};
pub type __clock_t = ::std::os::raw::c_long;
pub type __rlim_t = ::std::os::raw::c_ulong;
pub type __rlim64_t = ::std::os::raw::c_ulong;
pub type __id_t = ::std::os::raw::c_uint;
pub type __time_t = ::std::os::raw::c_long;
pub type __useconds_t = ::std::os::raw::c_uint;
pub type __suseconds_t = ::std::os::raw::c_long;
pub type __suseconds64_t = ::std::os::raw::c_long;
pub type __daddr_t = ::std::os::raw::c_int;
pub type __key_t = ::std::os::raw::c_int;
pub type __clockid_t = ::std::os::raw::c_int;
pub type __timer_t = *mut ::std::os::raw::c_void;
pub type __blksize_t = ::std::os::raw::c_long;
pub type __blkcnt_t = ::std::os::raw::c_long;
pub type __blkcnt64_t = ::std::os::raw::c_long;
pub type __fsblkcnt_t = ::std::os::raw::c_ulong;
pub type __fsblkcnt64_t = ::std::os::raw::c_ulong;
pub type __fsfilcnt_t = ::std::os::raw::c_ulong;
pub type __fsfilcnt64_t = ::std::os::raw::c_ulong;
pub type __fsword_t = ::std::os::raw::c_long;
pub type __ssize_t = ::std::os::raw::c_long;
pub type __syscall_slong_t = ::std::os::raw::c_long;
pub type __syscall_ulong_t = ::std::os::raw::c_ulong;
pub type __loff_t = __off64_t;
pub type __caddr_t = *mut ::std::os::raw::c_char;
pub type __intptr_t = ::std::os::raw::c_long;
pub type __socklen_t = ::std::os::raw::c_uint;
pub type __sig_atomic_t = ::std::os::raw::c_int;
pub type int_least8_t = __int_least8_t;
pub type int_least16_t = __int_least16_t;
pub type int_least32_t = __int_least32_t;
pub type int_least64_t = __int_least64_t;
pub type uint_least8_t = __uint_least8_t;
pub type uint_least16_t = __uint_least16_t;
pub type uint_least32_t = __uint_least32_t;
pub type uint_least64_t = __uint_least64_t;
pub type int_fast8_t = ::std::os::raw::c_schar;
pub type int_fast16_t = ::std::os::raw::c_long;
pub type int_fast32_t = ::std::os::raw::c_long;
pub type int_fast64_t = ::std::os::raw::c_long;
pub type uint_fast8_t = ::std::os::raw::c_uchar;
pub type uint_fast16_t = ::std::os::raw::c_ulong;
pub type uint_fast32_t = ::std::os::raw::c_ulong;
pub type uint_fast64_t = ::std::os::raw::c_ulong;
pub type intmax_t = __intmax_t;
pub type uintmax_t = __uintmax_t;
pub type __gnuc_va_list = __builtin_va_list;
pub type va_list = __builtin_va_list;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct virgl_box {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct iovec {
    _unused: [u8; 0],
}
pub type virgl_renderer_gl_context = *mut ::std::os::raw::c_void;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct virgl_renderer_gl_ctx_param {
    pub version: ::std::os::raw::c_int,
    pub shared: bool,
    pub major_ver: ::std::os::raw::c_int,
    pub minor_ver: ::std::os::raw::c_int,
    pub compat_ctx: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of virgl_renderer_gl_ctx_param"]
        [::std::mem::size_of::<virgl_renderer_gl_ctx_param>() - 20usize];
    ["Alignment of virgl_renderer_gl_ctx_param"]
        [::std::mem::align_of::<virgl_renderer_gl_ctx_param>() - 4usize];
    ["Offset of field: virgl_renderer_gl_ctx_param::version"]
        [::std::mem::offset_of!(virgl_renderer_gl_ctx_param, version) - 0usize];
    ["Offset of field: virgl_renderer_gl_ctx_param::shared"]
        [::std::mem::offset_of!(virgl_renderer_gl_ctx_param, shared) - 4usize];
    ["Offset of field: virgl_renderer_gl_ctx_param::major_ver"]
        [::std::mem::offset_of!(virgl_renderer_gl_ctx_param, major_ver) - 8usize];
    ["Offset of field: virgl_renderer_gl_ctx_param::minor_ver"]
        [::std::mem::offset_of!(virgl_renderer_gl_ctx_param, minor_ver) - 12usize];
    ["Offset of field: virgl_renderer_gl_ctx_param::compat_ctx"]
        [::std::mem::offset_of!(virgl_renderer_gl_ctx_param, compat_ctx) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct virgl_renderer_callbacks {
    pub version: ::std::os::raw::c_int,
    pub write_fence: ::std::option::Option<
        unsafe extern "C" fn(cookie: *mut ::std::os::raw::c_void, fence: u32),
    >,
    pub create_gl_context: ::std::option::Option<
        unsafe extern "C" fn(
            cookie: *mut ::std::os::raw::c_void,
            scanout_idx: ::std::os::raw::c_int,
            param: *mut virgl_renderer_gl_ctx_param,
        ) -> virgl_renderer_gl_context,
    >,
    pub destroy_gl_context: ::std::option::Option<
        unsafe extern "C" fn(cookie: *mut ::std::os::raw::c_void, ctx: virgl_renderer_gl_context),
    >,
    pub make_current: ::std::option::Option<
        unsafe extern "C" fn(
            cookie: *mut ::std::os::raw::c_void,
            scanout_idx: ::std::os::raw::c_int,
            ctx: virgl_renderer_gl_context,
        ) -> ::std::os::raw::c_int,
    >,
    pub get_drm_fd: ::std::option::Option<
        unsafe extern "C" fn(cookie: *mut ::std::os::raw::c_void) -> ::std::os::raw::c_int,
    >,
    pub write_context_fence: ::std::option::Option<
        unsafe extern "C" fn(
            cookie: *mut ::std::os::raw::c_void,
            ctx_id: u32,
            ring_idx: u32,
            fence_id: u64,
        ),
    >,
    pub get_server_fd: ::std::option::Option<
        unsafe extern "C" fn(
            cookie: *mut ::std::os::raw::c_void,
            version: u32,
        ) -> ::std::os::raw::c_int,
    >,
    pub get_egl_display: ::std::option::Option<
        unsafe extern "C" fn(cookie: *mut ::std::os::raw::c_void) -> *mut ::std::os::raw::c_void,
    >,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of virgl_renderer_callbacks"]
        [::std::mem::size_of::<virgl_renderer_callbacks>() - 72usize];
    ["Alignment of virgl_renderer_callbacks"]
        [::std::mem::align_of::<virgl_renderer_callbacks>() - 8usize];
    ["Offset of field: virgl_renderer_callbacks::version"]
        [::std::mem::offset_of!(virgl_renderer_callbacks, version) - 0usize];
    ["Offset of field: virgl_renderer_callbacks::write_fence"]
        [::std::mem::offset_of!(virgl_renderer_callbacks, write_fence) - 8usize];
    ["Offset of field: virgl_renderer_callbacks::create_gl_context"]
        [::std::mem::offset_of!(virgl_renderer_callbacks, create_gl_context) - 16usize];
    ["Offset of field: virgl_renderer_callbacks::destroy_gl_context"]
        [::std::mem::offset_of!(virgl_renderer_callbacks, destroy_gl_context) - 24usize];
    ["Offset of field: virgl_renderer_callbacks::make_current"]
        [::std::mem::offset_of!(virgl_renderer_callbacks, make_current) - 32usize];
    ["Offset of field: virgl_renderer_callbacks::get_drm_fd"]
        [::std::mem::offset_of!(virgl_renderer_callbacks, get_drm_fd) - 40usize];
    ["Offset of field: virgl_renderer_callbacks::write_context_fence"]
        [::std::mem::offset_of!(virgl_renderer_callbacks, write_context_fence) - 48usize];
    ["Offset of field: virgl_renderer_callbacks::get_server_fd"]
        [::std::mem::offset_of!(virgl_renderer_callbacks, get_server_fd) - 56usize];
    ["Offset of field: virgl_renderer_callbacks::get_egl_display"]
        [::std::mem::offset_of!(virgl_renderer_callbacks, get_egl_display) - 64usize];
};
unsafe extern "C" {
    pub fn virgl_renderer_init(
        cookie: *mut ::std::os::raw::c_void,
        flags: ::std::os::raw::c_int,
        cb: *mut virgl_renderer_callbacks,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn virgl_renderer_poll();
}
unsafe extern "C" {
    pub fn virgl_renderer_get_cursor_data(
        resource_id: u32,
        width: *mut u32,
        height: *mut u32,
    ) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn virgl_renderer_get_rect(
        resource_id: ::std::os::raw::c_int,
        iov: *mut iovec,
        num_iovs: ::std::os::raw::c_uint,
        offset: u32,
        x: ::std::os::raw::c_int,
        y: ::std::os::raw::c_int,
        width: ::std::os::raw::c_int,
        height: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn virgl_renderer_get_fd_for_texture(
        tex_id: u32,
        fd: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn virgl_renderer_get_fd_for_texture2(
        tex_id: u32,
        fd: *mut ::std::os::raw::c_int,
        stride: *mut ::std::os::raw::c_int,
        offset: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
pub const virgl_renderer_structure_type_v0_VIRGL_RENDERER_STRUCTURE_TYPE_NONE:
    virgl_renderer_structure_type_v0 = 0;
pub const virgl_renderer_structure_type_v0_VIRGL_RENDERER_STRUCTURE_TYPE_EXPORT_QUERY:
    virgl_renderer_structure_type_v0 = 1;
pub const virgl_renderer_structure_type_v0_VIRGL_RENDERER_STRUCTURE_TYPE_SUPPORTED_STRUCTURES:
    virgl_renderer_structure_type_v0 = 2;
pub type virgl_renderer_structure_type_v0 = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct virgl_renderer_resource_create_args {
    pub handle: u32,
    pub target: u32,
    pub format: u32,
    pub bind: u32,
    pub width: u32,
    pub height: u32,
    pub depth: u32,
    pub array_size: u32,
    pub last_level: u32,
    pub nr_samples: u32,
    pub flags: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of virgl_renderer_resource_create_args"]
        [::std::mem::size_of::<virgl_renderer_resource_create_args>() - 44usize];
    ["Alignment of virgl_renderer_resource_create_args"]
        [::std::mem::align_of::<virgl_renderer_resource_create_args>() - 4usize];
    ["Offset of field: virgl_renderer_resource_create_args::handle"]
        [::std::mem::offset_of!(virgl_renderer_resource_create_args, handle) - 0usize];
    ["Offset of field: virgl_renderer_resource_create_args::target"]
        [::std::mem::offset_of!(virgl_renderer_resource_create_args, target) - 4usize];
    ["Offset of field: virgl_renderer_resource_create_args::format"]
        [::std::mem::offset_of!(virgl_renderer_resource_create_args, format) - 8usize];
    ["Offset of field: virgl_renderer_resource_create_args::bind"]
        [::std::mem::offset_of!(virgl_renderer_resource_create_args, bind) - 12usize];
    ["Offset of field: virgl_renderer_resource_create_args::width"]
        [::std::mem::offset_of!(virgl_renderer_resource_create_args, width) - 16usize];
    ["Offset of field: virgl_renderer_resource_create_args::height"]
        [::std::mem::offset_of!(virgl_renderer_resource_create_args, height) - 20usize];
    ["Offset of field: virgl_renderer_resource_create_args::depth"]
        [::std::mem::offset_of!(virgl_renderer_resource_create_args, depth) - 24usize];
    ["Offset of field: virgl_renderer_resource_create_args::array_size"]
        [::std::mem::offset_of!(virgl_renderer_resource_create_args, array_size) - 28usize];
    ["Offset of field: virgl_renderer_resource_create_args::last_level"]
        [::std::mem::offset_of!(virgl_renderer_resource_create_args, last_level) - 32usize];
    ["Offset of field: virgl_renderer_resource_create_args::nr_samples"]
        [::std::mem::offset_of!(virgl_renderer_resource_create_args, nr_samples) - 36usize];
    ["Offset of field: virgl_renderer_resource_create_args::flags"]
        [::std::mem::offset_of!(virgl_renderer_resource_create_args, flags) - 40usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct virgl_renderer_hdr {
    pub stype: u32,
    pub stype_version: u32,
    pub size: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of virgl_renderer_hdr"][::std::mem::size_of::<virgl_renderer_hdr>() - 12usize];
    ["Alignment of virgl_renderer_hdr"][::std::mem::align_of::<virgl_renderer_hdr>() - 4usize];
    ["Offset of field: virgl_renderer_hdr::stype"]
        [::std::mem::offset_of!(virgl_renderer_hdr, stype) - 0usize];
    ["Offset of field: virgl_renderer_hdr::stype_version"]
        [::std::mem::offset_of!(virgl_renderer_hdr, stype_version) - 4usize];
    ["Offset of field: virgl_renderer_hdr::size"]
        [::std::mem::offset_of!(virgl_renderer_hdr, size) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct virgl_renderer_export_query {
    pub hdr: virgl_renderer_hdr,
    pub in_resource_id: u32,
    pub out_num_fds: u32,
    pub in_export_fds: u32,
    pub out_fourcc: u32,
    pub pad: u32,
    pub out_fds: [i32; 4usize],
    pub out_strides: [u32; 4usize],
    pub out_offsets: [u32; 4usize],
    pub out_modifier: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of virgl_renderer_export_query"]
        [::std::mem::size_of::<virgl_renderer_export_query>() - 88usize];
    ["Alignment of virgl_renderer_export_query"]
        [::std::mem::align_of::<virgl_renderer_export_query>() - 8usize];
    ["Offset of field: virgl_renderer_export_query::hdr"]
        [::std::mem::offset_of!(virgl_renderer_export_query, hdr) - 0usize];
    ["Offset of field: virgl_renderer_export_query::in_resource_id"]
        [::std::mem::offset_of!(virgl_renderer_export_query, in_resource_id) - 12usize];
    ["Offset of field: virgl_renderer_export_query::out_num_fds"]
        [::std::mem::offset_of!(virgl_renderer_export_query, out_num_fds) - 16usize];
    ["Offset of field: virgl_renderer_export_query::in_export_fds"]
        [::std::mem::offset_of!(virgl_renderer_export_query, in_export_fds) - 20usize];
    ["Offset of field: virgl_renderer_export_query::out_fourcc"]
        [::std::mem::offset_of!(virgl_renderer_export_query, out_fourcc) - 24usize];
    ["Offset of field: virgl_renderer_export_query::pad"]
        [::std::mem::offset_of!(virgl_renderer_export_query, pad) - 28usize];
    ["Offset of field: virgl_renderer_export_query::out_fds"]
        [::std::mem::offset_of!(virgl_renderer_export_query, out_fds) - 32usize];
    ["Offset of field: virgl_renderer_export_query::out_strides"]
        [::std::mem::offset_of!(virgl_renderer_export_query, out_strides) - 48usize];
    ["Offset of field: virgl_renderer_export_query::out_offsets"]
        [::std::mem::offset_of!(virgl_renderer_export_query, out_offsets) - 64usize];
    ["Offset of field: virgl_renderer_export_query::out_modifier"]
        [::std::mem::offset_of!(virgl_renderer_export_query, out_modifier) - 80usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct virgl_renderer_supported_structures {
    pub hdr: virgl_renderer_hdr,
    pub in_stype_version: u32,
    pub out_supported_structures_mask: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of virgl_renderer_supported_structures"]
        [::std::mem::size_of::<virgl_renderer_supported_structures>() - 20usize];
    ["Alignment of virgl_renderer_supported_structures"]
        [::std::mem::align_of::<virgl_renderer_supported_structures>() - 4usize];
    ["Offset of field: virgl_renderer_supported_structures::hdr"]
        [::std::mem::offset_of!(virgl_renderer_supported_structures, hdr) - 0usize];
    ["Offset of field: virgl_renderer_supported_structures::in_stype_version"]
        [::std::mem::offset_of!(virgl_renderer_supported_structures, in_stype_version) - 12usize];
    ["Offset of field: virgl_renderer_supported_structures::out_supported_structures_mask"][::std::mem::offset_of!(
        virgl_renderer_supported_structures,
        out_supported_structures_mask
    )
        - 16usize];
};
pub type virgl_debug_callback_type = ::std::option::Option<
    unsafe extern "C" fn(fmt: *const ::std::os::raw::c_char, ap: *mut __va_list_tag),
>;
pub const virgl_log_level_flags_VIRGL_LOG_LEVEL_DEBUG: virgl_log_level_flags = 0;
pub const virgl_log_level_flags_VIRGL_LOG_LEVEL_INFO: virgl_log_level_flags = 1;
pub const virgl_log_level_flags_VIRGL_LOG_LEVEL_WARNING: virgl_log_level_flags = 2;
pub const virgl_log_level_flags_VIRGL_LOG_LEVEL_ERROR: virgl_log_level_flags = 3;
pub const virgl_log_level_flags_VIRGL_LOG_LEVEL_SILENT: virgl_log_level_flags = 4;
pub type virgl_log_level_flags = ::std::os::raw::c_uint;
pub type virgl_free_data_callback_type =
    ::std::option::Option<unsafe extern "C" fn(user_data: *mut ::std::os::raw::c_void)>;
pub type virgl_log_callback_type = ::std::option::Option<
    unsafe extern "C" fn(
        log_level: virgl_log_level_flags,
        message: *const ::std::os::raw::c_char,
        user_data: *mut ::std::os::raw::c_void,
    ),
>;
unsafe extern "C" {
    pub fn virgl_renderer_resource_create(
        args: *mut virgl_renderer_resource_create_args,
        iov: *mut iovec,
        num_iovs: u32,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn virgl_renderer_resource_import_eglimage(
        args: *mut virgl_renderer_resource_create_args,
        image: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn virgl_renderer_resource_unref(res_handle: u32);
}
unsafe extern "C" {
    pub fn virgl_renderer_resource_set_priv(res_handle: u32, priv_: *mut ::std::os::raw::c_void);
}
unsafe extern "C" {
    pub fn virgl_renderer_resource_get_priv(res_handle: u32) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn virgl_renderer_context_create(
        handle: u32,
        nlen: u32,
        name: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn virgl_renderer_context_destroy(handle: u32);
}
unsafe extern "C" {
    pub fn virgl_renderer_submit_cmd(
        buffer: *mut ::std::os::raw::c_void,
        ctx_id: ::std::os::raw::c_int,
        ndw: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn virgl_renderer_transfer_read_iov(
        handle: u32,
        ctx_id: u32,
        level: u32,
        stride: u32,
        layer_stride: u32,
        box_: *mut virgl_box,
        offset: u64,
        iov: *mut iovec,
        iovec_cnt: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn virgl_renderer_transfer_write_iov(
        handle: u32,
        ctx_id: u32,
        level: ::std::os::raw::c_int,
        stride: u32,
        layer_stride: u32,
        box_: *mut virgl_box,
        offset: u64,
        iovec: *mut iovec,
        iovec_cnt: ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn virgl_renderer_get_cap_set(set: u32, max_ver: *mut u32, max_size: *mut u32);
}
unsafe extern "C" {
    pub fn virgl_renderer_fill_caps(set: u32, version: u32, caps: *mut ::std::os::raw::c_void);
}
unsafe extern "C" {
    pub fn virgl_renderer_resource_attach_iov(
        res_handle: ::std::os::raw::c_int,
        iov: *mut iovec,
        num_iovs: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn virgl_renderer_resource_detach_iov(
        res_handle: ::std::os::raw::c_int,
        iov: *mut *mut iovec,
        num_iovs: *mut ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn virgl_renderer_create_fence(
        client_fence_id: ::std::os::raw::c_int,
        ctx_id: u32,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn virgl_renderer_force_ctx_0();
}
unsafe extern "C" {
    pub fn virgl_renderer_ctx_attach_resource(
        ctx_id: ::std::os::raw::c_int,
        res_handle: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn virgl_renderer_ctx_detach_resource(
        ctx_id: ::std::os::raw::c_int,
        res_handle: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn virgl_set_debug_callback(cb: virgl_debug_callback_type) -> virgl_debug_callback_type;
}
unsafe extern "C" {
    pub fn virgl_set_log_callback(
        cb: virgl_log_callback_type,
        user_data: *mut ::std::os::raw::c_void,
        free_user_data_cb: virgl_free_data_callback_type,
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct virgl_renderer_resource_info {
    pub handle: u32,
    pub virgl_format: u32,
    pub width: u32,
    pub height: u32,
    pub depth: u32,
    pub flags: u32,
    pub tex_id: u32,
    pub stride: u32,
    pub drm_fourcc: ::std::os::raw::c_int,
    pub fd: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of virgl_renderer_resource_info"]
        [::std::mem::size_of::<virgl_renderer_resource_info>() - 40usize];
    ["Alignment of virgl_renderer_resource_info"]
        [::std::mem::align_of::<virgl_renderer_resource_info>() - 4usize];
    ["Offset of field: virgl_renderer_resource_info::handle"]
        [::std::mem::offset_of!(virgl_renderer_resource_info, handle) - 0usize];
    ["Offset of field: virgl_renderer_resource_info::virgl_format"]
        [::std::mem::offset_of!(virgl_renderer_resource_info, virgl_format) - 4usize];
    ["Offset of field: virgl_renderer_resource_info::width"]
        [::std::mem::offset_of!(virgl_renderer_resource_info, width) - 8usize];
    ["Offset of field: virgl_renderer_resource_info::height"]
        [::std::mem::offset_of!(virgl_renderer_resource_info, height) - 12usize];
    ["Offset of field: virgl_renderer_resource_info::depth"]
        [::std::mem::offset_of!(virgl_renderer_resource_info, depth) - 16usize];
    ["Offset of field: virgl_renderer_resource_info::flags"]
        [::std::mem::offset_of!(virgl_renderer_resource_info, flags) - 20usize];
    ["Offset of field: virgl_renderer_resource_info::tex_id"]
        [::std::mem::offset_of!(virgl_renderer_resource_info, tex_id) - 24usize];
    ["Offset of field: virgl_renderer_resource_info::stride"]
        [::std::mem::offset_of!(virgl_renderer_resource_info, stride) - 28usize];
    ["Offset of field: virgl_renderer_resource_info::drm_fourcc"]
        [::std::mem::offset_of!(virgl_renderer_resource_info, drm_fourcc) - 32usize];
    ["Offset of field: virgl_renderer_resource_info::fd"]
        [::std::mem::offset_of!(virgl_renderer_resource_info, fd) - 36usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct virgl_renderer_resource_info_ext {
    pub version: ::std::os::raw::c_int,
    pub base: virgl_renderer_resource_info,
    pub has_dmabuf_export: bool,
    pub planes: ::std::os::raw::c_int,
    pub modifiers: u64,
    pub d3d_tex2d: *mut ::std::os::raw::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of virgl_renderer_resource_info_ext"]
        [::std::mem::size_of::<virgl_renderer_resource_info_ext>() - 72usize];
    ["Alignment of virgl_renderer_resource_info_ext"]
        [::std::mem::align_of::<virgl_renderer_resource_info_ext>() - 8usize];
    ["Offset of field: virgl_renderer_resource_info_ext::version"]
        [::std::mem::offset_of!(virgl_renderer_resource_info_ext, version) - 0usize];
    ["Offset of field: virgl_renderer_resource_info_ext::base"]
        [::std::mem::offset_of!(virgl_renderer_resource_info_ext, base) - 4usize];
    ["Offset of field: virgl_renderer_resource_info_ext::has_dmabuf_export"]
        [::std::mem::offset_of!(virgl_renderer_resource_info_ext, has_dmabuf_export) - 44usize];
    ["Offset of field: virgl_renderer_resource_info_ext::planes"]
        [::std::mem::offset_of!(virgl_renderer_resource_info_ext, planes) - 48usize];
    ["Offset of field: virgl_renderer_resource_info_ext::modifiers"]
        [::std::mem::offset_of!(virgl_renderer_resource_info_ext, modifiers) - 56usize];
    ["Offset of field: virgl_renderer_resource_info_ext::d3d_tex2d"]
        [::std::mem::offset_of!(virgl_renderer_resource_info_ext, d3d_tex2d) - 64usize];
};
unsafe extern "C" {
    pub fn virgl_renderer_resource_get_info(
        res_handle: ::std::os::raw::c_int,
        info: *mut virgl_renderer_resource_info,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn virgl_renderer_resource_get_info_ext(
        res_handle: ::std::os::raw::c_int,
        info: *mut virgl_renderer_resource_info_ext,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn virgl_renderer_cleanup(cookie: *mut ::std::os::raw::c_void);
}
unsafe extern "C" {
    pub fn virgl_renderer_reset();
}
unsafe extern "C" {
    pub fn virgl_renderer_get_poll_fd() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn virgl_renderer_execute(
        execute_args: *mut ::std::os::raw::c_void,
        execute_size: u32,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn virgl_renderer_context_create_with_flags(
        ctx_id: u32,
        ctx_flags: u32,
        nlen: u32,
        name: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct virgl_renderer_resource_create_blob_args {
    pub res_handle: u32,
    pub ctx_id: u32,
    pub blob_mem: u32,
    pub blob_flags: u32,
    pub blob_id: u64,
    pub size: u64,
    pub iovecs: *const iovec,
    pub num_iovs: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of virgl_renderer_resource_create_blob_args"]
        [::std::mem::size_of::<virgl_renderer_resource_create_blob_args>() - 48usize];
    ["Alignment of virgl_renderer_resource_create_blob_args"]
        [::std::mem::align_of::<virgl_renderer_resource_create_blob_args>() - 8usize];
    ["Offset of field: virgl_renderer_resource_create_blob_args::res_handle"]
        [::std::mem::offset_of!(virgl_renderer_resource_create_blob_args, res_handle) - 0usize];
    ["Offset of field: virgl_renderer_resource_create_blob_args::ctx_id"]
        [::std::mem::offset_of!(virgl_renderer_resource_create_blob_args, ctx_id) - 4usize];
    ["Offset of field: virgl_renderer_resource_create_blob_args::blob_mem"]
        [::std::mem::offset_of!(virgl_renderer_resource_create_blob_args, blob_mem) - 8usize];
    ["Offset of field: virgl_renderer_resource_create_blob_args::blob_flags"]
        [::std::mem::offset_of!(virgl_renderer_resource_create_blob_args, blob_flags) - 12usize];
    ["Offset of field: virgl_renderer_resource_create_blob_args::blob_id"]
        [::std::mem::offset_of!(virgl_renderer_resource_create_blob_args, blob_id) - 16usize];
    ["Offset of field: virgl_renderer_resource_create_blob_args::size"]
        [::std::mem::offset_of!(virgl_renderer_resource_create_blob_args, size) - 24usize];
    ["Offset of field: virgl_renderer_resource_create_blob_args::iovecs"]
        [::std::mem::offset_of!(virgl_renderer_resource_create_blob_args, iovecs) - 32usize];
    ["Offset of field: virgl_renderer_resource_create_blob_args::num_iovs"]
        [::std::mem::offset_of!(virgl_renderer_resource_create_blob_args, num_iovs) - 40usize];
};
unsafe extern "C" {
    pub fn virgl_renderer_resource_create_blob(
        args: *const virgl_renderer_resource_create_blob_args,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn virgl_renderer_resource_map(
        res_handle: u32,
        map: *mut *mut ::std::os::raw::c_void,
        out_size: *mut u64,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn virgl_renderer_resource_unmap(res_handle: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn virgl_renderer_resource_get_map_info(
        res_handle: u32,
        map_info: *mut u32,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn virgl_renderer_resource_export_blob(
        res_id: u32,
        fd_type: *mut u32,
        fd: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct virgl_renderer_resource_import_blob_args {
    pub res_handle: u32,
    pub blob_mem: u32,
    pub fd_type: u32,
    pub fd: ::std::os::raw::c_int,
    pub size: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of virgl_renderer_resource_import_blob_args"]
        [::std::mem::size_of::<virgl_renderer_resource_import_blob_args>() - 24usize];
    ["Alignment of virgl_renderer_resource_import_blob_args"]
        [::std::mem::align_of::<virgl_renderer_resource_import_blob_args>() - 8usize];
    ["Offset of field: virgl_renderer_resource_import_blob_args::res_handle"]
        [::std::mem::offset_of!(virgl_renderer_resource_import_blob_args, res_handle) - 0usize];
    ["Offset of field: virgl_renderer_resource_import_blob_args::blob_mem"]
        [::std::mem::offset_of!(virgl_renderer_resource_import_blob_args, blob_mem) - 4usize];
    ["Offset of field: virgl_renderer_resource_import_blob_args::fd_type"]
        [::std::mem::offset_of!(virgl_renderer_resource_import_blob_args, fd_type) - 8usize];
    ["Offset of field: virgl_renderer_resource_import_blob_args::fd"]
        [::std::mem::offset_of!(virgl_renderer_resource_import_blob_args, fd) - 12usize];
    ["Offset of field: virgl_renderer_resource_import_blob_args::size"]
        [::std::mem::offset_of!(virgl_renderer_resource_import_blob_args, size) - 16usize];
};
unsafe extern "C" {
    pub fn virgl_renderer_resource_import_blob(
        args: *const virgl_renderer_resource_import_blob_args,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn virgl_renderer_context_create_fence(
        ctx_id: u32,
        flags: u32,
        ring_idx: u32,
        fence_id: u64,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn virgl_renderer_context_poll(ctx_id: u32);
}
unsafe extern "C" {
    pub fn virgl_renderer_context_get_poll_fd(ctx_id: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn virgl_renderer_resource_map_fixed(
        res_handle: u32,
        addr: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn virgl_renderer_export_fence(
        client_fence_id: u64,
        fd: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn virgl_renderer_export_signalled_fence() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn virgl_renderer_submit_cmd2(
        buffer: *mut ::std::os::raw::c_void,
        ctx_id: ::std::os::raw::c_int,
        ndw: ::std::os::raw::c_int,
        in_fence_ids: *mut u64,
        num_in_fences: u32,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn virgl_renderer_attach_fence(
        ctx_id: ::std::os::raw::c_int,
        fence_fd: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn virgl_renderer_get_fence_fd(fence_id: u64) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn virgl_renderer_get_dev_fd(ctx_id: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn __errno_location() -> *mut ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub static mut program_invocation_name: *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub static mut program_invocation_short_name: *mut ::std::os::raw::c_char;
}
pub type error_t = ::std::os::raw::c_int;
pub type wchar_t = ::std::os::raw::c_int;
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct max_align_t {
    pub __clang_max_align_nonce1: ::std::os::raw::c_longlong,
    pub __bindgen_padding_0: u64,
    pub __clang_max_align_nonce2: u128,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of max_align_t"][::std::mem::size_of::<max_align_t>() - 32usize];
    ["Alignment of max_align_t"][::std::mem::align_of::<max_align_t>() - 16usize];
    ["Offset of field: max_align_t::__clang_max_align_nonce1"]
        [::std::mem::offset_of!(max_align_t, __clang_max_align_nonce1) - 0usize];
    ["Offset of field: max_align_t::__clang_max_align_nonce2"]
        [::std::mem::offset_of!(max_align_t, __clang_max_align_nonce2) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vtest_context {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vtest_buffer {
    pub buffer: *const ::std::os::raw::c_char,
    pub size: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of vtest_buffer"][::std::mem::size_of::<vtest_buffer>() - 16usize];
    ["Alignment of vtest_buffer"][::std::mem::align_of::<vtest_buffer>() - 8usize];
    ["Offset of field: vtest_buffer::buffer"]
        [::std::mem::offset_of!(vtest_buffer, buffer) - 0usize];
    ["Offset of field: vtest_buffer::size"][::std::mem::offset_of!(vtest_buffer, size) - 8usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct vtest_input {
    pub data: vtest_input__bindgen_ty_1,
    pub read: ::std::option::Option<
        unsafe extern "C" fn(
            input: *mut vtest_input,
            buf: *mut ::std::os::raw::c_void,
            size: ::std::os::raw::c_int,
        ) -> ::std::os::raw::c_int,
    >,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union vtest_input__bindgen_ty_1 {
    pub fd: ::std::os::raw::c_int,
    pub buffer: *mut vtest_buffer,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of vtest_input__bindgen_ty_1"]
        [::std::mem::size_of::<vtest_input__bindgen_ty_1>() - 8usize];
    ["Alignment of vtest_input__bindgen_ty_1"]
        [::std::mem::align_of::<vtest_input__bindgen_ty_1>() - 8usize];
    ["Offset of field: vtest_input__bindgen_ty_1::fd"]
        [::std::mem::offset_of!(vtest_input__bindgen_ty_1, fd) - 0usize];
    ["Offset of field: vtest_input__bindgen_ty_1::buffer"]
        [::std::mem::offset_of!(vtest_input__bindgen_ty_1, buffer) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of vtest_input"][::std::mem::size_of::<vtest_input>() - 16usize];
    ["Alignment of vtest_input"][::std::mem::align_of::<vtest_input>() - 8usize];
    ["Offset of field: vtest_input::data"][::std::mem::offset_of!(vtest_input, data) - 0usize];
    ["Offset of field: vtest_input::read"][::std::mem::offset_of!(vtest_input, read) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vtest_output {
    pub data: *mut ::std::os::raw::c_void,
    pub write: ::std::option::Option<
        unsafe extern "C" fn(
            input: *mut vtest_output,
            buf: *const ::std::os::raw::c_void,
            size: ::std::os::raw::c_int,
        ) -> ::std::os::raw::c_int,
    >,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of vtest_output"][::std::mem::size_of::<vtest_output>() - 16usize];
    ["Alignment of vtest_output"][::std::mem::align_of::<vtest_output>() - 8usize];
    ["Offset of field: vtest_output::data"][::std::mem::offset_of!(vtest_output, data) - 0usize];
    ["Offset of field: vtest_output::write"][::std::mem::offset_of!(vtest_output, write) - 8usize];
};
unsafe extern "C" {
    pub fn vtest_init_renderer(
        multi_clients: bool,
        ctx_flags: ::std::os::raw::c_int,
        render_device: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vtest_cleanup_renderer();
}
unsafe extern "C" {
    pub fn vtest_create_context(
        input: *mut vtest_input,
        output: *mut vtest_output,
        length_dw: u32,
        out_ctx: *mut *mut vtest_context,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vtest_lazy_init_context(ctx: *mut vtest_context) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vtest_destroy_context(ctx: *mut vtest_context);
}
unsafe extern "C" {
    pub fn vtest_poll_context(ctx: *mut vtest_context);
}
unsafe extern "C" {
    pub fn vtest_get_context_poll_fd(ctx: *mut vtest_context) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vtest_set_current_context(ctx: *mut vtest_context);
}
unsafe extern "C" {
    pub fn vtest_send_caps(length_dw: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vtest_send_caps2(length_dw: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vtest_create_resource(length_dw: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vtest_create_resource2(length_dw: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vtest_resource_unref(length_dw: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vtest_submit_cmd(length_dw: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vtest_transfer_get(length_dw: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vtest_transfer_get_nop(length_dw: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vtest_transfer_get2(length_dw: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vtest_transfer_get2_nop(length_dw: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vtest_transfer_put(length_dw: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vtest_transfer_put_nop(length_dw: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vtest_transfer_put2(length_dw: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vtest_transfer_put2_nop(length_dw: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vtest_block_read(
        input: *mut vtest_input,
        buf: *mut ::std::os::raw::c_void,
        size: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vtest_buf_read(
        input: *mut vtest_input,
        buf: *mut ::std::os::raw::c_void,
        size: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vtest_resource_busy_wait(length_dw: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vtest_resource_busy_wait_nop(length_dw: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vtest_poll_resource_busy_wait();
}
unsafe extern "C" {
    pub fn vtest_ping_protocol_version(length_dw: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vtest_protocol_version(length_dw: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vtest_get_param(length_dw: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vtest_get_capset(length_dw: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vtest_context_init(length_dw: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vtest_resource_create_blob(length_dw: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vtest_sync_create(length_dw: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vtest_sync_unref(length_dw: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vtest_sync_read(length_dw: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vtest_sync_write(length_dw: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vtest_sync_wait(length_dw: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vtest_submit_cmd2(length_dw: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vtest_drm_sync_create(length_dw: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vtest_drm_sync_destroy(length_dw: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vtest_drm_sync_handle_to_fd(length_dw: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vtest_drm_sync_fd_to_handle(length_dw: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vtest_drm_sync_import_sync_file(length_dw: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vtest_drm_sync_export_sync_file(length_dw: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vtest_drm_sync_wait(length_dw: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vtest_drm_sync_reset(length_dw: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vtest_drm_sync_signal(length_dw: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vtest_drm_sync_timeline_signal(length_dw: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vtest_drm_sync_timeline_wait(length_dw: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vtest_drm_sync_query(length_dw: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vtest_drm_sync_transfer(length_dw: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vtest_resource_export_fd(length_dw: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn vtest_set_max_length(length: u32);
}
unsafe extern "C" {
    pub fn vtest_webrogue_write(
        input: *mut vtest_input,
        output: *mut vtest_output,
        length_dw: u32,
        out_ctx: *mut *mut vtest_context,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn webrogueSetVulkan(vulkan: *mut ::std::os::raw::c_void);
}
unsafe extern "C" {
    pub fn webrogue_virgl_is_impl() -> u8;
}
unsafe extern "C" {
    pub fn webrogue_virgl_stub_fn();
}
unsafe extern "C" {
    pub fn webrogue_map_fd(fd: i32, addr: *mut ::std::os::raw::c_void, size: usize);
}
pub type __builtin_va_list = [__va_list_tag; 1usize];
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __va_list_tag {
    pub gp_offset: ::std::os::raw::c_uint,
    pub fp_offset: ::std::os::raw::c_uint,
    pub overflow_arg_area: *mut ::std::os::raw::c_void,
    pub reg_save_area: *mut ::std::os::raw::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __va_list_tag"][::std::mem::size_of::<__va_list_tag>() - 24usize];
    ["Alignment of __va_list_tag"][::std::mem::align_of::<__va_list_tag>() - 8usize];
    ["Offset of field: __va_list_tag::gp_offset"]
        [::std::mem::offset_of!(__va_list_tag, gp_offset) - 0usize];
    ["Offset of field: __va_list_tag::fp_offset"]
        [::std::mem::offset_of!(__va_list_tag, fp_offset) - 4usize];
    ["Offset of field: __va_list_tag::overflow_arg_area"]
        [::std::mem::offset_of!(__va_list_tag, overflow_arg_area) - 8usize];
    ["Offset of field: __va_list_tag::reg_save_area"]
        [::std::mem::offset_of!(__va_list_tag, reg_save_area) - 16usize];
};
