/* automatically generated by rust-bindgen 0.72.1 */

#![allow(dead_code)]
#![allow(nonstandard_style)]

pub const _GNU_SOURCE: u32 = 1;
pub const VIRGL_RENDERER_UNSTABLE_APIS: u32 = 1;
pub const HAVE___BUILTIN_BSWAP32: u32 = 1;
pub const HAVE___BUILTIN_BSWAP64: u32 = 1;
pub const HAVE___BUILTIN_CLZ: u32 = 1;
pub const HAVE___BUILTIN_CLZLL: u32 = 1;
pub const HAVE___BUILTIN_EXPECT: u32 = 1;
pub const HAVE___BUILTIN_FFS: u32 = 1;
pub const HAVE___BUILTIN_FFSLL: u32 = 1;
pub const HAVE___BUILTIN_POPCOUNT: u32 = 1;
pub const HAVE___BUILTIN_POPCOUNTLL: u32 = 1;
pub const HAVE___BUILTIN_TYPES_COMPATIBLE_P: u32 = 1;
pub const HAVE___BUILTIN_UNREACHABLE: u32 = 1;
pub const HAVE_FUNC_ATTRIBUTE_CONST: u32 = 1;
pub const HAVE_FUNC_ATTRIBUTE_FLATTEN: u32 = 1;
pub const HAVE_FUNC_ATTRIBUTE_FORMAT: u32 = 1;
pub const HAVE_FUNC_ATTRIBUTE_MALLOC: u32 = 1;
pub const HAVE_FUNC_ATTRIBUTE_NORETURN: u32 = 1;
pub const HAVE_FUNC_ATTRIBUTE_PACKED: u32 = 1;
pub const HAVE_FUNC_ATTRIBUTE_PURE: u32 = 1;
pub const HAVE_FUNC_ATTRIBUTE_RETURNS_NONNULL: u32 = 1;
pub const HAVE_FUNC_ATTRIBUTE_UNUSED: u32 = 1;
pub const HAVE_FUNC_ATTRIBUTE_WARN_UNUSED_RESULT: u32 = 1;
pub const HAVE_FUNC_ATTRIBUTE_WEAK: u32 = 1;
pub const HAVE_TIMESPEC_GET: u32 = 1;
pub const HAVE_SYS_UIO_H: u32 = 1;
pub const CHECK_GL_ERRORS: u32 = 1;
pub const ENABLE_VENUS: u32 = 1;
pub const ENABLE_RENDER_SERVER: u32 = 1;
pub const ENABLE_SAME_PROCESS_RENDER_SERVER: u32 = 1;
pub const ENABLE_RENDER_SERVER_WORKER_THREAD: u32 = 1;
pub const RENDER_SERVER_EXEC_PATH: &[u8; 16] = b"No path to that\0";
pub const UTIL_ARCH_LITTLE_ENDIAN: u32 = 1;
pub const UTIL_ARCH_BIG_ENDIAN: u32 = 0;
pub const PIPE_ARCH_X86_64: u32 = 1;
pub const _VCRT_COMPILER_PREPROCESSOR: u32 = 1;
pub const _SAL_VERSION: u32 = 20;
pub const __SAL_H_VERSION: u32 = 180000000;
pub const _USE_DECLSPECS_FOR_SAL: u32 = 0;
pub const _USE_ATTRIBUTES_FOR_SAL: u32 = 0;
pub const _CRT_PACKING: u32 = 8;
pub const _HAS_EXCEPTIONS: u32 = 1;
pub const _STL_LANG: u32 = 0;
pub const _HAS_CXX17: u32 = 0;
pub const _HAS_CXX20: u32 = 0;
pub const _HAS_CXX23: u32 = 0;
pub const _HAS_CXX26: u32 = 0;
pub const WCHAR_MIN: u32 = 0;
pub const WCHAR_MAX: u32 = 65535;
pub const WINT_MIN: u32 = 0;
pub const WINT_MAX: u32 = 65535;
pub const __bool_true_false_are_defined: u32 = 1;
pub const false_: u32 = 0;
pub const true_: u32 = 1;
pub const VIRGL_MAJOR_VERSION: u32 = 1;
pub const VIRGL_MINOR_VERSION: u32 = 3;
pub const VIRGL_MICRO_VERSION: u32 = 0;
pub const VIRGL_RENDERER_CALLBACKS_VERSION: u32 = 4;
pub const VIRGL_RENDERER_USE_EGL: u32 = 1;
pub const VIRGL_RENDERER_THREAD_SYNC: u32 = 2;
pub const VIRGL_RENDERER_USE_GLX: u32 = 4;
pub const VIRGL_RENDERER_USE_SURFACELESS: u32 = 8;
pub const VIRGL_RENDERER_USE_GLES: u32 = 16;
pub const VIRGL_RENDERER_USE_EXTERNAL_BLOB: u32 = 32;
pub const VIRGL_RENDERER_VENUS: u32 = 64;
pub const VIRGL_RENDERER_NO_VIRGL: u32 = 128;
pub const VIRGL_RENDERER_ASYNC_FENCE_CB: u32 = 256;
pub const VIRGL_RENDERER_RENDER_SERVER: u32 = 512;
pub const VIRGL_RENDERER_DRM: u32 = 1024;
pub const VIRGL_RENDERER_USE_VIDEO: u32 = 2048;
pub const VIRGL_RENDERER_D3D11_SHARE_TEXTURE: u32 = 4096;
pub const VIRGL_RENDERER_COMPAT_PROFILE: u32 = 8192;
pub const VIRGL_RENDERER_USE_GUEST_VRAM: u32 = 16384;
pub const VIRGL_RES_BIND_DEPTH_STENCIL: u32 = 1;
pub const VIRGL_RES_BIND_RENDER_TARGET: u32 = 2;
pub const VIRGL_RES_BIND_SAMPLER_VIEW: u32 = 8;
pub const VIRGL_RES_BIND_VERTEX_BUFFER: u32 = 16;
pub const VIRGL_RES_BIND_INDEX_BUFFER: u32 = 32;
pub const VIRGL_RES_BIND_CONSTANT_BUFFER: u32 = 64;
pub const VIRGL_RES_BIND_STREAM_OUTPUT: u32 = 2048;
pub const VIRGL_RES_BIND_CURSOR: u32 = 65536;
pub const VIRGL_RES_BIND_CUSTOM: u32 = 131072;
pub const VIRGL_RES_BIND_SCANOUT: u32 = 262144;
pub const VIRGL_RES_BIND_SHARED: u32 = 1048576;
pub const VIRGL_RENDERER_RESOURCE_INFO_EXT_VERSION: u32 = 0;
pub const VIRGL_RENDERER_CONTEXT_FLAG_CAPSET_ID_MASK: u32 = 255;
pub const VIRGL_RENDERER_BLOB_MEM_GUEST: u32 = 1;
pub const VIRGL_RENDERER_BLOB_MEM_HOST3D: u32 = 2;
pub const VIRGL_RENDERER_BLOB_MEM_HOST3D_GUEST: u32 = 3;
pub const VIRGL_RENDERER_BLOB_MEM_GUEST_VRAM: u32 = 4;
pub const VIRGL_RENDERER_BLOB_FLAG_USE_MAPPABLE: u32 = 1;
pub const VIRGL_RENDERER_BLOB_FLAG_USE_SHAREABLE: u32 = 2;
pub const VIRGL_RENDERER_BLOB_FLAG_USE_CROSS_DEVICE: u32 = 4;
pub const VIRGL_RENDERER_MAP_CACHE_MASK: u32 = 15;
pub const VIRGL_RENDERER_MAP_CACHE_NONE: u32 = 0;
pub const VIRGL_RENDERER_MAP_CACHE_CACHED: u32 = 1;
pub const VIRGL_RENDERER_MAP_CACHE_UNCACHED: u32 = 2;
pub const VIRGL_RENDERER_MAP_CACHE_WC: u32 = 3;
pub const VIRGL_RENDERER_BLOB_FD_TYPE_DMABUF: u32 = 1;
pub const VIRGL_RENDERER_BLOB_FD_TYPE_OPAQUE: u32 = 2;
pub const VIRGL_RENDERER_BLOB_FD_TYPE_SHM: u32 = 3;
pub const VIRGL_RENDERER_FENCE_FLAG_MERGEABLE: u32 = 1;
pub const _ARM_WINAPI_PARTITION_DESKTOP_SDK_AVAILABLE: u32 = 1;
pub const _CRT_BUILD_DESKTOP_APP: u32 = 1;
pub const _ARGMAX: u32 = 100;
pub const _CRT_INT_MAX: u32 = 2147483647;
pub const _CRT_FUNCTIONS_REQUIRED: u32 = 1;
pub const _CRT_HAS_CXX17: u32 = 0;
pub const _CRT_HAS_C11: u32 = 1;
pub const _CRT_INTERNAL_NONSTDC_NAMES: u32 = 1;
pub const __STDC_SECURE_LIB__: u32 = 200411;
pub const __GOT_SECURE_LIB__: u32 = 200411;
pub const __STDC_WANT_SECURE_LIB__: u32 = 1;
pub const _SECURECRT_FILL_BUFFER_PATTERN: u32 = 254;
pub const _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES: u32 = 0;
pub const _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES_COUNT: u32 = 0;
pub const _CRT_SECURE_CPP_OVERLOAD_SECURE_NAMES: u32 = 1;
pub const _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES_MEMORY: u32 = 0;
pub const _CRT_SECURE_CPP_OVERLOAD_SECURE_NAMES_MEMORY: u32 = 0;
pub const _STATIC_INLINE_UCRT_FUNCTIONS: u32 = 0;
pub const STDIN_FILENO: u32 = 0;
pub const STDOUT_FILENO: u32 = 1;
pub const STDERR_FILENO: u32 = 2;
pub const SEEK_SET: u32 = 0;
pub const SEEK_CUR: u32 = 1;
pub const SEEK_END: u32 = 2;
pub const F_OK: u32 = 0;
pub const X_OK: u32 = 1;
pub const W_OK: u32 = 2;
pub const R_OK: u32 = 4;
pub const _SC_PAGESIZE: u32 = 30;
pub const _SC_PAGE_SIZE: u32 = 30;
pub type va_list = *mut ::std::os::raw::c_char;
unsafe extern "C" {
    pub fn __va_start(arg1: *mut *mut ::std::os::raw::c_char, ...);
}
pub type __vcrt_bool = bool;
pub type wchar_t = ::std::os::raw::c_ushort;
unsafe extern "C" {
    pub fn __security_init_cookie();
}
unsafe extern "C" {
    pub fn __security_check_cookie(_StackCookie: usize);
}
unsafe extern "C" {
    pub fn __report_gsfailure(_StackCookie: usize) -> !;
}
unsafe extern "C" {
    pub static mut __security_cookie: usize;
}
pub type int_least8_t = ::std::os::raw::c_schar;
pub type int_least16_t = ::std::os::raw::c_short;
pub type int_least32_t = ::std::os::raw::c_int;
pub type int_least64_t = ::std::os::raw::c_longlong;
pub type uint_least8_t = ::std::os::raw::c_uchar;
pub type uint_least16_t = ::std::os::raw::c_ushort;
pub type uint_least32_t = ::std::os::raw::c_uint;
pub type uint_least64_t = ::std::os::raw::c_ulonglong;
pub type int_fast8_t = ::std::os::raw::c_schar;
pub type int_fast16_t = ::std::os::raw::c_int;
pub type int_fast32_t = ::std::os::raw::c_int;
pub type int_fast64_t = ::std::os::raw::c_longlong;
pub type uint_fast8_t = ::std::os::raw::c_uchar;
pub type uint_fast16_t = ::std::os::raw::c_uint;
pub type uint_fast32_t = ::std::os::raw::c_uint;
pub type uint_fast64_t = ::std::os::raw::c_ulonglong;
pub type intmax_t = ::std::os::raw::c_longlong;
pub type uintmax_t = ::std::os::raw::c_ulonglong;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct virgl_box {
    _unused: [u8; 0],
}
pub type virgl_renderer_gl_context = *mut ::std::os::raw::c_void;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct virgl_renderer_gl_ctx_param {
    pub version: ::std::os::raw::c_int,
    pub shared: bool,
    pub major_ver: ::std::os::raw::c_int,
    pub minor_ver: ::std::os::raw::c_int,
    pub compat_ctx: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of virgl_renderer_gl_ctx_param"]
        [::std::mem::size_of::<virgl_renderer_gl_ctx_param>() - 20usize];
    ["Alignment of virgl_renderer_gl_ctx_param"]
        [::std::mem::align_of::<virgl_renderer_gl_ctx_param>() - 4usize];
    ["Offset of field: virgl_renderer_gl_ctx_param::version"]
        [::std::mem::offset_of!(virgl_renderer_gl_ctx_param, version) - 0usize];
    ["Offset of field: virgl_renderer_gl_ctx_param::shared"]
        [::std::mem::offset_of!(virgl_renderer_gl_ctx_param, shared) - 4usize];
    ["Offset of field: virgl_renderer_gl_ctx_param::major_ver"]
        [::std::mem::offset_of!(virgl_renderer_gl_ctx_param, major_ver) - 8usize];
    ["Offset of field: virgl_renderer_gl_ctx_param::minor_ver"]
        [::std::mem::offset_of!(virgl_renderer_gl_ctx_param, minor_ver) - 12usize];
    ["Offset of field: virgl_renderer_gl_ctx_param::compat_ctx"]
        [::std::mem::offset_of!(virgl_renderer_gl_ctx_param, compat_ctx) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct virgl_renderer_callbacks {
    pub version: ::std::os::raw::c_int,
    pub write_fence: ::std::option::Option<
        unsafe extern "C" fn(cookie: *mut ::std::os::raw::c_void, fence: u32),
    >,
    pub create_gl_context: ::std::option::Option<
        unsafe extern "C" fn(
            cookie: *mut ::std::os::raw::c_void,
            scanout_idx: ::std::os::raw::c_int,
            param: *mut virgl_renderer_gl_ctx_param,
        ) -> virgl_renderer_gl_context,
    >,
    pub destroy_gl_context: ::std::option::Option<
        unsafe extern "C" fn(cookie: *mut ::std::os::raw::c_void, ctx: virgl_renderer_gl_context),
    >,
    pub make_current: ::std::option::Option<
        unsafe extern "C" fn(
            cookie: *mut ::std::os::raw::c_void,
            scanout_idx: ::std::os::raw::c_int,
            ctx: virgl_renderer_gl_context,
        ) -> ::std::os::raw::c_int,
    >,
    pub get_drm_fd: ::std::option::Option<
        unsafe extern "C" fn(cookie: *mut ::std::os::raw::c_void) -> ::std::os::raw::c_int,
    >,
    pub write_context_fence: ::std::option::Option<
        unsafe extern "C" fn(
            cookie: *mut ::std::os::raw::c_void,
            ctx_id: u32,
            ring_idx: u32,
            fence_id: u64,
        ),
    >,
    pub get_server_fd: ::std::option::Option<
        unsafe extern "C" fn(
            cookie: *mut ::std::os::raw::c_void,
            version: u32,
        ) -> ::std::os::raw::c_int,
    >,
    pub get_egl_display: ::std::option::Option<
        unsafe extern "C" fn(cookie: *mut ::std::os::raw::c_void) -> *mut ::std::os::raw::c_void,
    >,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of virgl_renderer_callbacks"]
        [::std::mem::size_of::<virgl_renderer_callbacks>() - 72usize];
    ["Alignment of virgl_renderer_callbacks"]
        [::std::mem::align_of::<virgl_renderer_callbacks>() - 8usize];
    ["Offset of field: virgl_renderer_callbacks::version"]
        [::std::mem::offset_of!(virgl_renderer_callbacks, version) - 0usize];
    ["Offset of field: virgl_renderer_callbacks::write_fence"]
        [::std::mem::offset_of!(virgl_renderer_callbacks, write_fence) - 8usize];
    ["Offset of field: virgl_renderer_callbacks::create_gl_context"]
        [::std::mem::offset_of!(virgl_renderer_callbacks, create_gl_context) - 16usize];
    ["Offset of field: virgl_renderer_callbacks::destroy_gl_context"]
        [::std::mem::offset_of!(virgl_renderer_callbacks, destroy_gl_context) - 24usize];
    ["Offset of field: virgl_renderer_callbacks::make_current"]
        [::std::mem::offset_of!(virgl_renderer_callbacks, make_current) - 32usize];
    ["Offset of field: virgl_renderer_callbacks::get_drm_fd"]
        [::std::mem::offset_of!(virgl_renderer_callbacks, get_drm_fd) - 40usize];
    ["Offset of field: virgl_renderer_callbacks::write_context_fence"]
        [::std::mem::offset_of!(virgl_renderer_callbacks, write_context_fence) - 48usize];
    ["Offset of field: virgl_renderer_callbacks::get_server_fd"]
        [::std::mem::offset_of!(virgl_renderer_callbacks, get_server_fd) - 56usize];
    ["Offset of field: virgl_renderer_callbacks::get_egl_display"]
        [::std::mem::offset_of!(virgl_renderer_callbacks, get_egl_display) - 64usize];
};
unsafe extern "C" {
    pub fn virgl_renderer_init(
        cookie: *mut ::std::os::raw::c_void,
        flags: ::std::os::raw::c_int,
        cb: *mut virgl_renderer_callbacks,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn virgl_renderer_poll();
}
unsafe extern "C" {
    pub fn virgl_renderer_get_cursor_data(
        resource_id: u32,
        width: *mut u32,
        height: *mut u32,
    ) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn virgl_renderer_get_rect(
        resource_id: ::std::os::raw::c_int,
        iov: *mut iovec,
        num_iovs: ::std::os::raw::c_uint,
        offset: u32,
        x: ::std::os::raw::c_int,
        y: ::std::os::raw::c_int,
        width: ::std::os::raw::c_int,
        height: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn virgl_renderer_get_fd_for_texture(
        tex_id: u32,
        fd: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn virgl_renderer_get_fd_for_texture2(
        tex_id: u32,
        fd: *mut ::std::os::raw::c_int,
        stride: *mut ::std::os::raw::c_int,
        offset: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
pub const virgl_renderer_structure_type_v0_VIRGL_RENDERER_STRUCTURE_TYPE_NONE:
    virgl_renderer_structure_type_v0 = 0;
pub const virgl_renderer_structure_type_v0_VIRGL_RENDERER_STRUCTURE_TYPE_EXPORT_QUERY:
    virgl_renderer_structure_type_v0 = 1;
pub const virgl_renderer_structure_type_v0_VIRGL_RENDERER_STRUCTURE_TYPE_SUPPORTED_STRUCTURES:
    virgl_renderer_structure_type_v0 = 2;
pub type virgl_renderer_structure_type_v0 = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct virgl_renderer_resource_create_args {
    pub handle: u32,
    pub target: u32,
    pub format: u32,
    pub bind: u32,
    pub width: u32,
    pub height: u32,
    pub depth: u32,
    pub array_size: u32,
    pub last_level: u32,
    pub nr_samples: u32,
    pub flags: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of virgl_renderer_resource_create_args"]
        [::std::mem::size_of::<virgl_renderer_resource_create_args>() - 44usize];
    ["Alignment of virgl_renderer_resource_create_args"]
        [::std::mem::align_of::<virgl_renderer_resource_create_args>() - 4usize];
    ["Offset of field: virgl_renderer_resource_create_args::handle"]
        [::std::mem::offset_of!(virgl_renderer_resource_create_args, handle) - 0usize];
    ["Offset of field: virgl_renderer_resource_create_args::target"]
        [::std::mem::offset_of!(virgl_renderer_resource_create_args, target) - 4usize];
    ["Offset of field: virgl_renderer_resource_create_args::format"]
        [::std::mem::offset_of!(virgl_renderer_resource_create_args, format) - 8usize];
    ["Offset of field: virgl_renderer_resource_create_args::bind"]
        [::std::mem::offset_of!(virgl_renderer_resource_create_args, bind) - 12usize];
    ["Offset of field: virgl_renderer_resource_create_args::width"]
        [::std::mem::offset_of!(virgl_renderer_resource_create_args, width) - 16usize];
    ["Offset of field: virgl_renderer_resource_create_args::height"]
        [::std::mem::offset_of!(virgl_renderer_resource_create_args, height) - 20usize];
    ["Offset of field: virgl_renderer_resource_create_args::depth"]
        [::std::mem::offset_of!(virgl_renderer_resource_create_args, depth) - 24usize];
    ["Offset of field: virgl_renderer_resource_create_args::array_size"]
        [::std::mem::offset_of!(virgl_renderer_resource_create_args, array_size) - 28usize];
    ["Offset of field: virgl_renderer_resource_create_args::last_level"]
        [::std::mem::offset_of!(virgl_renderer_resource_create_args, last_level) - 32usize];
    ["Offset of field: virgl_renderer_resource_create_args::nr_samples"]
        [::std::mem::offset_of!(virgl_renderer_resource_create_args, nr_samples) - 36usize];
    ["Offset of field: virgl_renderer_resource_create_args::flags"]
        [::std::mem::offset_of!(virgl_renderer_resource_create_args, flags) - 40usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct virgl_renderer_hdr {
    pub stype: u32,
    pub stype_version: u32,
    pub size: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of virgl_renderer_hdr"][::std::mem::size_of::<virgl_renderer_hdr>() - 12usize];
    ["Alignment of virgl_renderer_hdr"][::std::mem::align_of::<virgl_renderer_hdr>() - 4usize];
    ["Offset of field: virgl_renderer_hdr::stype"]
        [::std::mem::offset_of!(virgl_renderer_hdr, stype) - 0usize];
    ["Offset of field: virgl_renderer_hdr::stype_version"]
        [::std::mem::offset_of!(virgl_renderer_hdr, stype_version) - 4usize];
    ["Offset of field: virgl_renderer_hdr::size"]
        [::std::mem::offset_of!(virgl_renderer_hdr, size) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct virgl_renderer_export_query {
    pub hdr: virgl_renderer_hdr,
    pub in_resource_id: u32,
    pub out_num_fds: u32,
    pub in_export_fds: u32,
    pub out_fourcc: u32,
    pub pad: u32,
    pub out_fds: [i32; 4usize],
    pub out_strides: [u32; 4usize],
    pub out_offsets: [u32; 4usize],
    pub out_modifier: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of virgl_renderer_export_query"]
        [::std::mem::size_of::<virgl_renderer_export_query>() - 88usize];
    ["Alignment of virgl_renderer_export_query"]
        [::std::mem::align_of::<virgl_renderer_export_query>() - 8usize];
    ["Offset of field: virgl_renderer_export_query::hdr"]
        [::std::mem::offset_of!(virgl_renderer_export_query, hdr) - 0usize];
    ["Offset of field: virgl_renderer_export_query::in_resource_id"]
        [::std::mem::offset_of!(virgl_renderer_export_query, in_resource_id) - 12usize];
    ["Offset of field: virgl_renderer_export_query::out_num_fds"]
        [::std::mem::offset_of!(virgl_renderer_export_query, out_num_fds) - 16usize];
    ["Offset of field: virgl_renderer_export_query::in_export_fds"]
        [::std::mem::offset_of!(virgl_renderer_export_query, in_export_fds) - 20usize];
    ["Offset of field: virgl_renderer_export_query::out_fourcc"]
        [::std::mem::offset_of!(virgl_renderer_export_query, out_fourcc) - 24usize];
    ["Offset of field: virgl_renderer_export_query::pad"]
        [::std::mem::offset_of!(virgl_renderer_export_query, pad) - 28usize];
    ["Offset of field: virgl_renderer_export_query::out_fds"]
        [::std::mem::offset_of!(virgl_renderer_export_query, out_fds) - 32usize];
    ["Offset of field: virgl_renderer_export_query::out_strides"]
        [::std::mem::offset_of!(virgl_renderer_export_query, out_strides) - 48usize];
    ["Offset of field: virgl_renderer_export_query::out_offsets"]
        [::std::mem::offset_of!(virgl_renderer_export_query, out_offsets) - 64usize];
    ["Offset of field: virgl_renderer_export_query::out_modifier"]
        [::std::mem::offset_of!(virgl_renderer_export_query, out_modifier) - 80usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct virgl_renderer_supported_structures {
    pub hdr: virgl_renderer_hdr,
    pub in_stype_version: u32,
    pub out_supported_structures_mask: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of virgl_renderer_supported_structures"]
        [::std::mem::size_of::<virgl_renderer_supported_structures>() - 20usize];
    ["Alignment of virgl_renderer_supported_structures"]
        [::std::mem::align_of::<virgl_renderer_supported_structures>() - 4usize];
    ["Offset of field: virgl_renderer_supported_structures::hdr"]
        [::std::mem::offset_of!(virgl_renderer_supported_structures, hdr) - 0usize];
    ["Offset of field: virgl_renderer_supported_structures::in_stype_version"]
        [::std::mem::offset_of!(virgl_renderer_supported_structures, in_stype_version) - 12usize];
    ["Offset of field: virgl_renderer_supported_structures::out_supported_structures_mask"][::std::mem::offset_of!(
        virgl_renderer_supported_structures,
        out_supported_structures_mask
    )
        - 16usize];
};
pub type virgl_debug_callback_type =
    ::std::option::Option<unsafe extern "C" fn(fmt: *const ::std::os::raw::c_char, ap: va_list)>;
pub const virgl_log_level_flags_VIRGL_LOG_LEVEL_DEBUG: virgl_log_level_flags = 0;
pub const virgl_log_level_flags_VIRGL_LOG_LEVEL_INFO: virgl_log_level_flags = 1;
pub const virgl_log_level_flags_VIRGL_LOG_LEVEL_WARNING: virgl_log_level_flags = 2;
pub const virgl_log_level_flags_VIRGL_LOG_LEVEL_ERROR: virgl_log_level_flags = 3;
pub const virgl_log_level_flags_VIRGL_LOG_LEVEL_SILENT: virgl_log_level_flags = 4;
pub type virgl_log_level_flags = ::std::os::raw::c_int;
pub type virgl_free_data_callback_type =
    ::std::option::Option<unsafe extern "C" fn(user_data: *mut ::std::os::raw::c_void)>;
pub type virgl_log_callback_type = ::std::option::Option<
    unsafe extern "C" fn(
        log_level: virgl_log_level_flags,
        message: *const ::std::os::raw::c_char,
        user_data: *mut ::std::os::raw::c_void,
    ),
>;
unsafe extern "C" {
    pub fn virgl_renderer_resource_create(
        args: *mut virgl_renderer_resource_create_args,
        iov: *mut iovec,
        num_iovs: u32,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn virgl_renderer_resource_import_eglimage(
        args: *mut virgl_renderer_resource_create_args,
        image: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn virgl_renderer_resource_unref(res_handle: u32);
}
unsafe extern "C" {
    pub fn virgl_renderer_resource_set_priv(res_handle: u32, priv_: *mut ::std::os::raw::c_void);
}
unsafe extern "C" {
    pub fn virgl_renderer_resource_get_priv(res_handle: u32) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn virgl_renderer_context_create(
        handle: u32,
        nlen: u32,
        name: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn virgl_renderer_context_destroy(handle: u32);
}
unsafe extern "C" {
    pub fn virgl_renderer_submit_cmd(
        buffer: *mut ::std::os::raw::c_void,
        ctx_id: ::std::os::raw::c_int,
        ndw: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn virgl_renderer_transfer_read_iov(
        handle: u32,
        ctx_id: u32,
        level: u32,
        stride: u32,
        layer_stride: u32,
        box_: *mut virgl_box,
        offset: u64,
        iov: *mut iovec,
        iovec_cnt: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn virgl_renderer_transfer_write_iov(
        handle: u32,
        ctx_id: u32,
        level: ::std::os::raw::c_int,
        stride: u32,
        layer_stride: u32,
        box_: *mut virgl_box,
        offset: u64,
        iovec: *mut iovec,
        iovec_cnt: ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn virgl_renderer_get_cap_set(set: u32, max_ver: *mut u32, max_size: *mut u32);
}
unsafe extern "C" {
    pub fn virgl_renderer_fill_caps(set: u32, version: u32, caps: *mut ::std::os::raw::c_void);
}
unsafe extern "C" {
    pub fn virgl_renderer_resource_attach_iov(
        res_handle: ::std::os::raw::c_int,
        iov: *mut iovec,
        num_iovs: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn virgl_renderer_resource_detach_iov(
        res_handle: ::std::os::raw::c_int,
        iov: *mut *mut iovec,
        num_iovs: *mut ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn virgl_renderer_create_fence(
        client_fence_id: ::std::os::raw::c_int,
        ctx_id: u32,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn virgl_renderer_force_ctx_0();
}
unsafe extern "C" {
    pub fn virgl_renderer_ctx_attach_resource(
        ctx_id: ::std::os::raw::c_int,
        res_handle: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn virgl_renderer_ctx_detach_resource(
        ctx_id: ::std::os::raw::c_int,
        res_handle: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn virgl_set_debug_callback(cb: virgl_debug_callback_type) -> virgl_debug_callback_type;
}
unsafe extern "C" {
    pub fn virgl_set_log_callback(
        cb: virgl_log_callback_type,
        user_data: *mut ::std::os::raw::c_void,
        free_user_data_cb: virgl_free_data_callback_type,
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct virgl_renderer_resource_info {
    pub handle: u32,
    pub virgl_format: u32,
    pub width: u32,
    pub height: u32,
    pub depth: u32,
    pub flags: u32,
    pub tex_id: u32,
    pub stride: u32,
    pub drm_fourcc: ::std::os::raw::c_int,
    pub fd: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of virgl_renderer_resource_info"]
        [::std::mem::size_of::<virgl_renderer_resource_info>() - 40usize];
    ["Alignment of virgl_renderer_resource_info"]
        [::std::mem::align_of::<virgl_renderer_resource_info>() - 4usize];
    ["Offset of field: virgl_renderer_resource_info::handle"]
        [::std::mem::offset_of!(virgl_renderer_resource_info, handle) - 0usize];
    ["Offset of field: virgl_renderer_resource_info::virgl_format"]
        [::std::mem::offset_of!(virgl_renderer_resource_info, virgl_format) - 4usize];
    ["Offset of field: virgl_renderer_resource_info::width"]
        [::std::mem::offset_of!(virgl_renderer_resource_info, width) - 8usize];
    ["Offset of field: virgl_renderer_resource_info::height"]
        [::std::mem::offset_of!(virgl_renderer_resource_info, height) - 12usize];
    ["Offset of field: virgl_renderer_resource_info::depth"]
        [::std::mem::offset_of!(virgl_renderer_resource_info, depth) - 16usize];
    ["Offset of field: virgl_renderer_resource_info::flags"]
        [::std::mem::offset_of!(virgl_renderer_resource_info, flags) - 20usize];
    ["Offset of field: virgl_renderer_resource_info::tex_id"]
        [::std::mem::offset_of!(virgl_renderer_resource_info, tex_id) - 24usize];
    ["Offset of field: virgl_renderer_resource_info::stride"]
        [::std::mem::offset_of!(virgl_renderer_resource_info, stride) - 28usize];
    ["Offset of field: virgl_renderer_resource_info::drm_fourcc"]
        [::std::mem::offset_of!(virgl_renderer_resource_info, drm_fourcc) - 32usize];
    ["Offset of field: virgl_renderer_resource_info::fd"]
        [::std::mem::offset_of!(virgl_renderer_resource_info, fd) - 36usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct virgl_renderer_resource_info_ext {
    pub version: ::std::os::raw::c_int,
    pub base: virgl_renderer_resource_info,
    pub has_dmabuf_export: bool,
    pub planes: ::std::os::raw::c_int,
    pub modifiers: u64,
    pub d3d_tex2d: *mut ::std::os::raw::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of virgl_renderer_resource_info_ext"]
        [::std::mem::size_of::<virgl_renderer_resource_info_ext>() - 72usize];
    ["Alignment of virgl_renderer_resource_info_ext"]
        [::std::mem::align_of::<virgl_renderer_resource_info_ext>() - 8usize];
    ["Offset of field: virgl_renderer_resource_info_ext::version"]
        [::std::mem::offset_of!(virgl_renderer_resource_info_ext, version) - 0usize];
    ["Offset of field: virgl_renderer_resource_info_ext::base"]
        [::std::mem::offset_of!(virgl_renderer_resource_info_ext, base) - 4usize];
    ["Offset of field: virgl_renderer_resource_info_ext::has_dmabuf_export"]
        [::std::mem::offset_of!(virgl_renderer_resource_info_ext, has_dmabuf_export) - 44usize];
    ["Offset of field: virgl_renderer_resource_info_ext::planes"]
        [::std::mem::offset_of!(virgl_renderer_resource_info_ext, planes) - 48usize];
    ["Offset of field: virgl_renderer_resource_info_ext::modifiers"]
        [::std::mem::offset_of!(virgl_renderer_resource_info_ext, modifiers) - 56usize];
    ["Offset of field: virgl_renderer_resource_info_ext::d3d_tex2d"]
        [::std::mem::offset_of!(virgl_renderer_resource_info_ext, d3d_tex2d) - 64usize];
};
unsafe extern "C" {
    pub fn virgl_renderer_resource_get_info(
        res_handle: ::std::os::raw::c_int,
        info: *mut virgl_renderer_resource_info,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn virgl_renderer_resource_get_info_ext(
        res_handle: ::std::os::raw::c_int,
        info: *mut virgl_renderer_resource_info_ext,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn virgl_renderer_cleanup(cookie: *mut ::std::os::raw::c_void);
}
unsafe extern "C" {
    pub fn virgl_renderer_reset();
}
unsafe extern "C" {
    pub fn virgl_renderer_get_poll_fd() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn virgl_renderer_execute(
        execute_args: *mut ::std::os::raw::c_void,
        execute_size: u32,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn virgl_renderer_context_create_with_flags(
        ctx_id: u32,
        ctx_flags: u32,
        nlen: u32,
        name: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct virgl_renderer_resource_create_blob_args {
    pub res_handle: u32,
    pub ctx_id: u32,
    pub blob_mem: u32,
    pub blob_flags: u32,
    pub blob_id: u64,
    pub size: u64,
    pub iovecs: *const iovec,
    pub num_iovs: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of virgl_renderer_resource_create_blob_args"]
        [::std::mem::size_of::<virgl_renderer_resource_create_blob_args>() - 48usize];
    ["Alignment of virgl_renderer_resource_create_blob_args"]
        [::std::mem::align_of::<virgl_renderer_resource_create_blob_args>() - 8usize];
    ["Offset of field: virgl_renderer_resource_create_blob_args::res_handle"]
        [::std::mem::offset_of!(virgl_renderer_resource_create_blob_args, res_handle) - 0usize];
    ["Offset of field: virgl_renderer_resource_create_blob_args::ctx_id"]
        [::std::mem::offset_of!(virgl_renderer_resource_create_blob_args, ctx_id) - 4usize];
    ["Offset of field: virgl_renderer_resource_create_blob_args::blob_mem"]
        [::std::mem::offset_of!(virgl_renderer_resource_create_blob_args, blob_mem) - 8usize];
    ["Offset of field: virgl_renderer_resource_create_blob_args::blob_flags"]
        [::std::mem::offset_of!(virgl_renderer_resource_create_blob_args, blob_flags) - 12usize];
    ["Offset of field: virgl_renderer_resource_create_blob_args::blob_id"]
        [::std::mem::offset_of!(virgl_renderer_resource_create_blob_args, blob_id) - 16usize];
    ["Offset of field: virgl_renderer_resource_create_blob_args::size"]
        [::std::mem::offset_of!(virgl_renderer_resource_create_blob_args, size) - 24usize];
    ["Offset of field: virgl_renderer_resource_create_blob_args::iovecs"]
        [::std::mem::offset_of!(virgl_renderer_resource_create_blob_args, iovecs) - 32usize];
    ["Offset of field: virgl_renderer_resource_create_blob_args::num_iovs"]
        [::std::mem::offset_of!(virgl_renderer_resource_create_blob_args, num_iovs) - 40usize];
};
unsafe extern "C" {
    pub fn virgl_renderer_resource_create_blob(
        args: *const virgl_renderer_resource_create_blob_args,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn virgl_renderer_resource_map(
        res_handle: u32,
        map: *mut *mut ::std::os::raw::c_void,
        out_size: *mut u64,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn virgl_renderer_resource_unmap(res_handle: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn virgl_renderer_resource_get_map_info(
        res_handle: u32,
        map_info: *mut u32,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn virgl_renderer_resource_export_blob(
        res_id: u32,
        fd_type: *mut u32,
        fd: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct virgl_renderer_resource_import_blob_args {
    pub res_handle: u32,
    pub blob_mem: u32,
    pub fd_type: u32,
    pub fd: ::std::os::raw::c_int,
    pub size: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of virgl_renderer_resource_import_blob_args"]
        [::std::mem::size_of::<virgl_renderer_resource_import_blob_args>() - 24usize];
    ["Alignment of virgl_renderer_resource_import_blob_args"]
        [::std::mem::align_of::<virgl_renderer_resource_import_blob_args>() - 8usize];
    ["Offset of field: virgl_renderer_resource_import_blob_args::res_handle"]
        [::std::mem::offset_of!(virgl_renderer_resource_import_blob_args, res_handle) - 0usize];
    ["Offset of field: virgl_renderer_resource_import_blob_args::blob_mem"]
        [::std::mem::offset_of!(virgl_renderer_resource_import_blob_args, blob_mem) - 4usize];
    ["Offset of field: virgl_renderer_resource_import_blob_args::fd_type"]
        [::std::mem::offset_of!(virgl_renderer_resource_import_blob_args, fd_type) - 8usize];
    ["Offset of field: virgl_renderer_resource_import_blob_args::fd"]
        [::std::mem::offset_of!(virgl_renderer_resource_import_blob_args, fd) - 12usize];
    ["Offset of field: virgl_renderer_resource_import_blob_args::size"]
        [::std::mem::offset_of!(virgl_renderer_resource_import_blob_args, size) - 16usize];
};
unsafe extern "C" {
    pub fn virgl_renderer_resource_import_blob(
        args: *const virgl_renderer_resource_import_blob_args,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn virgl_renderer_context_create_fence(
        ctx_id: u32,
        flags: u32,
        ring_idx: u32,
        fence_id: u64,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn virgl_renderer_context_poll(ctx_id: u32);
}
unsafe extern "C" {
    pub fn virgl_renderer_context_get_poll_fd(ctx_id: u32) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn virgl_renderer_resource_map_fixed(
        res_handle: u32,
        addr: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn virgl_renderer_export_fence(
        client_fence_id: u64,
        fd: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn virgl_renderer_export_signalled_fence() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn virgl_renderer_submit_cmd2(
        buffer: *mut ::std::os::raw::c_void,
        ctx_id: ::std::os::raw::c_int,
        ndw: ::std::os::raw::c_int,
        in_fence_ids: *mut u64,
        num_in_fences: u32,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn virgl_renderer_attach_fence(
        ctx_id: ::std::os::raw::c_int,
        fence_fd: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn virgl_renderer_get_fence_fd(fence_id: u64) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn virgl_renderer_get_dev_fd(ctx_id: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
pub type __crt_bool = bool;
unsafe extern "C" {
    pub fn _invalid_parameter_noinfo();
}
unsafe extern "C" {
    pub fn _invalid_parameter_noinfo_noreturn() -> !;
}
unsafe extern "C" {
    pub fn _invoke_watson(
        _Expression: *const wchar_t,
        _FunctionName: *const wchar_t,
        _FileName: *const wchar_t,
        _LineNo: ::std::os::raw::c_uint,
        _Reserved: usize,
    ) -> !;
}
pub type errno_t = ::std::os::raw::c_int;
pub type wint_t = ::std::os::raw::c_ushort;
pub type wctype_t = ::std::os::raw::c_ushort;
pub type __time32_t = ::std::os::raw::c_long;
pub type __time64_t = ::std::os::raw::c_longlong;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __crt_locale_data_public {
    pub _locale_pctype: *const ::std::os::raw::c_ushort,
    pub _locale_mb_cur_max: ::std::os::raw::c_int,
    pub _locale_lc_codepage: ::std::os::raw::c_uint,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __crt_locale_data_public"]
        [::std::mem::size_of::<__crt_locale_data_public>() - 16usize];
    ["Alignment of __crt_locale_data_public"]
        [::std::mem::align_of::<__crt_locale_data_public>() - 8usize];
    ["Offset of field: __crt_locale_data_public::_locale_pctype"]
        [::std::mem::offset_of!(__crt_locale_data_public, _locale_pctype) - 0usize];
    ["Offset of field: __crt_locale_data_public::_locale_mb_cur_max"]
        [::std::mem::offset_of!(__crt_locale_data_public, _locale_mb_cur_max) - 8usize];
    ["Offset of field: __crt_locale_data_public::_locale_lc_codepage"]
        [::std::mem::offset_of!(__crt_locale_data_public, _locale_lc_codepage) - 12usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __crt_locale_pointers {
    pub locinfo: *mut __crt_locale_data,
    pub mbcinfo: *mut __crt_multibyte_data,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __crt_locale_pointers"][::std::mem::size_of::<__crt_locale_pointers>() - 16usize];
    ["Alignment of __crt_locale_pointers"]
        [::std::mem::align_of::<__crt_locale_pointers>() - 8usize];
    ["Offset of field: __crt_locale_pointers::locinfo"]
        [::std::mem::offset_of!(__crt_locale_pointers, locinfo) - 0usize];
    ["Offset of field: __crt_locale_pointers::mbcinfo"]
        [::std::mem::offset_of!(__crt_locale_pointers, mbcinfo) - 8usize];
};
pub type _locale_t = *mut __crt_locale_pointers;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _Mbstatet {
    pub _Wchar: ::std::os::raw::c_ulong,
    pub _Byte: ::std::os::raw::c_ushort,
    pub _State: ::std::os::raw::c_ushort,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _Mbstatet"][::std::mem::size_of::<_Mbstatet>() - 8usize];
    ["Alignment of _Mbstatet"][::std::mem::align_of::<_Mbstatet>() - 4usize];
    ["Offset of field: _Mbstatet::_Wchar"][::std::mem::offset_of!(_Mbstatet, _Wchar) - 0usize];
    ["Offset of field: _Mbstatet::_Byte"][::std::mem::offset_of!(_Mbstatet, _Byte) - 4usize];
    ["Offset of field: _Mbstatet::_State"][::std::mem::offset_of!(_Mbstatet, _State) - 6usize];
};
pub type mbstate_t = _Mbstatet;
pub type time_t = __time64_t;
pub type rsize_t = usize;
unsafe extern "C" {
    pub fn _errno() -> *mut ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn _set_errno(_Value: ::std::os::raw::c_int) -> errno_t;
}
unsafe extern "C" {
    pub fn _get_errno(_Value: *mut ::std::os::raw::c_int) -> errno_t;
}
unsafe extern "C" {
    pub fn __threadid() -> ::std::os::raw::c_ulong;
}
unsafe extern "C" {
    pub fn __threadhandle() -> usize;
}
pub type POINTER_64_INT = ::std::os::raw::c_ulonglong;
pub type INT8 = ::std::os::raw::c_schar;
pub type PINT8 = *mut ::std::os::raw::c_schar;
pub type INT16 = ::std::os::raw::c_short;
pub type PINT16 = *mut ::std::os::raw::c_short;
pub type INT32 = ::std::os::raw::c_int;
pub type PINT32 = *mut ::std::os::raw::c_int;
pub type INT64 = ::std::os::raw::c_longlong;
pub type PINT64 = *mut ::std::os::raw::c_longlong;
pub type UINT8 = ::std::os::raw::c_uchar;
pub type PUINT8 = *mut ::std::os::raw::c_uchar;
pub type UINT16 = ::std::os::raw::c_ushort;
pub type PUINT16 = *mut ::std::os::raw::c_ushort;
pub type UINT32 = ::std::os::raw::c_uint;
pub type PUINT32 = *mut ::std::os::raw::c_uint;
pub type UINT64 = ::std::os::raw::c_ulonglong;
pub type PUINT64 = *mut ::std::os::raw::c_ulonglong;
pub type LONG32 = ::std::os::raw::c_int;
pub type PLONG32 = *mut ::std::os::raw::c_int;
pub type ULONG32 = ::std::os::raw::c_uint;
pub type PULONG32 = *mut ::std::os::raw::c_uint;
pub type DWORD32 = ::std::os::raw::c_uint;
pub type PDWORD32 = *mut ::std::os::raw::c_uint;
pub type INT_PTR = ::std::os::raw::c_longlong;
pub type PINT_PTR = *mut ::std::os::raw::c_longlong;
pub type UINT_PTR = ::std::os::raw::c_ulonglong;
pub type PUINT_PTR = *mut ::std::os::raw::c_ulonglong;
pub type LONG_PTR = ::std::os::raw::c_longlong;
pub type PLONG_PTR = *mut ::std::os::raw::c_longlong;
pub type ULONG_PTR = ::std::os::raw::c_ulonglong;
pub type PULONG_PTR = *mut ::std::os::raw::c_ulonglong;
pub type PHANDLE64 = *mut *mut ::std::os::raw::c_void;
pub type SHANDLE_PTR = ::std::os::raw::c_longlong;
pub type HANDLE_PTR = ::std::os::raw::c_ulonglong;
pub type UHALF_PTR = ::std::os::raw::c_uint;
pub type PUHALF_PTR = *mut ::std::os::raw::c_uint;
pub type HALF_PTR = ::std::os::raw::c_int;
pub type PHALF_PTR = *mut ::std::os::raw::c_int;
pub type SIZE_T = ULONG_PTR;
pub type PSIZE_T = *mut ULONG_PTR;
pub type SSIZE_T = LONG_PTR;
pub type PSSIZE_T = *mut LONG_PTR;
pub type DWORD_PTR = ULONG_PTR;
pub type PDWORD_PTR = *mut ULONG_PTR;
pub type LONG64 = ::std::os::raw::c_longlong;
pub type PLONG64 = *mut ::std::os::raw::c_longlong;
pub type ULONG64 = ::std::os::raw::c_ulonglong;
pub type PULONG64 = *mut ::std::os::raw::c_ulonglong;
pub type DWORD64 = ::std::os::raw::c_ulonglong;
pub type PDWORD64 = *mut ::std::os::raw::c_ulonglong;
pub type KAFFINITY = ULONG_PTR;
pub type PKAFFINITY = *mut KAFFINITY;
pub type _ino_t = ::std::os::raw::c_ushort;
pub type ino_t = _ino_t;
pub type _dev_t = ::std::os::raw::c_uint;
pub type dev_t = _dev_t;
pub type _off_t = ::std::os::raw::c_long;
pub type off_t = _off_t;
pub type _off64_t = ::std::os::raw::c_longlong;
pub type off64_t = _off64_t;
pub type _mode_t = ::std::os::raw::c_ushort;
pub type mode_t = _mode_t;
pub type pid_t = isize;
pub type useconds_t = ::std::os::raw::c_uint;
pub type id_t = ::std::os::raw::c_int;
pub type idtype_t = ::std::os::raw::c_uint;
pub type uid_t = ::std::os::raw::c_uint;
pub type gid_t = ::std::os::raw::c_uint;
pub type nlink_t = ::std::os::raw::c_ushort;
pub type blkcnt_t = ::std::os::raw::c_long;
pub type blksize_t = ::std::os::raw::c_long;
pub type u_char = ::std::os::raw::c_uchar;
pub type u_short = ::std::os::raw::c_ushort;
pub type u_int = ::std::os::raw::c_uint;
pub type u_long = ::std::os::raw::c_ulong;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct iovec {
    pub iov_base: *mut ::std::os::raw::c_void,
    pub iov_len: usize,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of iovec"][::std::mem::size_of::<iovec>() - 16usize];
    ["Alignment of iovec"][::std::mem::align_of::<iovec>() - 8usize];
    ["Offset of field: iovec::iov_base"][::std::mem::offset_of!(iovec, iov_base) - 0usize];
    ["Offset of field: iovec::iov_len"][::std::mem::offset_of!(iovec, iov_len) - 8usize];
};
unsafe extern "C" {
    pub fn readv(
        fd: ::std::os::raw::c_int,
        iov: *const iovec,
        iovcnt: ::std::os::raw::c_int,
    ) -> isize;
}
unsafe extern "C" {
    pub fn writev(
        fd: ::std::os::raw::c_int,
        iov: *const iovec,
        iovcnt: ::std::os::raw::c_int,
    ) -> isize;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vrend_transfer_info {
    pub level: ::std::os::raw::c_uint,
    pub stride: u32,
    pub layer_stride: u32,
    pub iovec_cnt: ::std::os::raw::c_uint,
    pub iovec: *const iovec,
    pub offset: u64,
    pub box_: *mut pipe_box,
    pub synchronized: bool,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of vrend_transfer_info"][::std::mem::size_of::<vrend_transfer_info>() - 48usize];
    ["Alignment of vrend_transfer_info"][::std::mem::align_of::<vrend_transfer_info>() - 8usize];
    ["Offset of field: vrend_transfer_info::level"]
        [::std::mem::offset_of!(vrend_transfer_info, level) - 0usize];
    ["Offset of field: vrend_transfer_info::stride"]
        [::std::mem::offset_of!(vrend_transfer_info, stride) - 4usize];
    ["Offset of field: vrend_transfer_info::layer_stride"]
        [::std::mem::offset_of!(vrend_transfer_info, layer_stride) - 8usize];
    ["Offset of field: vrend_transfer_info::iovec_cnt"]
        [::std::mem::offset_of!(vrend_transfer_info, iovec_cnt) - 12usize];
    ["Offset of field: vrend_transfer_info::iovec"]
        [::std::mem::offset_of!(vrend_transfer_info, iovec) - 16usize];
    ["Offset of field: vrend_transfer_info::offset"]
        [::std::mem::offset_of!(vrend_transfer_info, offset) - 24usize];
    ["Offset of field: vrend_transfer_info::box_"]
        [::std::mem::offset_of!(vrend_transfer_info, box_) - 32usize];
    ["Offset of field: vrend_transfer_info::synchronized"]
        [::std::mem::offset_of!(vrend_transfer_info, synchronized) - 40usize];
};
pub type iov_cb = ::std::option::Option<
    unsafe extern "C" fn(
        cookie: *mut ::std::os::raw::c_void,
        doff: ::std::os::raw::c_uint,
        src: *mut ::std::os::raw::c_void,
        len: ::std::os::raw::c_int,
    ),
>;
unsafe extern "C" {
    pub fn vrend_get_iovec_size(iov: *const iovec, iovlen: ::std::os::raw::c_int) -> usize;
}
unsafe extern "C" {
    pub fn vrend_read_from_iovec(
        iov: *const iovec,
        iov_cnt: ::std::os::raw::c_int,
        offset: usize,
        buf: *mut ::std::os::raw::c_char,
        bytes: usize,
    ) -> usize;
}
unsafe extern "C" {
    pub fn vrend_write_to_iovec(
        iov: *const iovec,
        iov_cnt: ::std::os::raw::c_int,
        offset: usize,
        buf: *const ::std::os::raw::c_char,
        bytes: usize,
    ) -> usize;
}
unsafe extern "C" {
    pub fn vrend_read_from_iovec_cb(
        iov: *const iovec,
        iov_cnt: ::std::os::raw::c_int,
        offset: usize,
        bytes: usize,
        iocb: iov_cb,
        cookie: *mut ::std::os::raw::c_void,
    ) -> usize;
}
unsafe extern "C" {
    pub fn vrend_copy_iovec(
        src_iov: *const iovec,
        src_iovlen: ::std::os::raw::c_int,
        src_offset: usize,
        dst_iov: *const iovec,
        dst_iovlen: ::std::os::raw::c_int,
        dst_offset: usize,
        count: usize,
        buf: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn close(fd: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn read(
        fd: ::std::os::raw::c_int,
        buf: *mut ::std::os::raw::c_void,
        count: ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn write(
        fd: ::std::os::raw::c_int,
        buf: *const ::std::os::raw::c_void,
        count: ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn lseek(
        fd: ::std::os::raw::c_int,
        offset: ::std::os::raw::c_long,
        whence: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_long;
}
unsafe extern "C" {
    pub fn fsync(fd: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn ftruncate(fd: ::std::os::raw::c_int, length: off_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn dup(fd: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn dup2(fd: ::std::os::raw::c_int, fd2: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn pipe(fds: *mut ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn access(
        path: *const ::std::os::raw::c_char,
        mode: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn unlink(path: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rmdir(path: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn chdir(path: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn getcwd(
        buf: *mut ::std::os::raw::c_char,
        size: ::std::os::raw::c_int,
    ) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn getpid() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn sysconf(name: ::std::os::raw::c_int) -> ::std::os::raw::c_long;
}
unsafe extern "C" {
    pub fn sleep(seconds: ::std::os::raw::c_uint) -> ::std::os::raw::c_uint;
}
unsafe extern "C" {
    pub fn usleep(usec: useconds_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn setenv(
        name: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
        overwrite: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn unsetenv(name: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn webrogueSetVulkan(vulkan: *mut ::std::os::raw::c_void);
}
unsafe extern "C" {
    pub fn webrogueGetVulkan() -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn webrogue_virgl_is_impl() -> u8;
}
unsafe extern "C" {
    pub fn webrogue_virgl_stub_fn();
}
unsafe extern "C" {
    pub fn webrogue_get_host_blob(blob_id: u64) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn webrogue_virgl_setup_shmem(ptr: *mut ::std::os::raw::c_void, size: usize);
}
unsafe extern "C" {
    pub fn webrogue_virgl_pop_shmem(out_size: *mut usize) -> *mut ::std::os::raw::c_void;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __crt_locale_data {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __crt_multibyte_data {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pipe_box {
    pub _address: u8,
}
