[package]
name = "webrogue-web-main"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
webrogue-gfx = { workspace = true }
wasi-common = { workspace = true, default-features = false, features = ["sync"] }
anyhow = { workspace = true }
# cap-std = "3.4.1"
webrogue-wrapp = { workspace = true }
wiggle = { workspace = true, default-features = false, features = [] }
webrogue-web-macro = { workspace = true }
wasmparser = { workspace = true, default-features = false }
