[package]
name = "webrogue-web-main"
version.workspace = true
authors.workspace = true
edition.workspace = true

[features]
default = ["gl"]
gl = ["dep:webrogue-gl", "dep:webrogue-gfx", "dep:webrogue-gfx-ffi"]

[dependencies]
webrogue-runtime = { workspace = true }
webrogue-wasi-sync = { workspace = true }
webrogue-std-stream-os = { workspace = true }
webrogue-backend-web = { workspace = true }
anyhow = { workspace = true }
webrogue-wasi = { workspace = true }
webrogue-gl = { workspace = true, optional = true }
webrogue-gfx = { workspace = true, optional = true }
webrogue-gfx-ffi = { workspace = true, optional = true }
