[package]
name = "webrogue_wasi"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
webrogue_runtime = { workspace = true }
wasi-common = { workspace = true, default-features = false, features = ["trace_log"] }
wiggle = { workspace = true, default-features = false, features = ["wiggle_metadata"] }
futures =  { workspace = true }
anyhow = { workspace = true }
