on:
  workflow_call:
    inputs:
      is_release:
        required: true
        type: boolean

jobs:
  macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Submodules
      run: |
        git submodule update --init --recursive --single-branch external/xz/
        git submodule update --init --recursive --single-branch external/libuv/
        git submodule update --init --recursive --single-branch external/uvwasi/
        git submodule update --init --recursive --single-branch external/wasmer/
        git submodule update --init --recursive --single-branch external/SDL/
        git submodule update --init --recursive --single-branch external/SDL_ttf/

    - name: Install packages
      run: |
        python3 -m venv .venv
        . .venv/bin/activate
        python3 -m pip install zstd

    - name: Install rust tools
      run: |
        cargo install cargo-lipo

    - name: Cmake Cache
      uses: actions/cache@v4
      with:
        path: platforms/MacOS/cmake_build/CMakeCache.txt
        key: macos-cmake-cache

    - name: Configure and build
      run: |
        . .venv/bin/activate
        sh platforms/MacOS/build.sh --release

    - uses: actions/upload-artifact@v4
      if: ${{ inputs.is_release }}
      with:
        name: Artifacts-MacOS
        path: |
          webrogue.dmg
