name: Build Webrogue CLI utility for Linux (glibc)

on:
  workflow_call

jobs:
  x86_64-glibc:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Submodules
      run: |
        git submodule update --init --single-branch --depth=1 external/wasmtime external/aemu external/gfxstream external/llvm
  
    - name: Build
      run: |
        sh linux/build_cli.sh

    - uses: actions/upload-artifact@v4
      with:
        name: CLI-linux-x86_64-glibc-raw
        retention-days: 1
        if-no-files-found: error
        path: linux/target/x86_64-unknown-linux-gnu/release-lto/webrogue
