name:  Build Webrogue SDK

on:
  workflow_dispatch

jobs:
  cli:
    uses: ./.github/workflows/build_cli.yml

  sdk:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Submodules
      run: |
        git submodule update --init --single-branch --depth=1 webrogue-sdk external/aemu external/gfxstream
        cd webrogue-sdk && git submodule update --init --single-branch --depth=1

    - name: Build
      run: |
        sh webrogue-sdk/build.sh

    - name: Archive SDK
      run: |
        tar czf sdk_raw.tar.gz -C webrogue-sdk/package/ webrogue-x86_64-linux webrogue-x86_64-windows webrogue-x86_64-macos webrogue-arm64-macos

    - uses: actions/upload-artifact@v4
      with:
        name: SDK-raw
        compression-level: 0
        retention-days: 1
        if-no-files-found: error
        path: |
          sdk_raw.tar.gz
  
  combine:
    needs: [cli, sdk]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with: 
          name: SDK-raw
          path: sdk

      - name: Extract SDK-raw
        run: |
          tar xzf sdk/sdk_raw.tar.gz

      - uses: actions/download-artifact@v4
        with: 
          name: CLI
          path: cli

      - name: Add Webrogue CLI utility to SDK
        run: |
          cp cli/webrogue_linux_x86_64_glibc webrogue-x86_64-linux/bin/webrogue
          chmod +x webrogue-x86_64-linux/bin/webrogue

          cp cli/webrogue_windows_x86_64.exe webrogue-x86_64-windows/bin/webrogue.exe

          cp cli/webrogue_macos_x86_64 webrogue-x86_64-macos/bin/webrogue
          chmod +x webrogue-x86_64-macos/bin/webrogue
          cp cli/webrogue_macos_arm64 webrogue-arm64-macos/bin/webrogue
          chmod +x webrogue-arm64-macos/bin/webrogue

      - name: Archive SDK
        run: |
          tar czf webrogue-x86_64-linux.tar.gz webrogue-x86_64-linux/

          zip -r ../webrogue-x86_64-windows.zip webrogue-x86_64-windows

          tar czf webrogue-x86_64-macos.tar.gz webrogue-x86_64-macos/
          tar czf webrogue-arm64-macos.tar.gz webrogue-arm64-macos/

      - uses: actions/upload-artifact@v4
        with:
          name: SDK
          compression-level: 0
          if-no-files-found: error
          path: |
            webrogue-x86_64-linux.tar.gz
            webrogue-x86_64-windows.zip
            webrogue-x86_64-macos.tar.gz
            webrogue-arm64-macos.tar.gz
