name: Webrogue artifacts

on:
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Submodules
      run: |
        git submodule update --init --recursive --single-branch external/wasmer/;
        git submodule update --init --recursive --single-branch external/xz/;
        git submodule update --init --recursive --single-branch external/dirent/;
        git submodule update --init --recursive --single-branch external/pdcurses/;
        git submodule update --init --recursive --single-branch external/libuv/;
        git submodule update --init --recursive --single-branch external/uvwasi/;
        
    - name: Build
      run: |
        ./platforms/Windows/build.ps1 Release;

    - uses: actions/upload-artifact@v4
      with:
        name: Artifacts-Windows
        path: ./artifacts

  web:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Submodules
      run: |
        git submodule update --init --recursive --single-branch \
          external/xz/ \
          external/libuv/ \
          external/uvwasi/

    - name: Install Emscripten
      run: |
        git clone https://github.com/emscripten-core/emsdk.git
        ./emsdk/emsdk install latest
        ./emsdk/emsdk activate latest
    
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'

    - name: Configure and build
      run: |        
        . ./emsdk/emsdk_env.sh
        emcmake cmake -B platforms/Web/build -S platforms/Web -DCMAKE_BUILD_TYPE=Release
        cmake --build platforms/Web/build --target pack_artifacts -j

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Artifacts-Web
        path: |
          ./artifacts
      
  linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Submodules
      run: |
        git submodule update --init --recursive --single-branch external/wasmer/
        git submodule update --init --recursive --single-branch external/xz/
        git submodule update --init --recursive --single-branch external/argparse/
        git submodule update --init --recursive --single-branch external/libuv/
        git submodule update --init --recursive --single-branch external/uvwasi/

    - name: Apt
      run: |
        sudo apt update
        sudo apt-get install -y libsdl2-dev libsdl2-ttf-dev 

    - name: Configure and build
      run: |
        cmake -S platforms/Linux -B platforms/Linux/build -DCMAKE_BUILD_TYPE=Release
        cmake --build platforms/Linux/build --target pack_executable_to_artifacts -j

    - uses: actions/upload-artifact@v4
      with:
        name: Artifacts-Linux
        path: |
          ./artifacts

  dos:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Apt
      run: |
        sudo apt-get install -y libfl2

    - name: Submodules
      run: |
        git submodule update --init --recursive --single-branch external/xz/
        git submodule update --init --recursive --single-branch external/argparse/
        git submodule update --init --recursive --single-branch external/pdcurses/
        git submodule update --init --recursive --single-branch external/libuv/
        git submodule update --init --recursive --single-branch external/uvwasi/

    - name: Install DJGPP toolchain
      run: |
        wget https://github.com/andrewwutw/build-djgpp/releases/download/v3.4/djgpp-linux64-gcc1220.tar.bz2
        sudo tar -xjvf djgpp-linux64-gcc1220.tar.bz2 -C /usr/local/

    - name: Configure and build
      run: |
        cmake --toolchain=djgpp_toolchain.cmake -S platforms/DOS/ -B platforms/DOS/build -DCMAKE_BUILD_TYPE=Release
        cmake --build platforms/DOS/build --target pack_executable_to_artifacts -j

    - uses: actions/upload-artifact@v4
      with:
        name: Artifacts-DOS
        path: |
          ./artifacts

  android:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Submodules
        run: |
          git submodule update --init --recursive --single-branch external/wamr/
          git submodule update --init --recursive --single-branch external/wasmer/
          git submodule update --init --recursive --single-branch external/xz/
          git submodule update --init --recursive --single-branch external/SDL/
          git submodule update --init --recursive --single-branch external/SDL_ttf/
          git submodule update --init --recursive --single-branch external/libuv/
          git submodule update --init --recursive --single-branch external/uvwasi/

      - name: Install rust targets
        run: |
          rustup target add aarch64-linux-android
          rustup target add x86_64-linux-android

      - name: Build
        run: |
          cd platforms/Android
          ORG_GRADLE_PROJECT_RELEASE_STORE_PASSWORD=${{ secrets.ANDROID_STORE_PASSWORD }} ORG_GRADLE_PROJECT_RELEASE_KEY_PASSWORD=${{ secrets.ANDROID_KEY_PASSWORD }} ./gradlew --no-daemon assembleRelease
          cd ../..
          rm -rf artifacts
          mkdir artifacts
          cp ./platforms/Android/app/build/outputs/apk/release/app-release.apk artifacts/webrogue.apk

      - uses: actions/upload-artifact@v4
        with:
          name: Artifacts-Android
          path: artifacts/webrogue.apk

  macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Submodules
      run: |
        git submodule update --init --recursive --single-branch external/xz/
        git submodule update --init --recursive --single-branch external/libuv/
        git submodule update --init --recursive --single-branch external/uvwasi/
        git submodule update --init --recursive --single-branch external/wasmer/
        git submodule update --init --recursive --single-branch external/SDL/
        git submodule update --init --recursive --single-branch external/SDL_ttf/


    - name: Install rust tools
      run: |
        rustup target add aarch64-apple-darwin
        cargo install cargo-lipo

    - name: Cmake Cache
      uses: actions/cache@v4
      with:
        path: platforms/MacOS/cmake_build/CMakeCache.txt
        key: macos-cmake-cache

    - name: Configure and build
      run: |
        sh platforms/MacOS/build.sh --release --universal

    - name: Pack to DMG
      run: |
        npm install --global create-dmg
        create-dmg artifacts/Webrogue.app artifacts --dmg-title=Webrogue || true
        mv artifacts/webrogue\ 0.1.dmg Webrogue.dmg

    - uses: actions/upload-artifact@v4
      with:
        name: Artifacts-MacOS
        path: |
          Webrogue.dmg

  ios:
    runs-on: macos-latest
        
    steps:
      - uses: actions/checkout@v4
      
      - name: Submodules
        run: |
          git submodule update --init --recursive --single-branch external/xz/
          git submodule update --init --recursive --single-branch external/libuv/
          git submodule update --init --recursive --single-branch external/uvwasi/
          git submodule update --init --recursive --single-branch external/wasm3/
          git submodule update --init --recursive --single-branch external/wasmer/
          git submodule update --init --recursive --single-branch platforms/iOS/external/SnapKit
          git submodule update --init --recursive --single-branch external/SDL/
          git submodule update --init --recursive --single-branch external/SDL_ttf/
        
      - name: Install rust tools
        run: |
          cargo install cargo-lipo
          rustup target add aarch64-apple-ios
  
      - name: Cmake Cache
        uses: actions/cache@v4
        with:
          path: platforms/iOS/cmake_build/CMakeCache.txt
          key: ios-cmake-cache

      - name: Configure and build
        run: |
          sh platforms/iOS/build.sh --release

  update_pages:
    needs: [windows, web, linux, dos, android, macos, ios]
    env:
      GH_TOKEN: ${{secrets.PAGES_UPDATE_TOKEN}}
    runs-on: ubuntu-latest

    steps:
      - name: Ok
        run: |
          git clone https://github.com/webrogue-runtime/webrogue-runtime.github.io.git &&
          cd webrogue-runtime.github.io &&
          gh workflow run update_submodule
