on:
  workflow_call:
    inputs:
      is_release:
        required: true
        type: boolean

jobs:
  example_matrix:
    strategy:
      matrix:
        platform: [windows, linux, macos, android, ios, web, dos]

    uses: ./.github/workflows/build_platform_${{ matrix.platform }}.yml
    with:
      is_release: ${{inputs.is_release}}
