name: Build AOT artifacts

on:
  workflow_dispatch

jobs:
  linux_artifacts:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Submodules
      run: |
        git submodule update --init --single-branch external/wasmtime external/aemu external/gfxstream
    
    - name: Build AOT artifacts
      run: |
        sh linux/build_template.sh

    - uses: actions/upload-artifact@v4
      with:
        name: Artifacts-Linux
        path: |
          aot_artifacts/x86_64-linux-gnu

  windows_artifacts:
    runs-on: ubuntu-latest # Surprisingly

    steps:
    - uses: actions/checkout@v4

    - name: Submodules
      run: |
        git submodule update --init --single-branch external/wasmtime external/aemu external/gfxstream
    
    - name: Setup Rust
      run: |
        rustup target add x86_64-pc-windows-msvc
  
    - name: Build AOT artifacts
      run: |
        sh windows/msvc/build_template.sh

    - uses: actions/upload-artifact@v4
      with:
        name: Artifacts-Windows
        path: |
          aot_artifacts/x86_64-windows-msvc

  android_artifacts:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Submodules
      run: |
        git submodule update --init --single-branch external/wasmtime external/aemu external/gfxstream
    
    - name: Setup Rust
      run: |
        rustup target add aarch64-linux-android
  
    - name: Build AOT artifacts
      run: |
        android/template/build_template.sh

    - uses: actions/upload-artifact@v4
      with:
        name: Artifacts-Android
        path: |
          aot_artifacts/android_gradle
