name: Build AOT artifacts

on:
  workflow_dispatch

jobs:
  linux_artifacts:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Submodules
      run: |
        git submodule update --init --single-branch external/wasmtime external/aemu external/gfxstream
    
    - name: Build AOT artifacts
      run: |
        sh linux/build_template.sh

    - uses: actions/upload-artifact@v4
      with:
        name: Artifacts-Linux
        retention-days: 1
        path: aot_artifacts/x86_64-linux-gnu

  windows_artifacts:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Submodules
      run: |
        git submodule update --init --single-branch external/wasmtime external/aemu external/gfxstream

    - name: Setup Python
      run: |
        python3 -m pip install requests
        python3 -m pip install tqdm

    - name: Build AOT artifacts
      shell: cmd 
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat"
        python3 windows/msvc/build_template.py

    - uses: actions/upload-artifact@v4
      with:
        name: Artifacts-Windows
        retention-days: 1
        path: aot_artifacts/x86_64-windows-msvc

  android_artifacts:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Submodules
      run: |
        git submodule update --init --single-branch external/wasmtime external/aemu external/gfxstream
    
    - name: Setup Rust
      run: |
        rustup target add aarch64-linux-android
  
    - name: Build AOT artifacts
      run: |
        sh android/template/build_template.sh

    - uses: actions/upload-artifact@v4
      with:
        name: Artifacts-Android
        retention-days: 1
        path: aot_artifacts/android_gradle

  apple_artifacts:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Submodules
      run: |
        git submodule update --init --single-branch external/wasmtime external/aemu external/gfxstream

    - name: Install Xcodegen
      run: |
        brew install xcodegen
    
    - name: Setup Rust
      run: |
        rustup target add x86_64-apple-darwin
        rustup target add x86_64-apple-ios
        rustup target add aarch64-apple-darwin
        rustup target add aarch64-apple-ios
        rustup target add aarch64-apple-ios-sim
  
    - name: Build AOT artifacts
      run: |
        sh apple/template/build_template.sh

    - uses: actions/upload-artifact@v4
      with:
        name: Artifacts-Apple
        retention-days: 1
        path: aot_artifacts/apple_xcode

  combine:
    needs: [linux_artifacts, windows_artifacts, android_artifacts, apple_artifacts]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with: 
        name: Artifacts-Linux
        path: aot_artifacts/x86_64-linux-gnu

    - uses: actions/download-artifact@v4
      with: 
        name: Artifacts-Windows
        path: aot_artifacts/x86_64-windows-msvc

    - uses: actions/download-artifact@v4
      with: 
        name: Artifacts-Android
        path: aot_artifacts/android_gradle

    - uses: actions/download-artifact@v4
      with: 
        name: Artifacts-Apple
        path: aot_artifacts/apple_xcode

    - uses: actions/upload-artifact@v4
      with:
        name: Artifacts
        path: aot_artifacts
