name: Webrogue CI

on: 
  pull_request:
    branches: [ main ]
  merge_group:
    types: [ checks_requested ]

concurrency:
  group: ci-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  checks_and_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: ubuntu-24.04
        - os: windows-latest
        - os: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Submodules
      run: |
        git submodule update --init --single-branch --depth=1 external/wasmtime external/gfxstream external/zstd-rs
        git -C external/zstd-rs/ submodule update --init zstd-safe/zstd-sys/zstd

    - uses: taiki-e/install-action@v2
      with:
        tool: cargo-ndk

    - name: Python dependencies (macOS)
      if: startsWith(matrix.os, 'macos') == true
      run: |
        brew install python3-tqdm

    - name: Python dependencies (Windows/Linux)
      if: startsWith(matrix.os, 'macos') == false
      run: |
        python3 -m pip install tqdm

    - name: Cargo test (UNIX)
      if: startsWith(matrix.os, 'windows') == false
      run: |
        export CARGO_NDK_PLATFORM=$(cat android/android_api_version.txt)
        python3 scripts/cargo_check.py
        cargo test --package webrogue-wasip1

    - name: Cargo test (Windows)
      if: startsWith(matrix.os, 'windows') == true
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat"
        REM gfxstream doesn't seem to support MSVC
        set CXX=clang-cl
        python3 scripts\cargo_check.py
        cargo test --package webrogue-wasip1

  typos:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Install and run typos-cli
      run: |
        curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
        cargo binstall --locked typos-cli
        typos

  build_cli:
    uses: ./.github/workflows/build_cli.yml
