name: Webrogue CI

on: [push]
jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Submodules
      run: |
        git submodule update --init --single-branch --depth=1 external/wasmtime external/gfxstream external/zstd-rs
        git -C external/zstd-rs/ submodule update --init zstd-safe/zstd-sys/zstd

    - name: Cargo test
      run: |
        cargo test --package webrogue-wasip1

  windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Submodules
      run: |
        git submodule update --init --single-branch --depth=1 external/wasmtime external/gfxstream external/zstd-rs
        git -C external/zstd-rs/ submodule update --init zstd-safe/zstd-sys/zstd

    - name: Cargo test
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat"
        REM gfxstream doesn't seem to support MSVC
        set CXX=clang-cl
        cargo test --package webrogue-wasip1

  macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Submodules
      run: |
        git submodule update --init --single-branch --depth=1 external/wasmtime external/gfxstream external/zstd-rs
        git -C external/zstd-rs/ submodule update --init zstd-safe/zstd-sys/zstd

    - name: Cargo test
      run: |
        cargo test --package webrogue-wasip1

  typos:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install and run typos-cli
      run: |
        cargo binstall --locked typos-cli

  build_cli:
    uses: ./.github/workflows/build_cli.yml
