name: Dry build

on:
  push:

jobs:
  macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Submodules
      run: |
        git submodule update --init external/wasmer
    
    - name: Setup
      run: |
        rustup target add x86_64-apple-darwin
        rustup target add aarch64-apple-darwin
        brew install xcodegen
        sh apple/runtime/setup.command

    - name: Build
      shell: sh # does not works on zsh
      run: |
        XCODEBUILD_FLAGS="-destination generic/platform=macOS -workspace apple/runtime/webrogue.xcworkspace -scheme MacOS_Launcher_ReleaseLocal -configuration ReleaseLocal"
        XC_BUILD_DIR=$(xcodebuild $XCODEBUILD_FLAGS -showBuildSettings | grep -m 1 "BUILT_PRODUCTS_DIR =" | grep -oEi "\/.*" || exit 3)
        xcodebuild $XCODEBUILD_FLAGS -parallelizeTargets -allowProvisioningUpdates
        du -h -d 0 $XC_BUILD_DIR/webrogue\ Launcher.app

  ios:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Submodules
      run: |
        git submodule update --init external/wasmer
    
    - name: Setup
      run: |
        rustup target add aarch64-apple-ios
        rustup target add x86_64-apple-ios
        rustup target add aarch64-apple-ios-sim
        brew install xcodegen
        brew install ninja
        sh apple/runtime/setup.command

    - name: Build
      shell: sh # does not works on zsh
      run: |
        XCODEBUILD_FLAGS="-workspace apple/runtime/webrogue.xcworkspace -scheme iOS_ReleaseLocal -configuration ReleaseLocal -destination"
        XCODEBUILD_DESTINATION_FLAGS="generic/platform=iOS Simulator"
        XC_BUILD_DIR=$(xcodebuild $XCODEBUILD_FLAGS "$XCODEBUILD_DESTINATION_FLAGS" -showBuildSettings | grep -m 1 "BUILT_PRODUCTS_DIR =" | grep -oEi "\/.*" || exit 3)
        xcodebuild $XCODEBUILD_FLAGS "$XCODEBUILD_DESTINATION_FLAGS" -parallelizeTargets -allowProvisioningUpdates
        XC_BUILD_DIR=$(echo $XC_BUILD_DIR | sed "s/iphoneos/iphonesimulator/")
        du -h -d 0 $XC_BUILD_DIR/webrogue.app

  android:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Submodules
      run: |
        git submodule update --init external/wasmer
        git submodule update --init --recursive --single-branch examples
    
    - name: Setup
      run: |
        rustup target add aarch64-linux-android
        rustup target add x86_64-linux-android

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    # - name: Build template
    #   run: |
    #     unset ANDROID_SDK_ROOT
    #     unset ANDROID_NDK
    #     unset ANDROID_NDK_HOME
    #     unset ANDROID_NDK_LATEST_HOME
    #     unset ANDROID_NDK_ROOT
    #     unset ANDROID_SDK_ROOT

    #     sh android/template/build_template.sh

    - name: Build launcher
      run: |
        unset ANDROID_SDK_ROOT
        unset ANDROID_NDK
        # unset ANDROID_NDK_HOME
        unset ANDROID_NDK_LATEST_HOME
        unset ANDROID_NDK_ROOT
        unset ANDROID_SDK_ROOT

        cd android/runtime
        ./gradlew --no-daemon :launcher:assembleRelease
        cd ..
        du -h android/runtime/launcher/build/outputs/apk/release/launcher-release-unsigned.apk
