name: Dry build

on:
  push:

jobs:
  macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Submodules
      run: |
        git submodule update --init external/wasmtime
    
    - name: Setup
      run: |
        brew install xcodegen
        sh apple/setup.command

    - name: Build for macOS
      shell: sh # does not works on zsh
      run: |
        XCODEBUILD_FLAGS="-destination generic/platform=macOS -workspace apple/webrogue.xcworkspace -scheme MacOS_Release -configuration Release"
        XC_BUILD_DIR=$(xcodebuild $XCODEBUILD_FLAGS -showBuildSettings | grep -m 1 "BUILT_PRODUCTS_DIR =" | grep -oEi "\/.*" || exit 3)
        xcodebuild $XCODEBUILD_FLAGS -parallelizeTargets
        du -h -d 0 $XC_BUILD_DIR/webrogue\ Launcher.app

    - name: Build for iOS
      shell: sh # does not works on zsh
      run: |
        XCODEBUILD_FLAGS="-destination generic/platform=iOS -workspace apple/webrogue.xcworkspace -scheme iOS_Release -configuration Release"
        XC_BUILD_DIR=$(xcodebuild $XCODEBUILD_FLAGS -showBuildSettings | grep -m 1 "BUILT_PRODUCTS_DIR =" | grep -oEi "\/.*" || exit 3)
        xcodebuild $XCODEBUILD_FLAGS -parallelizeTargets
        du -h -d 0 $XC_BUILD_DIR/webrogue.app 
