name: CI/CD

on:
  push:
    branches: 
      main
      develop
    
jobs:
  build_debug:
    uses: ./.github/workflows/build.yml
    with:
      is_release: false
  build_release:
    if: ${{ github.ref_name == 'main' }}
    uses: ./.github/workflows/build.yml
    needs: build_debug
    with:
      is_release: true
  deploy:
    permissions:
      pages: write
      id-token: write
    needs: build_release
    uses: ./.github/workflows/deploy.yml
