name: CI/CD

on:
  push:
    
jobs:
  dbg:
    uses: ./.github/workflows/build.yml
    with:
      is_release: false
  rel:
    if: ${{ github.ref_name == 'main' }}
    uses: ./.github/workflows/build.yml
    needs: dbg
    with:
      is_release: true
  deploy:
    permissions:
      pages: write
      id-token: write
    needs: rel
    uses: ./.github/workflows/deploy.yml
