name: CI/CD

on:
  push:
    
jobs:
  debug:
    uses: ./.github/workflows/build.yml
    with:
      is_release: false
  release:
    if: ${{ github.ref_name == 'main' }}
    uses: ./.github/workflows/build.yml
    needs: debug
    with:
      is_release: true
  mods:
    uses: ./.github/workflows/build_mods.yml
    with:
      is_release: ${{ github.ref_name == 'main' }}
  deploy:
    permissions:
      pages: write
      id-token: write
    needs: [release, mods]
    uses: ./.github/workflows/deploy.yml
