name: Release Webrogue CLI

on:
  push:
    tags:
    - 'v*.*.*'
  workflow_dispatch:
  schedule:
  - cron: "37 13 * * 0"

jobs:
  build:
    uses: ./.github/workflows/build_cli.yml

  release:
    needs: build
    runs-on: ubuntu-slim
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v7

    - uses: actions/download-artifact@v8
      with: 
        name: Artifacts-Linux-GNU-x86_64
        path: aot_artifacts

    - uses: actions/download-artifact@v8
      with: 
        name: Artifacts-Linux-GNU-aarch64
        path: aot_artifacts

    - uses: actions/download-artifact@v8
      with: 
        name: Artifacts-Linux-MUSL-x86_64
        path: aot_artifacts

    - uses: actions/download-artifact@v8
      with: 
        name: Artifacts-Linux-MUSL-aarch64
        path: aot_artifacts

    - uses: actions/download-artifact@v8
      with: 
        name: Artifacts-Windows
        path: aot_artifacts

    - uses: actions/download-artifact@v8
      with: 
        name: Artifacts-Android
        path: aot_artifacts

    - uses: actions/download-artifact@v8
      with: 
        name: Artifacts-Apple
        path: aot_artifacts

    - name: Archive artifacts
      run: |
        cd aot_artifacts && zip -r ../aot_artifacts.zip \
          android_gradle \
          x86_64-linux-gnu aarch64-linux-gnu \
          x86_64-linux-musl aarch64-linux-musl \
          x86_64-windows-msvc \
          && cd ..
        cp aot_artifacts.zip aot_artifacts_macos.zip
        cd aot_artifacts && zip -r ../aot_artifacts_macos.zip apple_xcode && cd ..

    - uses: actions/download-artifact@v8
      with: 
        name: CLI-linux-x86_64-glibc-raw
        path: webrogue_linux_x86_64_glibc_raw

    - uses: actions/download-artifact@v8
      with: 
        name: CLI-linux-aarch64-glibc-raw
        path: webrogue_linux_aarch64_glibc_raw

    - uses: actions/download-artifact@v8
      with: 
        name: CLI-linux-x86_64-musl-raw
        path: webrogue_linux_x86_64_musl_raw

    - uses: actions/download-artifact@v8
      with: 
        name: CLI-linux-aarch64-musl-raw
        path: webrogue_linux_aarch64_musl_raw

    - uses: actions/download-artifact@v8
      with: 
        name: CLI-macOS-arm64-raw
        path: webrogue_macos_arm64_raw

    - uses: actions/download-artifact@v8
      with: 
        name: CLI-macOS-x86_64-raw
        path: webrogue_macos_x86_64_raw

    - uses: actions/download-artifact@v8
      with: 
        name: CLI-windows-x86_64-raw
        path: webrogue_windows_x86_64_raw
  
    - name: Append artifacts
      run: |
        mkdir webrogue-cli-linux-glibc-x86_64
        python3 append_artifacts.py webrogue_linux_x86_64_glibc_raw/webrogue aot_artifacts.zip webrogue-cli-linux-glibc-x86_64/webrogue
        chmod +x webrogue-cli-linux-glibc-x86_64/webrogue
        tar czf webrogue-cli-linux-glibc-x86_64.tar.gz webrogue-cli-linux-glibc-x86_64/

        mkdir webrogue-cli-linux-glibc-aarch64
        python3 append_artifacts.py webrogue_linux_aarch64_glibc_raw/webrogue aot_artifacts.zip webrogue-cli-linux-glibc-aarch64/webrogue
        chmod +x webrogue-cli-linux-glibc-aarch64/webrogue
        tar czf webrogue-cli-linux-glibc-aarch64.tar.gz webrogue-cli-linux-glibc-aarch64/

        mkdir webrogue-cli-linux-musl-x86_64
        python3 append_artifacts.py webrogue_linux_x86_64_musl_raw/webrogue aot_artifacts.zip webrogue-cli-linux-musl-x86_64/webrogue
        chmod +x webrogue-cli-linux-musl-x86_64/webrogue
        tar czf webrogue-cli-linux-musl-x86_64.tar.gz webrogue-cli-linux-musl-x86_64/

        mkdir webrogue-cli-linux-musl-aarch64
        python3 append_artifacts.py webrogue_linux_aarch64_musl_raw/webrogue aot_artifacts.zip webrogue-cli-linux-musl-aarch64/webrogue
        chmod +x webrogue-cli-linux-musl-aarch64/webrogue
        tar czf webrogue-cli-linux-musl-aarch64.tar.gz webrogue-cli-linux-musl-aarch64/

        mkdir webrogue-cli-windows-x86_64
        python3 append_artifacts.py webrogue_windows_x86_64_raw/webrogue.exe aot_artifacts.zip webrogue-cli-windows-x86_64/webrogue.exe
        zip -r webrogue-cli-windows-x86_64.zip webrogue-cli-windows-x86_64/

        mkdir webrogue-cli-macos-arm64
        python3 append_artifacts.py webrogue_macos_arm64_raw/webrogue aot_artifacts_macos.zip webrogue-cli-macos-arm64/webrogue
        chmod +x webrogue-cli-macos-arm64/webrogue
        tar czf webrogue-cli-macos-arm64.tar.gz webrogue-cli-macos-arm64/

        mkdir webrogue-cli-macos-x86_64
        python3 append_artifacts.py webrogue_macos_x86_64_raw/webrogue aot_artifacts_macos.zip webrogue-cli-macos-x86_64/webrogue
        chmod +x webrogue-cli-macos-x86_64/webrogue
        tar czf webrogue-cli-macos-x86_64.tar.gz webrogue-cli-macos-x86_64/

    - uses: ncipollo/release-action@v1
      if: github.event_name == 'push'
      with:
        artifacts: |
          webrogue-cli-linux-glibc-x86_64.tar.gz
          webrogue-cli-linux-glibc-aarch64.tar.gz
          webrogue-cli-linux-musl-x86_64.tar.gz
          webrogue-cli-linux-musl-aarch64.tar.gz
          webrogue-cli-windows-x86_64.zip
          webrogue-cli-macos-arm64.tar.gz
          webrogue-cli-macos-x86_64.tar.gz
        name: Release ${{ github.ref_name }}
        tag: ${{ github.ref_name }}
        makeLatest: true

    - uses: actions/upload-artifact@v7
      with:
        name: CLI-linux-x86_64-glibc
        retention-days: 1
        if-no-files-found: error
        path: |
          webrogue-cli-linux-glibc-x86_64.tar.gz

    - uses: actions/upload-artifact@v7
      with:
        name: CLI-linux-aarch64-glibc
        retention-days: 1
        if-no-files-found: error
        path: |
          webrogue-cli-linux-glibc-aarch64.tar.gz

    - uses: actions/upload-artifact@v7
      with:
        name: CLI-linux-x86_64-musl
        retention-days: 1
        if-no-files-found: error
        path: |
          webrogue-cli-linux-musl-x86_64.tar.gz

    - uses: actions/upload-artifact@v7
      with:
        name: CLI-linux-aarch64-musl
        retention-days: 1
        if-no-files-found: error
        path: |
          webrogue-cli-linux-musl-aarch64.tar.gz

    - uses: actions/upload-artifact@v7
      with:
        name: CLI-windows-x86_64
        retention-days: 1
        if-no-files-found: error
        path: |
          webrogue-cli-windows-x86_64.zip

    - uses: actions/upload-artifact@v7
      with:
        name: CLI-macOS-arm64
        retention-days: 1
        if-no-files-found: error
        path: |
          webrogue-cli-macos-arm64.tar.gz

    - uses: actions/upload-artifact@v7
      with:
        name: CLI-macOS-x86_64
        retention-days: 1
        if-no-files-found: error
        path: |
          webrogue-cli-macos-x86_64.tar.gz
