name: Reusable build workflow

on:
  workflow_call:
    inputs:
      is_release:
        required: true
        type: boolean
    # secrets:
    #   token:
    #     required: true

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Submodules
      run: |
        git submodule update --init --recursive --single-branch external/wasmer/;
        git submodule update --init --recursive --single-branch external/xz/;
        git submodule update --init --recursive --single-branch external/dirent/;
        git submodule update --init --recursive --single-branch external/pdcurses/;
        git submodule update --init --recursive --single-branch external/libuv/;
        git submodule update --init --recursive --single-branch external/uvwasi/;

    - uses: ilammy/msvc-dev-cmd@v1
    
    - name: Install packages
      run: |
        python3 -m pip install zstd
        
    - name: Build
      run: |
        ./platforms/Windows/build.ps1 Release;

  web:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Submodules
      run: |
        git submodule update --init --recursive --single-branch \
          external/xz/ \
          external/libuv/ \
          external/uvwasi/

    - name: Install Emscripten
      run: |
        git clone https://github.com/emscripten-core/emsdk.git
        ./emsdk/emsdk install latest
        ./emsdk/emsdk activate latest
    
    - name: Install packages
      run: |
        sudo apt-get install python3-zstd

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'

    - name: Configure and build
      run: |        
        . ./emsdk/emsdk_env.sh
        emcmake cmake -B platforms/Web/build -S platforms/Web -DCMAKE_BUILD_TYPE=Debug
        cmake --build platforms/Web/build --target pack_artifacts -j

  linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Submodules
      run: |
        git submodule update --init --recursive --single-branch external/wasmer/
        git submodule update --init --recursive --single-branch external/xz/
        git submodule update --init --recursive --single-branch external/argparse/
        git submodule update --init --recursive --single-branch external/libuv/
        git submodule update --init --recursive --single-branch external/uvwasi/
        git submodule update --init --recursive --single-branch external/SDL/
        git submodule update --init --recursive --single-branch external/SDL_ttf/

    - name: Install packages
      run: |
        sudo apt-get install python3-zstd

    - name: Configure and build
      run: |
        cmake -S platforms/Linux -B platforms/Linux/build -DCMAKE_BUILD_TYPE=Debug
        cmake --build platforms/Linux/build --target webrogue --parallel 

  dos:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install packages
      run: |
        sudo apt-get install -y libfl2
        sudo apt-get install python3-zstd

    - name: Submodules
      run: |
        git submodule update --init --recursive --single-branch external/xz/
        git submodule update --init --recursive --single-branch external/argparse/
        git submodule update --init --recursive --single-branch external/pdcurses/
        git submodule update --init --recursive --single-branch external/libuv/
        git submodule update --init --recursive --single-branch external/uvwasi/

    - name: Install DJGPP toolchain
      run: |
        wget https://github.com/andrewwutw/build-djgpp/releases/download/v3.4/djgpp-linux64-gcc1220.tar.bz2
        sudo tar -xjvf djgpp-linux64-gcc1220.tar.bz2 -C /usr/local/

    - name: Configure and build
      run: |
        cmake --toolchain=djgpp_toolchain.cmake -S platforms/DOS/ -B platforms/DOS/build -DCMAKE_BUILD_TYPE=Debug
        cmake --build platforms/DOS/build --target pack_executable_to_artifacts -j 

  android:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Submodules
        run: |
          git submodule update --init --recursive --single-branch external/wamr/
          git submodule update --init --recursive --single-branch external/wasmer/
          git submodule update --init --recursive --single-branch external/xz/
          git submodule update --init --recursive --single-branch external/SDL/
          git submodule update --init --recursive --single-branch external/SDL_ttf/
          git submodule update --init --recursive --single-branch external/libuv/
          git submodule update --init --recursive --single-branch external/uvwasi/

      - name: Install packages
        run: |
          sudo apt-get install python3-zstd

      - name: Install rust targets
        run: |
          rustup target add aarch64-linux-android
          rustup target add x86_64-linux-android

      - name: build
        run: |
          cd platforms/Android
          ./gradlew --no-daemon assembleDebug

  macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Submodules
      run: |
        git submodule update --init --recursive --single-branch external/xz/
        git submodule update --init --recursive --single-branch external/libuv/
        git submodule update --init --recursive --single-branch external/uvwasi/
        git submodule update --init --recursive --single-branch external/wasmer/
        git submodule update --init --recursive --single-branch external/SDL/
        git submodule update --init --recursive --single-branch external/SDL_ttf/

    - name: Install packages
      run: |
        python3 -m venv .venv
        . .venv/bin/activate
        python3 -m pip install zstd

    - name: Install rust tools
      run: |
        cargo install cargo-lipo

    - name: Cmake Cache
      uses: actions/cache@v4
      with:
        path: platforms/MacOS/cmake_build/CMakeCache.txt
        key: macos-cmake-cache

    - name: Configure and build
      run: |
        . .venv/bin/activate
        sh platforms/MacOS/build.sh --release

  ios:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Submodules
      run: |
        git submodule update --init --recursive --single-branch external/xz/
        git submodule update --init --recursive --single-branch external/libuv/
        git submodule update --init --recursive --single-branch external/uvwasi/
        git submodule update --init --recursive --single-branch external/wasm3/
        git submodule update --init --recursive --single-branch external/wasmer/
        git submodule update --init --recursive --single-branch platforms/iOS/external/SnapKit
        git submodule update --init --recursive --single-branch external/SDL/
        git submodule update --init --recursive --single-branch external/SDL_ttf/

    - name: Install packages
      run: |
        python3 -m venv .venv
        . .venv/bin/activate
        python3 -m pip install zstd

    - name: Install rust tools
      run: |
        cargo install cargo-lipo
        rustup target add aarch64-apple-ios

    - name: Cmake Cache
      uses: actions/cache@v4
      with:
        path: platforms/iOS/cmake_build/CMakeCache.txt
        key: ios-cmake-cache

    - name: Configure and build
      run: |
        . .venv/bin/activate
        sh platforms/iOS/build.sh --release

  mods:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Submodules
      run: |
        git submodule update --init --single-branch --recursive mods/brogue
        git submodule update --init --single-branch --recursive mods/coremark
        git submodule update --init --single-branch --recursive mods/rugpt2
        
    - name: Install packages
      run: |
        sudo apt-get install python3-zstd
        rustup target add wasm32-wasi

    - name: Build mods
      run: |
        cmake -DWEBROGUE_MOD_NAMES="core;log2048" -DMODS_BUILD_DIR=mods_build -P mods/tools/build.cmake
        cmake -DWEBROGUE_MOD_NAMES="core;brogue" -DMODS_BUILD_DIR=mods_build -P mods/tools/build.cmake
        cmake -DWEBROGUE_MOD_NAMES="core;coremark" -DMODS_BUILD_DIR=mods_build -P mods/tools/build.cmake
        cmake -DWEBROGUE_MOD_NAMES="core;rugpt2" -DMODS_BUILD_DIR=mods_build -P mods/tools/build.cmake
        cmake -DWEBROGUE_MOD_NAMES="core;langExampleCore;langExampleC;langExampleRust;langExampleJS" -DMODS_BUILD_DIR=mods_build -P mods/tools/build.cmake
        mkdir artifacts
        mv mods/*/*.wrmod artifacts

