name: webrogue CI

on:
  push:
    
jobs:
  call_build_workflow:
    uses: ${{GITHUB_REPOSITORY}}/.github/workflows/reusable.yml@${{GITHUB_SHA}}
    with:
      config-path: .github/reusable.yml
    secrets: inherit
