name: webrogue CI

on:
  push:
    
jobs:
  build_debug:
    uses: ./.github/workflows/reusable_build.yml
    with:
      is_release: false
  build_release:
    if: ${{ github.ref_name == 'main' }}
    uses: ./.github/workflows/reusable_build.yml
    needs: build_debug
    with:
      is_release: true
  deploy:
    permissions:
      pages: write
      id-token: write
    needs: build_release
    uses: ./.github/workflows/reusable_deploy.yml
